-- DROP ALL FOREIGN KEY CONSTRAINTS

ALTER TABLE `allocation`
    DROP FOREIGN KEY `ALLOCATION_ACCOUNT_FKC`,
    DROP FOREIGN KEY `ALLOCATION_ORDER_PREFERENCE_FKC`;

ALTER TABLE `bond`
    DROP FOREIGN KEY `BONDIFKC`;

ALTER TABLE `bond_family`
    DROP FOREIGN KEY `BOND_FAMILYIFKC`;

ALTER TABLE `broker_parameters`
    DROP FOREIGN KEY `BROKER_PARAMETERS_SECURITY_FKC`;

ALTER TABLE `cash_balance`
    DROP FOREIGN KEY `CASH_BALANCE_STRATEGY_FKC`;

ALTER TABLE `combination`
    DROP FOREIGN KEY `COMBINATIONIFKC`;

ALTER TABLE `commodity`
    DROP FOREIGN KEY `COMMODITYIFKC`;

ALTER TABLE `component`
    DROP FOREIGN KEY `COMPONENT_COMBINATION_FK`,
    DROP FOREIGN KEY `COMPONENT_SECURITY_FKC`;

ALTER TABLE `easy_to_borrow`
    DROP FOREIGN KEY `EASY_TO_BORROW_STOCK_FKC`;

ALTER TABLE `forex`
    DROP FOREIGN KEY `FOREXIFKC`;

ALTER TABLE `fund`
    DROP FOREIGN KEY `FUNDIFKC`;

ALTER TABLE `future`
    DROP FOREIGN KEY `FUTUREIFKC`;

ALTER TABLE `future_family`
    DROP FOREIGN KEY `FUTURE_FAMILYIFKC`;

ALTER TABLE `generic_future`
    DROP FOREIGN KEY `GENERIC_FUTUREIFKC`;

ALTER TABLE `generic_future_family`
    DROP FOREIGN KEY `GENERIC_FUTURE_FAMILYIFKC`;

ALTER TABLE `generic_tick`
    DROP FOREIGN KEY `GENERIC_TICK_SECURITY_FKC`;

ALTER TABLE `holiday`
    DROP FOREIGN KEY `HOLIDAY_MARKET_FKC`;

ALTER TABLE `implied_volatility`
    DROP FOREIGN KEY `IMPLIED_VOLATILITYIFKC`;

ALTER TABLE `index`
    DROP FOREIGN KEY `INDEXIFKC`;

ALTER TABLE `intrest_rate`
    DROP FOREIGN KEY `INTREST_RATEIFKC`;

ALTER TABLE `measurement`
    DROP FOREIGN KEY `MEASUREMENT_STRATEGY_FKC`;

ALTER TABLE `option`
    DROP FOREIGN KEY `OPTIONIFKC`;

ALTER TABLE `option_family`
    DROP FOREIGN KEY `OPTION_FAMILYIFKC`;

ALTER TABLE `order`
    DROP FOREIGN KEY `ORDER_ACCOUNT_FKC`,
    DROP FOREIGN KEY `ORDER_SECURITY_FKC`,
    DROP FOREIGN KEY `ORDER_STRATEGY_FKC`;

ALTER TABLE `order_preference`
    DROP FOREIGN KEY `ORDER_PREFERENCE_DEFAULT_ACCOC`;

ALTER TABLE `order_property`
    DROP FOREIGN KEY `ORDER_PROPERTY_ORDER_FKC`;

ALTER TABLE `order_status`
    DROP FOREIGN KEY `ORDER_STATUS_ORDER_FKC`;

ALTER TABLE `portfolio_value`
    DROP FOREIGN KEY `PORTFOLIO_VALUE_STRATEGY_FKC`;

ALTER TABLE `position`
    DROP FOREIGN KEY `POSITION_SECURITY_FKC`,
    DROP FOREIGN KEY `POSITION_STRATEGY_FKC`;

ALTER TABLE `security`
    DROP FOREIGN KEY `SECURITY_SECURITY_FAMILY_FKC`,
    DROP FOREIGN KEY `SECURITY_UNDERLYING_FKC`;

ALTER TABLE `security_family`
    DROP FOREIGN KEY `SECURITY_FAMILY_MARKET_FKC`,
    DROP FOREIGN KEY `SECURITY_FAMILY_UNDERLAYING_FKC`;

ALTER TABLE `stock`
    DROP FOREIGN KEY `STOCKIFKC`;

ALTER TABLE `subscription`
    DROP FOREIGN KEY `SUBSCRIPTION_SECURITY_FKC`,
    DROP FOREIGN KEY `SUBSCRIPTION_STRATEGY_FKC`;

ALTER TABLE `trading_hours`
    DROP FOREIGN KEY `TRADING_HOURS_EXCHANGE_FKC`;

ALTER TABLE `transaction`
    DROP FOREIGN KEY `TRANSACTION_ACCOUNT_FKC`,
    DROP FOREIGN KEY `TRANSACTION_POSITION_FKC`,
    DROP FOREIGN KEY `TRANSACTION_SECURITY_FKC`,
    DROP FOREIGN KEY `TRANSACTION_STRATEGY_FKC`;

-- CHANGE ID AND FK ATTRIBUTES

ALTER TABLE `account`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `allocation`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT,
  CHANGE COLUMN `ACCOUNT_FK` `ACCOUNT_FK` BIGINT NOT NULL,
  CHANGE COLUMN `ORDER_PREFERENCE_FK` `ORDER_PREFERENCE_FK` BIGINT NOT NULL;

ALTER TABLE `bar`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `bond`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `bond_family`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `broker_parameters`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT,
  CHANGE COLUMN `SECURITY_FAMILY_FK` `SECURITY_FAMILY_FK` BIGINT NOT NULL;

ALTER TABLE `cash_balance`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT,
  CHANGE COLUMN `STRATEGY_FK` `STRATEGY_FK` BIGINT NOT NULL;

ALTER TABLE `combination`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `commodity`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `component`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT,
  CHANGE COLUMN `SECURITY_FK` `SECURITY_FK` BIGINT NOT NULL,
  CHANGE COLUMN `COMBINATION_FK` `COMBINATION_FK` BIGINT NOT NULL;

ALTER TABLE `easy_to_borrow`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT,
  CHANGE COLUMN `STOCK_FK` `STOCK_FK` BIGINT NOT NULL;

ALTER TABLE `exchange`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `forex`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `fund`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `future`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `future_family`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `generic_future`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `generic_future_family`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `generic_tick`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT,
  CHANGE COLUMN `SECURITY_FK` `SECURITY_FK` BIGINT NOT NULL;

ALTER TABLE `holiday`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT,
  CHANGE COLUMN `EXCHANGE_FK` `EXCHANGE_FK` BIGINT NOT NULL;

ALTER TABLE `implied_volatility`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `index`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `intrest_rate`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `measurement`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT,
  CHANGE COLUMN `STRATEGY_FK` `STRATEGY_FK` BIGINT NOT NULL;

ALTER TABLE `option`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `option_family`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `order`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT,
  CHANGE COLUMN `ACCOUNT_FK` `ACCOUNT_FK` BIGINT NOT NULL,
  CHANGE COLUMN `SECURITY_FK` `SECURITY_FK` BIGINT NOT NULL,
  CHANGE COLUMN `STRATEGY_FK` `STRATEGY_FK` BIGINT NOT NULL;

ALTER TABLE `order_preference`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT,
  CHANGE COLUMN `DEFAULT_ACCOUNT_FK` `DEFAULT_ACCOUNT_FK` BIGINT DEFAULT NULL;

ALTER TABLE `order_property`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT,
  CHANGE COLUMN `ORDER_FK` `ORDER_FK` BIGINT NOT NULL;

ALTER TABLE `order_status`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT,
  CHANGE COLUMN `ORDER_FK` `ORDER_FK` BIGINT NOT NULL;

ALTER TABLE `portfolio_value`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT,
  CHANGE COLUMN `STRATEGY_FK` `STRATEGY_FK` BIGINT NOT NULL;

ALTER TABLE `position`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT,
  CHANGE COLUMN `SECURITY_FK` `SECURITY_FK` BIGINT NOT NULL,
  CHANGE COLUMN `STRATEGY_FK` `STRATEGY_FK` BIGINT NOT NULL;

ALTER TABLE `property`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT,
  CHANGE COLUMN `PROPERTY_HOLDER_FK` `PROPERTY_HOLDER_FK` BIGINT NOT NULL;

ALTER TABLE `security`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT,
  CHANGE COLUMN `UNDERLYING_FK` `UNDERLYING_FK` BIGINT DEFAULT NULL,
  CHANGE COLUMN `SECURITY_FAMILY_FK` `SECURITY_FAMILY_FK` BIGINT NOT NULL;

ALTER TABLE `security_family`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT,
  CHANGE COLUMN `UNDERLYING_FK` `UNDERLYING_FK` BIGINT DEFAULT NULL,
  CHANGE COLUMN `EXCHANGE_FK` `EXCHANGE_FK` BIGINT DEFAULT NULL;

ALTER TABLE `stock`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `strategy`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `subscription`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT,
  CHANGE COLUMN `SECURITY_FK` `SECURITY_FK` BIGINT NOT NULL,
  CHANGE COLUMN `STRATEGY_FK` `STRATEGY_FK` BIGINT NOT NULL;

ALTER TABLE `tick`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT,
  CHANGE COLUMN `SECURITY_FK` `SECURITY_FK` BIGINT NOT NULL;

ALTER TABLE `trading_hours`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT,
  CHANGE COLUMN `EXCHANGE_FK` `EXCHANGE_FK` BIGINT NOT NULL;

ALTER TABLE `transaction`
  CHANGE COLUMN `ID` `ID` BIGINT NOT NULL AUTO_INCREMENT,
  CHANGE COLUMN `SECURITY_FK` `SECURITY_FK` BIGINT DEFAULT NULL,
  CHANGE COLUMN `STRATEGY_FK` `STRATEGY_FK` BIGINT NOT NULL,
  CHANGE COLUMN `POSITION_FK` `POSITION_FK` BIGINT DEFAULT NULL,
  CHANGE COLUMN `ACCOUNT_FK` `ACCOUNT_FK` BIGINT DEFAULT NULL;

-- RESTORE ALL FOREIGN KEY CONSTRAINTS
ALTER TABLE `allocation`
  ADD CONSTRAINT `ALLOCATION_ACCOUNT_FKC` FOREIGN KEY (`ACCOUNT_FK`) REFERENCES `account` (`ID`),
  ADD CONSTRAINT `ALLOCATION_ORDER_PREFERENCE_FKC` FOREIGN KEY (`ORDER_PREFERENCE_FK`) REFERENCES `order_preference` (`ID`);

ALTER TABLE `bond`
  ADD CONSTRAINT `BONDIFKC` FOREIGN KEY (`ID`) REFERENCES `security` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `bond_family`
  ADD CONSTRAINT `BOND_FAMILYIFKC` FOREIGN KEY (`ID`) REFERENCES `security_family` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `broker_parameters`
  ADD CONSTRAINT `BROKER_PARAMETERS_SECURITY_FKC` FOREIGN KEY (`SECURITY_FAMILY_FK`) REFERENCES `security_family` (`ID`);

ALTER TABLE `cash_balance`
  ADD CONSTRAINT `CASH_BALANCE_STRATEGY_FKC` FOREIGN KEY (`STRATEGY_FK`) REFERENCES `strategy` (`ID`) ON UPDATE CASCADE;

ALTER TABLE `combination`
  ADD CONSTRAINT `COMBINATIONIFKC` FOREIGN KEY (`ID`) REFERENCES `security` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `commodity`
  ADD CONSTRAINT `COMMODITYIFKC` FOREIGN KEY (`ID`) REFERENCES `security` (`ID`);

ALTER TABLE `component`
  ADD CONSTRAINT `COMPONENT_COMBINATION_FK` FOREIGN KEY (`COMBINATION_FK`) REFERENCES `combination` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `COMPONENT_SECURITY_FKC` FOREIGN KEY (`SECURITY_FK`) REFERENCES `security` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `easy_to_borrow`
  ADD CONSTRAINT `EASY_TO_BORROW_STOCK_FKC` FOREIGN KEY (`STOCK_FK`) REFERENCES `stock` (`ID`);

ALTER TABLE `forex`
  ADD CONSTRAINT `FOREXIFKC` FOREIGN KEY (`ID`) REFERENCES `security` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `fund`
  ADD CONSTRAINT `FUNDIFKC` FOREIGN KEY (`ID`) REFERENCES `security` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `future`
  ADD CONSTRAINT `FUTUREIFKC` FOREIGN KEY (`ID`) REFERENCES `security` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `future_family`
  ADD CONSTRAINT `FUTURE_FAMILYIFKC` FOREIGN KEY (`ID`) REFERENCES `security_family` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `generic_future`
  ADD CONSTRAINT `GENERIC_FUTUREIFKC` FOREIGN KEY (`ID`) REFERENCES `security` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `generic_future_family`
  ADD CONSTRAINT `GENERIC_FUTURE_FAMILYIFKC` FOREIGN KEY (`ID`) REFERENCES `security_family` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `generic_tick`
  ADD CONSTRAINT `GENERIC_TICK_SECURITY_FKC` FOREIGN KEY (`SECURITY_FK`) REFERENCES `security` (`ID`);

ALTER TABLE `holiday`
  ADD CONSTRAINT `HOLIDAY_MARKET_FKC` FOREIGN KEY (`EXCHANGE_FK`) REFERENCES `exchange` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `implied_volatility`
  ADD CONSTRAINT `IMPLIED_VOLATILITYIFKC` FOREIGN KEY (`ID`) REFERENCES `security` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `index`
  ADD CONSTRAINT `INDEXIFKC` FOREIGN KEY (`ID`) REFERENCES `security` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `intrest_rate`
  ADD CONSTRAINT `INTREST_RATEIFKC` FOREIGN KEY (`ID`) REFERENCES `security` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `measurement`
  ADD CONSTRAINT `MEASUREMENT_STRATEGY_FKC` FOREIGN KEY (`STRATEGY_FK`) REFERENCES `strategy` (`ID`) ON UPDATE CASCADE;

ALTER TABLE `option`
  ADD CONSTRAINT `OPTIONIFKC` FOREIGN KEY (`ID`) REFERENCES `security` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `option_family`
  ADD CONSTRAINT `OPTION_FAMILYIFKC` FOREIGN KEY (`ID`) REFERENCES `security_family` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `order`
  ADD CONSTRAINT `ORDER_ACCOUNT_FKC` FOREIGN KEY (`ACCOUNT_FK`) REFERENCES `account` (`ID`),
  ADD CONSTRAINT `ORDER_SECURITY_FKC` FOREIGN KEY (`SECURITY_FK`) REFERENCES `security` (`ID`),
  ADD CONSTRAINT `ORDER_STRATEGY_FKC` FOREIGN KEY (`STRATEGY_FK`) REFERENCES `strategy` (`ID`);

ALTER TABLE `order_preference`
  ADD CONSTRAINT  `ORDER_PREFERENCE_DEFAULT_ACCOC` FOREIGN KEY (`DEFAULT_ACCOUNT_FK`) REFERENCES `account` (`ID`) ON UPDATE CASCADE;

ALTER TABLE `order_property`
  ADD CONSTRAINT `ORDER_PROPERTY_ORDER_FKC` FOREIGN KEY (`ORDER_FK`) REFERENCES `order` (`ID`);

ALTER TABLE `order_status`
  ADD CONSTRAINT `ORDER_STATUS_ORDER_FKC` FOREIGN KEY (`ORDER_FK`) REFERENCES `order` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `portfolio_value`
  ADD CONSTRAINT `PORTFOLIO_VALUE_STRATEGY_FKC` FOREIGN KEY (`STRATEGY_FK`) REFERENCES `strategy` (`ID`) ON UPDATE CASCADE;

ALTER TABLE `position`
  ADD CONSTRAINT `POSITION_SECURITY_FKC` FOREIGN KEY (`SECURITY_FK`) REFERENCES `security` (`ID`) ON UPDATE CASCADE,
  ADD CONSTRAINT `POSITION_STRATEGY_FKC` FOREIGN KEY (`STRATEGY_FK`) REFERENCES `strategy` (`ID`) ON UPDATE CASCADE;

ALTER TABLE `security`
  ADD CONSTRAINT `SECURITY_SECURITY_FAMILY_FKC` FOREIGN KEY (`SECURITY_FAMILY_FK`) REFERENCES `security_family` (`ID`) ON UPDATE CASCADE,
  ADD  CONSTRAINT `SECURITY_UNDERLYING_FKC` FOREIGN KEY (`UNDERLYING_FK`) REFERENCES `security` (`ID`) ON UPDATE CASCADE;

ALTER TABLE `security_family`
  ADD CONSTRAINT `SECURITY_FAMILY_MARKET_FKC` FOREIGN KEY (`EXCHANGE_FK`) REFERENCES `exchange` (`ID`),
  ADD CONSTRAINT `SECURITY_FAMILY_UNDERLAYING_FKC` FOREIGN KEY (`UNDERLYING_FK`) REFERENCES `security` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `stock`
  ADD CONSTRAINT `STOCKIFKC` FOREIGN KEY (`ID`) REFERENCES `security` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `subscription`
  ADD CONSTRAINT `SUBSCRIPTION_SECURITY_FKC` FOREIGN KEY (`SECURITY_FK`) REFERENCES `security` (`ID`) ON UPDATE CASCADE,
  ADD CONSTRAINT `SUBSCRIPTION_STRATEGY_FKC` FOREIGN KEY (`STRATEGY_FK`) REFERENCES `strategy` (`ID`) ON UPDATE CASCADE;

ALTER TABLE `tick`
  ADD CONSTRAINT `TICK_SECURITY_FKC` FOREIGN KEY (`SECURITY_FK`) REFERENCES `security` (`ID`);

ALTER TABLE `trading_hours`
  ADD CONSTRAINT `TRADING_HOURS_EXCHANGE_FKC` FOREIGN KEY (`EXCHANGE_FK`) REFERENCES `exchange` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `transaction`
  ADD CONSTRAINT `TRANSACTION_ACCOUNT_FKC` FOREIGN KEY (`ACCOUNT_FK`) REFERENCES `account` (`ID`) ON UPDATE CASCADE,
  ADD CONSTRAINT `TRANSACTION_POSITION_FKC` FOREIGN KEY (`POSITION_FK`) REFERENCES `position` (`ID`) ON UPDATE CASCADE,
  ADD CONSTRAINT `TRANSACTION_SECURITY_FKC` FOREIGN KEY (`SECURITY_FK`) REFERENCES `security` (`ID`) ON UPDATE CASCADE,
  ADD CONSTRAINT `TRANSACTION_STRATEGY_FKC` FOREIGN KEY (`STRATEGY_FK`) REFERENCES `strategy` (`ID`) ON UPDATE CASCADE;
