ALTER TABLE `order` CHANGE COLUMN `EXT_ID` `EXT_ID` VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_general_cs NULL DEFAULT NULL;
ALTER TABLE `order_status` CHANGE COLUMN `EXT_ID` `EXT_ID` VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_general_cs NULL DEFAULT NULL;
ALTER TABLE `transaction` CHANGE COLUMN `EXT_ID` `EXT_ID` VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_general_cs NULL DEFAULT NULL;
