INSERT INTO `account` (`ID`, `NAME`, `ACTIVE`, `BROKER`, `ORDER_SERVICE_TYPE`) VALUES 
  (1,'IB_NATIVE_TEST',1,'IB','IB_NATIVE');

INSERT INTO `exchange` (`ID`, `NAME`, `IB_CODE`, `TIME_ZONE`) VALUES
  (1,'IDEALPRO','IDEALPRO','US/Eastern');

INSERT INTO `security_family` (`ID`, `CLASS`, `NAME`, `CURRENCY`, `CONTRACT_SIZE`, `SCALE`, `TICK_SIZE_PATTERN`, `TRADEABLE`, `SYNTHETIC`, `EXCHANGE_FK`) VALUES
  (1,'SecurityFamilyImpl','USD FX','USD',1,5,'0<0.00001',1,0,1);

INSERT INTO `security` (`ID`, `CLASS`, `SYMBOL`, `CONID`, `LMAXID`, `SECURITY_FAMILY_FK`, `BASE_CURRENCY`) VALUES
  (1,'ForexImpl','EUR.USD','12087792','4001',1,'EUR');

INSERT INTO `strategy` (`ID`, `NAME`, `AUTO_ACTIVATE`, `VERSION`) VALUES
  (2, '${name.toUpperCase()}', True, 0);

INSERT INTO `order_preference` (`ID`, `NAME`, `ORDER_TYPE`, `DEFAULT_ACCOUNT_FK`, `VERSION`) VALUES
  (200, 'DEFAULT', 'MARKET', 1, 0);