INSERT INTO `account` (`ID`, `NAME`, `ACTIVE`, `BROKER`, `ORDER_SERVICE_TYPE`) VALUES (1,'IB_NATIVE_TEST',1,'IB','IB_NATIVE');

INSERT INTO `exchange` (`ID`, `NAME`, `IB_CODE`, `TIME_ZONE`) VALUES (1,'IDEALPRO','IDEALPRO','US/Eastern');

INSERT INTO `security_family` (`ID`, `NAME`, `CURRENCY`, `CONTRACT_SIZE`, `SCALE`, `TICK_SIZE_PATTERN`, `EXECUTION_COMMISSION`, `TRADEABLE`, `SYNTHETIC`, `EXCHANGE_FK`) VALUES (1,'USD FX','USD',1,5,'0<0.00005',0.00,1,0,1);

INSERT INTO `security` (`ID`, `SYMBOL`, `SECURITY_FAMILY_FK`) VALUES (1,'EUR.USD',1);

INSERT INTO `forex` (`ID`, `BASE_CURRENCY`) VALUES (1,'EUR');

INSERT INTO `strategy` (`ID`, `NAME`, `AUTO_ACTIVATE`, `ALLOCATION`, `VERSION`) VALUES (2, '${name.toUpperCase()}', True, 1, 0);