SELECT
  t1.id,
  t1.DATE_TIME,
  t1.TYPE,
  s1.SYMBOL,
  s1.RIC,
  t1.QUANTITY,
  t1.PRICE,
  t1.EXECUTION_COMMISSION AS COMMISSION,
  LEFT(t1.MARKET_CHANNEL, LOCATE('_', t1.MARKET_CHANNEL) - 1) AS MARKET_CHANNEL,
  t1.CURRENCY,
  CASE
      WHEN
      IFNULL(SUM(t2.quantity),0) = 0
    THEN
      'OPEN'
    WHEN
       SIGN(t1.QUANTITY) = SIGN(IFNULL(SUM(t2.quantity),0))
    THEN
      'OPEN'
    ELSE
      'CLOSE'
  END AS OPEN_CLOSE
FROM
  transaction t1
INNER JOIN
  security s1
ON
  t1.SECURITY_FK = s1.id
LEFT JOIN
  transaction t2
ON
  t2.SECURITY_FK = t1.SECURITY_FK
AND
  t2.DATE_TIME < t1.DATE_TIME
WHERE
  t1.TYPE = 'BUY'
OR
  t1.TYPE = 'SELL'
GROUP BY
  t1.id
ORDER BY
  cast(t1.DATE_TIME), t1.id
