;             
CREATE USER IF NOT EXISTS SA SALT 'f718438aa7460712' HASH '7b6cd45b4b095988bfd567db92976e19a12979a13eaa6a69741008ba6bb1cb66' ADMIN;           
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_8F026070_AF0F_47B9_AA27_824C14F1BD94 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_C47559EE_67A7_489D_8A20_1C67DCF4595B START WITH 2 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_5A328F84_1E5B_4206_A759_C1705B49B244 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_BA5B9B24_AA2A_49E8_8DCF_6644F87A0A92 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_417CAB6D_3230_4021_8FEC_C6BFAA7563E7 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_63FF5105_0669_4E26_B874_CBC54F500CBA START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_F25CDD3B_2034_4510_9394_277C2D62C721 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_6B39D1AC_220C_4F3A_AECF_8635A3EE8A1E START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_72D03512_702B_47BE_8EB7_292A5BDCA06D START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_805ABF73_9625_4E03_8E46_A1D03409E1DC START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_8B81F5F9_7610_41F6_9CE8_4FFA1139E570 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_B5220B25_2473_4436_B56B_D19901C433B3 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_7F4815D9_FD86_42F4_8181_5B90EF848CEA START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_A3C2EF43_9CCE_4FFD_9914_0623DCC20160 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_AE53FD4C_530A_4790_8B58_79F7796BB7EB START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_BC7873ED_4968_43E9_90CD_B3332D9C904B START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_2BEB9849_D818_4A1A_8941_1F8D7B2B8741 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_F35F79F1_2F91_4D2F_907F_ECD0A20AE6A7 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_21B0254E_79DE_4E12_9F08_B608B106218E START WITH 2 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_4219A4F5_9A5C_413C_9B2B_B9B8CF41E986 START WITH 2 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_6B046A29_91ED_4A1E_8885_710294614AF0 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_BA521665_94F9_4486_B4AF_2B89998B6AFB START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_BF7D4B5A_2481_46FC_BE82_976CE03E6B41 START WITH 1 BELONGS_TO_TABLE;    
CREATE CACHED TABLE PUBLIC."account"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_7F4815D9_FD86_42F4_8181_5B90EF848CEA) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_7F4815D9_FD86_42F4_8181_5B90EF848CEA,
    NAME VARCHAR(20) NOT NULL,
    ACTIVE BIT NOT NULL,
    BROKER VARCHAR(100) NOT NULL,
    ORDER_SERVICE_TYPE VARCHAR(100) NOT NULL,
    SESSION_QUALIFIER VARCHAR(10) DEFAULT NULL,
    EXT_ACCOUNT VARCHAR(20) DEFAULT NULL,
    EXT_ACCOUNT_GROUP VARCHAR(20) DEFAULT NULL,
    EXT_ALLOCATION_PROFILE VARCHAR(20) DEFAULT NULL,
    EXT_CLEARING_ACCOUNT VARCHAR(20) DEFAULT NULL
);   
ALTER TABLE PUBLIC."account" ADD CONSTRAINT PUBLIC.CONSTRAINT_B PRIMARY KEY(ID);              
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."account";               
CREATE INDEX PUBLIC.INDEX_B ON PUBLIC."account"(ACTIVE);      
CREATE INDEX PUBLIC.INDEX_B9 ON PUBLIC."account"(BROKER);     
CREATE INDEX PUBLIC.INDEX_B9D ON PUBLIC."account"(ORDER_SERVICE_TYPE);        
CREATE CACHED TABLE PUBLIC."allocation"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_63FF5105_0669_4E26_B874_CBC54F500CBA) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_63FF5105_0669_4E26_B874_CBC54F500CBA,
    VALUE DOUBLE NOT NULL,
    ORDER_PREFERENCE_FK INT NOT NULL,
    ACCOUNT_FK INT NOT NULL
);  
ALTER TABLE PUBLIC."allocation" ADD CONSTRAINT PUBLIC.CONSTRAINT_8 PRIMARY KEY(ID);           
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."allocation";            
CREATE INDEX PUBLIC.INDEX_8 ON PUBLIC."allocation"(ACCOUNT_FK);               
CREATE INDEX PUBLIC.INDEX_8E ON PUBLIC."allocation"(ORDER_PREFERENCE_FK);     
CREATE CACHED TABLE PUBLIC."bar"(
    ID INT NOT NULL,
    DATE_TIME DATETIME NOT NULL,
    OPEN DECIMAL(13, 6) NOT NULL,
    HIGH DECIMAL(13, 6) NOT NULL,
    LOW DECIMAL(13, 6) NOT NULL,
    CLOSE DECIMAL(13, 6) NOT NULL,
    VOL INT NOT NULL,
    BAR_SIZE VARCHAR(100) NOT NULL,
    FEED_TYPE VARCHAR(100) NOT NULL,
    SECURITY_FK INT NOT NULL
);     
ALTER TABLE PUBLIC."bar" ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID);  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."bar";   
CREATE INDEX PUBLIC.INDEX_1 ON PUBLIC."bar"(DATE_TIME);       
CREATE INDEX PUBLIC.INDEX_17 ON PUBLIC."bar"(SECURITY_FK);    
CREATE INDEX PUBLIC.INDEX_17C ON PUBLIC."bar"(BAR_SIZE);      
CREATE CACHED TABLE PUBLIC."bond"(
    ID INT NOT NULL,
    MATURITY DATE NOT NULL,
    COUPON DOUBLE NOT NULL
);         
ALTER TABLE PUBLIC."bond" ADD CONSTRAINT PUBLIC.CONSTRAINT_2 PRIMARY KEY(ID); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."bond";  
CREATE INDEX PUBLIC.INDEX_2 ON PUBLIC."bond"(MATURITY);       
CREATE INDEX PUBLIC.INDEX_2E ON PUBLIC."bond"(ID);            
CREATE CACHED TABLE PUBLIC."bond_family"(
    ID INT NOT NULL,
    MATURITY_DISTANCE VARCHAR(100) NOT NULL,
    LENGTH INT NOT NULL,
    QUOTATION_STYLE VARCHAR(100) NOT NULL
);        
ALTER TABLE PUBLIC."bond_family" ADD CONSTRAINT PUBLIC.CONSTRAINT_89 PRIMARY KEY(ID);         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."bond_family";           
CREATE INDEX PUBLIC.INDEX_89 ON PUBLIC."bond_family"(ID);     
CREATE CACHED TABLE PUBLIC."broker_parameters"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_BF7D4B5A_2481_46FC_BE82_976CE03E6B41) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_BF7D4B5A_2481_46FC_BE82_976CE03E6B41,
    BROKER VARCHAR(100) NOT NULL,
    SYMBOL_ROOT VARCHAR(20) DEFAULT NULL,
    EXCHANGE_CODE VARCHAR(20) DEFAULT NULL,
    EXECUTION_COMMISSION DECIMAL(5, 2) DEFAULT NULL,
    CLEARING_COMMISSION DECIMAL(5, 2) DEFAULT NULL,
    FEE DECIMAL(5, 2) DEFAULT NULL,
    SECURITY_FAMILY_FK INT NOT NULL
);           
ALTER TABLE PUBLIC."broker_parameters" ADD CONSTRAINT PUBLIC.CONSTRAINT_9 PRIMARY KEY(ID);    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."broker_parameters";     
CREATE INDEX PUBLIC.INDEX_9 ON PUBLIC."broker_parameters"(SECURITY_FAMILY_FK);
CREATE CACHED TABLE PUBLIC."cash_balance"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_21B0254E_79DE_4E12_9F08_B608B106218E) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_21B0254E_79DE_4E12_9F08_B608B106218E,
    CURRENCY VARCHAR(100) NOT NULL,
    AMOUNT DECIMAL(15, 2) NOT NULL,
    STRATEGY_FK INT NOT NULL,
    VERSION INT NOT NULL
);             
ALTER TABLE PUBLIC."cash_balance" ADD CONSTRAINT PUBLIC.CONSTRAINT_D PRIMARY KEY(ID);         
-- 1 +/- SELECT COUNT(*) FROM PUBLIC."cash_balance";          
INSERT INTO PUBLIC."cash_balance"(ID, CURRENCY, AMOUNT, STRATEGY_FK, VERSION) VALUES
(1, 'USD', 1000000.00, 1, 1);           
CREATE INDEX PUBLIC.INDEX_D ON PUBLIC."cash_balance"(STRATEGY_FK);            
CREATE CACHED TABLE PUBLIC."combination"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_8B81F5F9_7610_41F6_9CE8_4FFA1139E570) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_8B81F5F9_7610_41F6_9CE8_4FFA1139E570,
    UUID CHAR(36) NOT NULL,
    TYPE VARCHAR(100) NOT NULL,
    PERSISTENT BIT NOT NULL
);      
ALTER TABLE PUBLIC."combination" ADD CONSTRAINT PUBLIC.CONSTRAINT_D9 PRIMARY KEY(ID);         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."combination";           
CREATE INDEX PUBLIC.INDEX_D9 ON PUBLIC."combination"(ID);     
CREATE CACHED TABLE PUBLIC."commodity"(
    ID INT NOT NULL,
    TYPE VARCHAR(100) NOT NULL
);             
ALTER TABLE PUBLIC."commodity" ADD CONSTRAINT PUBLIC.CONSTRAINT_A PRIMARY KEY(ID);            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."commodity";             
CREATE INDEX PUBLIC.INDEX_A ON PUBLIC."commodity"(ID);        
CREATE CACHED TABLE PUBLIC."component"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_72D03512_702B_47BE_8EB7_292A5BDCA06D) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_72D03512_702B_47BE_8EB7_292A5BDCA06D,
    QUANTITY BIGINT NOT NULL,
    PERSISTENT BIT NOT NULL,
    SECURITY_FK INT NOT NULL,
    COMBINATION_FK INT NOT NULL,
    VERSION INT NOT NULL
);           
ALTER TABLE PUBLIC."component" ADD CONSTRAINT PUBLIC.CONSTRAINT_AC PRIMARY KEY(ID);           
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."component";             
CREATE INDEX PUBLIC.INDEX_AC ON PUBLIC."component"(COMBINATION_FK);           
CREATE INDEX PUBLIC.INDEX_AC8 ON PUBLIC."component"(SECURITY_FK);             
CREATE CACHED TABLE PUBLIC."easy_to_borrow"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_417CAB6D_3230_4021_8FEC_C6BFAA7563E7) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_417CAB6D_3230_4021_8FEC_C6BFAA7563E7,
    DATE DATE NOT NULL,
    BROKER VARCHAR(100) NOT NULL,
    QUANTITY BIGINT NOT NULL,
    STOCK_FK INT NOT NULL
);        
ALTER TABLE PUBLIC."easy_to_borrow" ADD CONSTRAINT PUBLIC.CONSTRAINT_80 PRIMARY KEY(ID);      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."easy_to_borrow";        
CREATE INDEX PUBLIC.INDEX_80 ON PUBLIC."easy_to_borrow"(STOCK_FK);            
CREATE CACHED TABLE PUBLIC."exchange"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_F25CDD3B_2034_4510_9394_277C2D62C721) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_F25CDD3B_2034_4510_9394_277C2D62C721,
    NAME VARCHAR(50) NOT NULL,
    CODE VARCHAR(10) NOT NULL,
    TIME_ZONE VARCHAR(50) NOT NULL
);
ALTER TABLE PUBLIC."exchange" ADD CONSTRAINT PUBLIC.CONSTRAINT_7 PRIMARY KEY(ID);             
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."exchange";              
CREATE CACHED TABLE PUBLIC."forex"(
    ID INT NOT NULL,
    BASE_CURRENCY VARCHAR(100) NOT NULL
);        
ALTER TABLE PUBLIC."forex" ADD CONSTRAINT PUBLIC.CONSTRAINT_5 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."forex"; 
CREATE INDEX PUBLIC.INDEX_5 ON PUBLIC."forex"(ID);            
CREATE CACHED TABLE PUBLIC."fund"(
    ID INT NOT NULL
);   
ALTER TABLE PUBLIC."fund" ADD CONSTRAINT PUBLIC.CONSTRAINT_3 PRIMARY KEY(ID); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."fund";  
CREATE INDEX PUBLIC.INDEX_3 ON PUBLIC."fund"(ID);             
CREATE CACHED TABLE PUBLIC."future"(
    ID INT NOT NULL,
    EXPIRATION DATE NOT NULL,
    FIRST_NOTICE DATE DEFAULT NULL,
    LAST_TRADING DATE DEFAULT NULL
);        
ALTER TABLE PUBLIC."future" ADD CONSTRAINT PUBLIC.CONSTRAINT_B4 PRIMARY KEY(ID);              
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."future";
CREATE INDEX PUBLIC.INDEX_B4 ON PUBLIC."future"(EXPIRATION);  
CREATE INDEX PUBLIC.INDEX_B4B ON PUBLIC."future"(FIRST_NOTICE);               
CREATE INDEX PUBLIC.INDEX_B4B5 ON PUBLIC."future"(LAST_TRADING);              
CREATE INDEX PUBLIC.INDEX_B4B58 ON PUBLIC."future"(ID);       
CREATE CACHED TABLE PUBLIC."future_family"(
    ID INT NOT NULL,
    INTREST DOUBLE NOT NULL,
    DIVIDEND DOUBLE NOT NULL,
    MARGIN_PARAMETER DOUBLE NOT NULL,
    EXPIRATION_TYPE VARCHAR(100) NOT NULL,
    EXPIRATION_DISTANCE VARCHAR(100) NOT NULL,
    LENGTH INT NOT NULL
);
ALTER TABLE PUBLIC."future_family" ADD CONSTRAINT PUBLIC.CONSTRAINT_E PRIMARY KEY(ID);        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."future_family";         
CREATE INDEX PUBLIC.INDEX_E ON PUBLIC."future_family"(ID);    
CREATE CACHED TABLE PUBLIC."generic_future"(
    ID INT NOT NULL,
    DURATION VARCHAR(100) NOT NULL,
    ASSET_CLASS VARCHAR(100) NOT NULL
);            
ALTER TABLE PUBLIC."generic_future" ADD CONSTRAINT PUBLIC.CONSTRAINT_21 PRIMARY KEY(ID);      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."generic_future";        
CREATE INDEX PUBLIC.INDEX_21 ON PUBLIC."generic_future"(DURATION);            
CREATE INDEX PUBLIC.INDEX_217 ON PUBLIC."generic_future"(ID); 
CREATE CACHED TABLE PUBLIC."generic_future_family"(
    ID INT NOT NULL,
    EXPIRATION_TYPE VARCHAR(100) NOT NULL,
    EXPIRATION_DISTANCE VARCHAR(100) NOT NULL
);      
ALTER TABLE PUBLIC."generic_future_family" ADD CONSTRAINT PUBLIC.CONSTRAINT_6 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."generic_future_family"; 
CREATE INDEX PUBLIC.INDEX_6 ON PUBLIC."generic_future_family"(ID);            
CREATE CACHED TABLE PUBLIC."generic_tick"(
    ID INT NOT NULL,
    DATE_TIME DATETIME NOT NULL,
    FEED_TYPE VARCHAR(100) NOT NULL,
    SECURITY_FK INT NOT NULL,
    TICK_TYPE VARCHAR(100) NOT NULL,
    MONEY_VALUE DECIMAL(13, 6) DEFAULT NULL,
    DOUBLE_VALUE DOUBLE DEFAULT NULL,
    INT_VALUE INT DEFAULT NULL
);        
ALTER TABLE PUBLIC."generic_tick" ADD CONSTRAINT PUBLIC.CONSTRAINT_F PRIMARY KEY(ID);         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."generic_tick";          
CREATE INDEX PUBLIC.INDEX_F ON PUBLIC."generic_tick"(SECURITY_FK);            
CREATE CACHED TABLE PUBLIC."holiday"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_6B39D1AC_220C_4F3A_AECF_8635A3EE8A1E) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_6B39D1AC_220C_4F3A_AECF_8635A3EE8A1E,
    DATE DATE NOT NULL,
    LATE_OPEN TIME DEFAULT NULL,
    EARLY_CLOSE TIME DEFAULT NULL,
    EXCHANGE_FK INT NOT NULL
);        
ALTER TABLE PUBLIC."holiday" ADD CONSTRAINT PUBLIC.CONSTRAINT_4 PRIMARY KEY(ID);              
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."holiday";               
CREATE INDEX PUBLIC.INDEX_4 ON PUBLIC."holiday"(EXCHANGE_FK); 
CREATE CACHED TABLE PUBLIC."implied_volatility"(
    ID INT NOT NULL,
    DURATION VARCHAR(100) NOT NULL,
    MONEYNESS DOUBLE DEFAULT NULL,
    DELTA DOUBLE DEFAULT NULL,
    TYPE VARCHAR(100) NOT NULL
);           
ALTER TABLE PUBLIC."implied_volatility" ADD CONSTRAINT PUBLIC.CONSTRAINT_1E PRIMARY KEY(ID);  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."implied_volatility";    
CREATE INDEX PUBLIC.INDEX_1E ON PUBLIC."implied_volatility"(ID);              
CREATE CACHED TABLE PUBLIC."index"(
    ID INT NOT NULL,
    ASSET_CLASS VARCHAR(100) NOT NULL
);          
ALTER TABLE PUBLIC."index" ADD CONSTRAINT PUBLIC.CONSTRAINT_5F PRIMARY KEY(ID);               
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."index"; 
CREATE INDEX PUBLIC.INDEX_5F ON PUBLIC."index"(ID);           
CREATE CACHED TABLE PUBLIC."intrest_rate"(
    ID INT NOT NULL,
    DURATION VARCHAR(100) NOT NULL
);      
ALTER TABLE PUBLIC."intrest_rate" ADD CONSTRAINT PUBLIC.CONSTRAINT_64 PRIMARY KEY(ID);        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."intrest_rate";          
CREATE INDEX PUBLIC.INDEX_64 ON PUBLIC."intrest_rate"(ID);    
CREATE CACHED TABLE PUBLIC."measurement"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_BA521665_94F9_4486_B4AF_2B89998B6AFB) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_BA521665_94F9_4486_B4AF_2B89998B6AFB,
    NAME VARCHAR(255) NOT NULL,
    DATE_TIME DATETIME NOT NULL,
    INT_VALUE INT DEFAULT NULL,
    DOUBLE_VALUE DOUBLE DEFAULT NULL,
    MONEY_VALUE DECIMAL(15, 6) DEFAULT NULL,
    TEXT_VALUE VARCHAR(50) DEFAULT NULL,
    BOOLEAN_VALUE BIT DEFAULT NULL,
    STRATEGY_FK INT NOT NULL
);           
ALTER TABLE PUBLIC."measurement" ADD CONSTRAINT PUBLIC.CONSTRAINT_93 PRIMARY KEY(ID);         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."measurement";           
CREATE INDEX PUBLIC.INDEX_93 ON PUBLIC."measurement"(STRATEGY_FK);            
CREATE CACHED TABLE PUBLIC."option"(
    ID INT NOT NULL,
    STRIKE DECIMAL(12, 5) NOT NULL,
    EXPIRATION DATE NOT NULL,
    TYPE VARCHAR(100) NOT NULL
);            
ALTER TABLE PUBLIC."option" ADD CONSTRAINT PUBLIC.CONSTRAINT_C PRIMARY KEY(ID);               
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."option";
CREATE INDEX PUBLIC.INDEX_C ON PUBLIC."option"(EXPIRATION);   
CREATE INDEX PUBLIC.INDEX_C3 ON PUBLIC."option"(STRIKE);      
CREATE INDEX PUBLIC.INDEX_C3C ON PUBLIC."option"(TYPE);       
CREATE INDEX PUBLIC.INDEX_C3CA ON PUBLIC."option"(ID);        
CREATE CACHED TABLE PUBLIC."option_family"(
    ID INT NOT NULL,
    INTREST DOUBLE NOT NULL,
    DIVIDEND DOUBLE NOT NULL,
    MARGIN_PARAMETER DOUBLE NOT NULL,
    EXPIRATION_TYPE VARCHAR(100) NOT NULL,
    EXPIRATION_DISTANCE VARCHAR(100) NOT NULL,
    STRIKE_DISTANCE DOUBLE NOT NULL,
    WEEKLY BIT NOT NULL
);          
ALTER TABLE PUBLIC."option_family" ADD CONSTRAINT PUBLIC.CONSTRAINT_B3 PRIMARY KEY(ID);       
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."option_family";         
CREATE INDEX PUBLIC.INDEX_B3 ON PUBLIC."option_family"(ID);   
CREATE CACHED TABLE PUBLIC."order"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_805ABF73_9625_4E03_8E46_A1D03409E1DC) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_805ABF73_9625_4E03_8E46_A1D03409E1DC,
    CLASS VARCHAR(255) NOT NULL,
    INT_ID VARCHAR(30) NOT NULL,
    EXT_ID VARCHAR(30) DEFAULT NULL,
    DATE_TIME DATETIME NOT NULL,
    SIDE VARCHAR(100) NOT NULL,
    QUANTITY BIGINT NOT NULL,
    TIF VARCHAR(100) NOT NULL,
    TIF_DATE_TIME DATETIME DEFAULT NULL,
    "LIMIT" DECIMAL(15, 6) DEFAULT NULL,
    STOP DECIMAL(15, 6) DEFAULT NULL,
    ACCOUNT_FK INT NOT NULL,
    SECURITY_FK INT NOT NULL,
    STRATEGY_FK INT NOT NULL
);     
ALTER TABLE PUBLIC."order" ADD CONSTRAINT PUBLIC.CONSTRAINT_65 PRIMARY KEY(ID);               
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."order"; 
CREATE INDEX PUBLIC.INDEX_65 ON PUBLIC."order"(ACCOUNT_FK);   
CREATE INDEX PUBLIC.INDEX_651 ON PUBLIC."order"(SECURITY_FK); 
CREATE INDEX PUBLIC.INDEX_6518 ON PUBLIC."order"(STRATEGY_FK);
CREATE CACHED TABLE PUBLIC."order_preference"(
    ID INT NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    ORDER_TYPE VARCHAR(100) NOT NULL,
    DEFAULT_ACCOUNT_FK INT DEFAULT NULL,
    VERSION INT NOT NULL
);           
ALTER TABLE PUBLIC."order_preference" ADD CONSTRAINT PUBLIC.CONSTRAINT_7D PRIMARY KEY(ID);    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."order_preference";      
CREATE INDEX PUBLIC.INDEX_7 ON PUBLIC."order_preference"(DEFAULT_ACCOUNT_FK); 
CREATE CACHED TABLE PUBLIC."order_property"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_BA5B9B24_AA2A_49E8_8DCF_6644F87A0A92) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_BA5B9B24_AA2A_49E8_8DCF_6644F87A0A92,
    NAME VARCHAR(30) NOT NULL,
    VALUE VARCHAR(255) NOT NULL,
    TYPE VARCHAR(100) NOT NULL,
    ORDER_FK INT NOT NULL
);
ALTER TABLE PUBLIC."order_property" ADD CONSTRAINT PUBLIC.CONSTRAINT_78 PRIMARY KEY(ID);      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."order_property";        
CREATE INDEX PUBLIC.INDEX_78 ON PUBLIC."order_property"(ORDER_FK);            
CREATE CACHED TABLE PUBLIC."order_status"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_2BEB9849_D818_4A1A_8941_1F8D7B2B8741) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_2BEB9849_D818_4A1A_8941_1F8D7B2B8741,
    DATE_TIME DATETIME NOT NULL,
    EXT_DATE_TIME DATETIME NOT NULL,
    STATUS VARCHAR(100) NOT NULL,
    FILLED_QUANTITY BIGINT NOT NULL,
    REMAINING_QUANTITY BIGINT NOT NULL,
    AVG_PRICE DECIMAL(15, 6) DEFAULT NULL,
    LAST_PRICE DECIMAL(15, 6) DEFAULT NULL,
    INT_ID VARCHAR(30) DEFAULT NULL,
    EXT_ID VARCHAR(30) DEFAULT NULL,
    SEQUENCE_NUMBER BIGINT NOT NULL,
    REASON VARCHAR(255) DEFAULT NULL,
    ORDER_FK INT NOT NULL
);         
ALTER TABLE PUBLIC."order_status" ADD CONSTRAINT PUBLIC.CONSTRAINT_3E PRIMARY KEY(ID);        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."order_status";          
CREATE INDEX PUBLIC.INDEX_3E ON PUBLIC."order_status"(ORDER_FK);              
CREATE CACHED TABLE PUBLIC."portfolio_value"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_F35F79F1_2F91_4D2F_907F_ECD0A20AE6A7) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_F35F79F1_2F91_4D2F_907F_ECD0A20AE6A7,
    DATE_TIME DATETIME NOT NULL,
    SECURITIES_CURRENT_VALUE DECIMAL(15, 6) NOT NULL,
    CASH_BALANCE DECIMAL(15, 6) NOT NULL,
    MAINTENANCE_MARGIN DECIMAL(15, 6) DEFAULT NULL,
    NET_LIQ_VALUE DECIMAL(15, 6) NOT NULL,
    LEVERAGE DOUBLE NOT NULL,
    ALLOCATION DOUBLE NOT NULL,
    CASH_FLOW DECIMAL(15, 6) DEFAULT NULL,
    STRATEGY_FK INT NOT NULL
);              
ALTER TABLE PUBLIC."portfolio_value" ADD CONSTRAINT PUBLIC.CONSTRAINT_F1 PRIMARY KEY(ID);     
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."portfolio_value";       
CREATE INDEX PUBLIC.INDEX_F1 ON PUBLIC."portfolio_value"(STRATEGY_FK);        
CREATE CACHED TABLE PUBLIC."position"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_8F026070_AF0F_47B9_AA27_824C14F1BD94) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_8F026070_AF0F_47B9_AA27_824C14F1BD94,
    QUANTITY BIGINT NOT NULL,
    COST DOUBLE NOT NULL,
    REALIZED_P_L DOUBLE NOT NULL,
    EXIT_VALUE DECIMAL(15, 6) DEFAULT NULL,
    MAINTENANCE_MARGIN DECIMAL(15, 2) DEFAULT NULL,
    PERSISTENT BIT NOT NULL,
    SECURITY_FK INT NOT NULL,
    STRATEGY_FK INT NOT NULL,
    VERSION INT DEFAULT '0' NOT NULL
);   
ALTER TABLE PUBLIC."position" ADD CONSTRAINT PUBLIC.CONSTRAINT_2C PRIMARY KEY(ID);            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."position";              
CREATE INDEX PUBLIC.INDEX_2C ON PUBLIC."position"(SECURITY_FK);               
CREATE INDEX PUBLIC.INDEX_2C9 ON PUBLIC."position"(STRATEGY_FK);              
CREATE CACHED TABLE PUBLIC."property"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_A3C2EF43_9CCE_4FFD_9914_0623DCC20160) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_A3C2EF43_9CCE_4FFD_9914_0623DCC20160,
    NAME VARCHAR(255) NOT NULL,
    PERSISTENT BIT NOT NULL,
    INT_VALUE INT DEFAULT NULL,
    DOUBLE_VALUE DOUBLE DEFAULT NULL,
    MONEY_VALUE DECIMAL(15, 6) DEFAULT NULL,
    TEXT_VALUE VARCHAR(255) DEFAULT NULL,
    DATE_TIME_VALUE DATETIME DEFAULT NULL,
    BOOLEAN_VALUE BIT DEFAULT NULL,
    PROPERTY_HOLDER_FK INT NOT NULL,
    VERSION INT NOT NULL
);   
ALTER TABLE PUBLIC."property" ADD CONSTRAINT PUBLIC.CONSTRAINT_C4 PRIMARY KEY(ID);            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."property";              
CREATE CACHED TABLE PUBLIC."security"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_5A328F84_1E5B_4206_A759_C1705B49B244) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_5A328F84_1E5B_4206_A759_C1705B49B244,
    SYMBOL VARCHAR(30) DEFAULT NULL,
    ISIN VARCHAR(20) DEFAULT NULL,
    BBGID VARCHAR(12) DEFAULT NULL,
    RIC VARCHAR(20) DEFAULT NULL,
    CONID VARCHAR(30) DEFAULT NULL,
    LMAXID VARCHAR(30) DEFAULT NULL,
    UNDERLYING_FK INT DEFAULT NULL,
    SECURITY_FAMILY_FK INT NOT NULL
);             
ALTER TABLE PUBLIC."security" ADD CONSTRAINT PUBLIC.CONSTRAINT_38 PRIMARY KEY(ID);            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."security";              
CREATE INDEX PUBLIC.INDEX_38 ON PUBLIC."security"(SECURITY_FAMILY_FK);        
CREATE INDEX PUBLIC.INDEX_389 ON PUBLIC."security"(UNDERLYING_FK);            
CREATE CACHED TABLE PUBLIC."security_family"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_BC7873ED_4968_43E9_90CD_B3332D9C904B) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_BC7873ED_4968_43E9_90CD_B3332D9C904B,
    NAME VARCHAR(20) NOT NULL,
    SYMBOL_ROOT VARCHAR(20) DEFAULT NULL,
    ISIN_ROOT VARCHAR(20) DEFAULT NULL,
    RIC_ROOT VARCHAR(20) DEFAULT NULL,
    CURRENCY VARCHAR(100) NOT NULL,
    TRADING_CLASS VARCHAR(20) DEFAULT NULL,
    CONTRACT_SIZE DOUBLE NOT NULL,
    SCALE INT NOT NULL,
    TICK_SIZE_PATTERN VARCHAR(100) NOT NULL,
    EXECUTION_COMMISSION DECIMAL(5, 2) DEFAULT NULL,
    CLEARING_COMMISSION DECIMAL(5, 2) DEFAULT NULL,
    FEE DECIMAL(5, 2) DEFAULT NULL,
    TRADEABLE BIT NOT NULL,
    SYNTHETIC BIT NOT NULL,
    PERIODICITY VARCHAR(100) DEFAULT NULL,
    MAX_GAP INT DEFAULT NULL,
    UNDERLYING_FK INT DEFAULT NULL,
    EXCHANGE_FK INT DEFAULT NULL
);        
ALTER TABLE PUBLIC."security_family" ADD CONSTRAINT PUBLIC.CONSTRAINT_58 PRIMARY KEY(ID);     
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."security_family";       
CREATE INDEX PUBLIC.INDEX_58 ON PUBLIC."security_family"(UNDERLYING_FK);      
CREATE INDEX PUBLIC.INDEX_585 ON PUBLIC."security_family"(EXCHANGE_FK);       
CREATE CACHED TABLE PUBLIC."stock"(
    ID INT NOT NULL,
    GICS CHAR(8) DEFAULT NULL
);  
ALTER TABLE PUBLIC."stock" ADD CONSTRAINT PUBLIC.CONSTRAINT_68 PRIMARY KEY(ID);               
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."stock"; 
CREATE INDEX PUBLIC.INDEX_68 ON PUBLIC."stock"(GICS);         
CREATE INDEX PUBLIC.INDEX_68A ON PUBLIC."stock"(ID);          
CREATE CACHED TABLE PUBLIC."strategy"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_4219A4F5_9A5C_413C_9B2B_B9B8CF41E986) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_4219A4F5_9A5C_413C_9B2B_B9B8CF41E986,
    NAME VARCHAR(30) NOT NULL,
    AUTO_ACTIVATE BIT NOT NULL,
    ALLOCATION DOUBLE NOT NULL,
    VERSION INT DEFAULT '0' NOT NULL
);            
ALTER TABLE PUBLIC."strategy" ADD CONSTRAINT PUBLIC.CONSTRAINT_6A PRIMARY KEY(ID);            
-- 1 +/- SELECT COUNT(*) FROM PUBLIC."strategy";              
INSERT INTO PUBLIC."strategy"(ID, NAME, AUTO_ACTIVATE, ALLOCATION, VERSION) VALUES
(1, 'SERVER', TRUE, 0.0, 0);              
CREATE CACHED TABLE PUBLIC."subscription"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_6B046A29_91ED_4A1E_8885_710294614AF0) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_6B046A29_91ED_4A1E_8885_710294614AF0,
    SECURITY_FK INT NOT NULL,
    STRATEGY_FK INT NOT NULL,
    FEED_TYPE VARCHAR(100) NOT NULL,
    PERSISTENT BIT NOT NULL,
    VERSION INT NOT NULL
);    
ALTER TABLE PUBLIC."subscription" ADD CONSTRAINT PUBLIC.CONSTRAINT_14 PRIMARY KEY(ID);        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."subscription";          
CREATE INDEX PUBLIC.INDEX_14 ON PUBLIC."subscription"(PERSISTENT);            
CREATE INDEX PUBLIC.INDEX_145 ON PUBLIC."subscription"(SECURITY_FK);          
CREATE INDEX PUBLIC.INDEX_1456 ON PUBLIC."subscription"(STRATEGY_FK);         
CREATE INDEX PUBLIC.INDEX_14565 ON PUBLIC."subscription"(FEED_TYPE);          
CREATE CACHED TABLE PUBLIC."tick"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_B5220B25_2473_4436_B56B_D19901C433B3) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_B5220B25_2473_4436_B56B_D19901C433B3,
    DATE_TIME DATETIME NOT NULL,
    LAST DECIMAL(13, 6) DEFAULT NULL,
    LAST_DATE_TIME DATETIME DEFAULT NULL,
    VOL INT NOT NULL,
    VOL_BID INT NOT NULL,
    VOL_ASK INT NOT NULL,
    BID DECIMAL(13, 6) DEFAULT NULL,
    ASK DECIMAL(13, 6) DEFAULT NULL,
    FEED_TYPE VARCHAR(100) NOT NULL,
    SECURITY_FK INT NOT NULL
);       
ALTER TABLE PUBLIC."tick" ADD CONSTRAINT PUBLIC.CONSTRAINT_36 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."tick";  
CREATE INDEX PUBLIC.INDEX_36 ON PUBLIC."tick"(DATE_TIME);     
CREATE INDEX PUBLIC.INDEX_365 ON PUBLIC."tick"(SECURITY_FK);  
CREATE INDEX PUBLIC.INDEX_3651 ON PUBLIC."tick"(FEED_TYPE);   
CREATE CACHED TABLE PUBLIC."trading_hours"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_AE53FD4C_530A_4790_8B58_79F7796BB7EB) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_AE53FD4C_530A_4790_8B58_79F7796BB7EB,
    OPEN TIME NOT NULL,
    CLOSE TIME NOT NULL,
    SUNDAY BIT NOT NULL,
    MONDAY BIT NOT NULL,
    TUESDAY BIT NOT NULL,
    WEDNESDAY BIT NOT NULL,
    THURSDAY BIT NOT NULL,
    FRIDAY BIT NOT NULL,
    SATURDAY BIT NOT NULL,
    EXCHANGE_FK INT NOT NULL
);
ALTER TABLE PUBLIC."trading_hours" ADD CONSTRAINT PUBLIC.CONSTRAINT_BB PRIMARY KEY(ID);       
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."trading_hours";         
CREATE INDEX PUBLIC.INDEX_BB ON PUBLIC."trading_hours"(EXCHANGE_FK);          
CREATE CACHED TABLE PUBLIC."transaction"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_C47559EE_67A7_489D_8A20_1C67DCF4595B) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_C47559EE_67A7_489D_8A20_1C67DCF4595B,
    EXT_ID VARCHAR(30) DEFAULT NULL,
    INT_ORDER_ID VARCHAR(30) DEFAULT NULL,
    EXT_ORDER_ID VARCHAR(30) DEFAULT NULL,
    DATE_TIME DATETIME NOT NULL,
    SETTLEMENT_DATE DATE DEFAULT NULL,
    QUANTITY BIGINT NOT NULL,
    PRICE DECIMAL(15, 6) NOT NULL,
    EXECUTION_COMMISSION DECIMAL(15, 2) DEFAULT NULL,
    CLEARING_COMMISSION DECIMAL(15, 2) DEFAULT NULL,
    FEE DECIMAL(15, 2) DEFAULT NULL,
    CURRENCY VARCHAR(100) NOT NULL,
    TYPE VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(255) DEFAULT NULL,
    SECURITY_FK INT DEFAULT NULL,
    STRATEGY_FK INT NOT NULL,
    POSITION_FK INT DEFAULT NULL,
    ACCOUNT_FK INT DEFAULT NULL
);           
ALTER TABLE PUBLIC."transaction" ADD CONSTRAINT PUBLIC.CONSTRAINT_7F PRIMARY KEY(ID);         
-- 1 +/- SELECT COUNT(*) FROM PUBLIC."transaction";           
INSERT INTO PUBLIC."transaction"(ID, EXT_ID, INT_ORDER_ID, EXT_ORDER_ID, DATE_TIME, SETTLEMENT_DATE, QUANTITY, PRICE, EXECUTION_COMMISSION, CLEARING_COMMISSION, FEE, CURRENCY, TYPE, DESCRIPTION, SECURITY_FK, STRATEGY_FK, POSITION_FK, ACCOUNT_FK) VALUES
(1, NULL, NULL, NULL, TIMESTAMP '2012-08-16 00:00:00.0', NULL, 1, 1000000.000000, NULL, NULL, NULL, 'USD', 'CREDIT', NULL, NULL, 1, NULL, NULL);
CREATE INDEX PUBLIC.INDEX_7F ON PUBLIC."transaction"(DATE_TIME);              
CREATE INDEX PUBLIC.INDEX_7FA ON PUBLIC."transaction"(SETTLEMENT_DATE);       
CREATE INDEX PUBLIC.INDEX_7FA0 ON PUBLIC."transaction"(CURRENCY);             
CREATE INDEX PUBLIC.INDEX_7FA0D ON PUBLIC."transaction"(STRATEGY_FK);         
CREATE INDEX PUBLIC.INDEX_7FA0D2 ON PUBLIC."transaction"(POSITION_FK);        
CREATE INDEX PUBLIC.INDEX_7FA0D2D ON PUBLIC."transaction"(SECURITY_FK);       
CREATE INDEX PUBLIC.INDEX_7FA0D2DE_0 ON PUBLIC."transaction"(ACCOUNT_FK);     
ALTER TABLE PUBLIC."allocation" ADD CONSTRAINT PUBLIC.CONSTRAINT_8E UNIQUE(ORDER_PREFERENCE_FK, ACCOUNT_FK);  
ALTER TABLE PUBLIC."strategy" ADD CONSTRAINT PUBLIC.CONSTRAINT_6A8 UNIQUE(NAME);              
ALTER TABLE PUBLIC."order_preference" ADD CONSTRAINT PUBLIC.CONSTRAINT_7D3 UNIQUE(NAME);      
ALTER TABLE PUBLIC."security" ADD CONSTRAINT PUBLIC.CONSTRAINT_389277 UNIQUE(RIC);            
ALTER TABLE PUBLIC."position" ADD CONSTRAINT PUBLIC.CONSTRAINT_2C9 UNIQUE(SECURITY_FK, STRATEGY_FK);          
ALTER TABLE PUBLIC."cash_balance" ADD CONSTRAINT PUBLIC.CONSTRAINT_D5 UNIQUE(CURRENCY, STRATEGY_FK);          
ALTER TABLE PUBLIC."broker_parameters" ADD CONSTRAINT PUBLIC.CONSTRAINT_94 UNIQUE(BROKER, SECURITY_FAMILY_FK);
ALTER TABLE PUBLIC."exchange" ADD CONSTRAINT PUBLIC.CONSTRAINT_76 UNIQUE(NAME);               
ALTER TABLE PUBLIC."security_family" ADD CONSTRAINT PUBLIC.CONSTRAINT_585 UNIQUE(NAME);       
ALTER TABLE PUBLIC."security" ADD CONSTRAINT PUBLIC.CONSTRAINT_389 UNIQUE(SYMBOL, SECURITY_FAMILY_FK);        
ALTER TABLE PUBLIC."property" ADD CONSTRAINT PUBLIC.CONSTRAINT_C4C UNIQUE(NAME, PROPERTY_HOLDER_FK);          
ALTER TABLE PUBLIC."security" ADD CONSTRAINT PUBLIC.CONSTRAINT_38927 UNIQUE(BBGID);           
ALTER TABLE PUBLIC."transaction" ADD CONSTRAINT PUBLIC.CONSTRAINT_7FA UNIQUE(EXT_ID);         
ALTER TABLE PUBLIC."security" ADD CONSTRAINT PUBLIC.CONSTRAINT_3892 UNIQUE(ISIN);             
ALTER TABLE PUBLIC."easy_to_borrow" ADD CONSTRAINT PUBLIC.CONSTRAINT_80E UNIQUE(DATE, BROKER, STOCK_FK);      
ALTER TABLE PUBLIC."portfolio_value" ADD CONSTRAINT PUBLIC.CONSTRAINT_F1C UNIQUE(DATE_TIME, STRATEGY_FK);     
ALTER TABLE PUBLIC."subscription" ADD CONSTRAINT PUBLIC.CONSTRAINT_145 UNIQUE(SECURITY_FK, STRATEGY_FK, FEED_TYPE);           
ALTER TABLE PUBLIC."component" ADD CONSTRAINT PUBLIC.CONSTRAINT_AC8 UNIQUE(SECURITY_FK, COMBINATION_FK);      
ALTER TABLE PUBLIC."security" ADD CONSTRAINT PUBLIC.CONSTRAINT_3892774 UNIQUE(CONID);         
ALTER TABLE PUBLIC."bar" ADD CONSTRAINT PUBLIC.CONSTRAINT_17 UNIQUE(DATE_TIME, SECURITY_FK, BAR_SIZE);        
ALTER TABLE PUBLIC."account" ADD CONSTRAINT PUBLIC.CONSTRAINT_B9 UNIQUE(NAME);
ALTER TABLE PUBLIC."tick" ADD CONSTRAINT PUBLIC.CONSTRAINT_365 UNIQUE(DATE_TIME, SECURITY_FK, FEED_TYPE);     
ALTER TABLE PUBLIC."measurement" ADD CONSTRAINT PUBLIC.CONSTRAINT_93F UNIQUE(DATE_TIME, NAME, STRATEGY_FK);   
ALTER TABLE PUBLIC."transaction" ADD CONSTRAINT PUBLIC.TRANSACTION_STRATEGY_FKC FOREIGN KEY(STRATEGY_FK) REFERENCES PUBLIC."strategy"(ID) ON UPDATE CASCADE NOCHECK;          
ALTER TABLE PUBLIC."order_preference" ADD CONSTRAINT PUBLIC.ORDER_PREFERENCE_DEFAULT_ACCOC FOREIGN KEY(DEFAULT_ACCOUNT_FK) REFERENCES PUBLIC."account"(ID) ON UPDATE CASCADE NOCHECK;         
ALTER TABLE PUBLIC."allocation" ADD CONSTRAINT PUBLIC.ALLOCATION_ACCOUNT_FKC FOREIGN KEY(ACCOUNT_FK) REFERENCES PUBLIC."account"(ID) NOCHECK; 
ALTER TABLE PUBLIC."stock" ADD CONSTRAINT PUBLIC.STOCKIFKC FOREIGN KEY(ID) REFERENCES PUBLIC."security"(ID) ON DELETE CASCADE ON UPDATE CASCADE NOCHECK;      
ALTER TABLE PUBLIC."order_property" ADD CONSTRAINT PUBLIC.ORDER_PROPERTY_ORDER_FKC FOREIGN KEY(ORDER_FK) REFERENCES PUBLIC."order"(ID) NOCHECK;               
ALTER TABLE PUBLIC."trading_hours" ADD CONSTRAINT PUBLIC.TRADING_HOURS_EXCHANGE_FKC FOREIGN KEY(EXCHANGE_FK) REFERENCES PUBLIC."exchange"(ID) ON DELETE CASCADE ON UPDATE CASCADE NOCHECK;    
ALTER TABLE PUBLIC."order_status" ADD CONSTRAINT PUBLIC.ORDER_STATUS_ORDER_FKC FOREIGN KEY(ORDER_FK) REFERENCES PUBLIC."order"(ID) ON DELETE CASCADE ON UPDATE CASCADE NOCHECK;               
ALTER TABLE PUBLIC."transaction" ADD CONSTRAINT PUBLIC.TRANSACTION_POSITION_FKC FOREIGN KEY(POSITION_FK) REFERENCES PUBLIC."position"(ID) ON UPDATE CASCADE NOCHECK;          
ALTER TABLE PUBLIC."transaction" ADD CONSTRAINT PUBLIC.TRANSACTION_SECURITY_FKC FOREIGN KEY(SECURITY_FK) REFERENCES PUBLIC."security"(ID) ON UPDATE CASCADE NOCHECK;          
ALTER TABLE PUBLIC."component" ADD CONSTRAINT PUBLIC.COMPONENT_COMBINATION_FK FOREIGN KEY(COMBINATION_FK) REFERENCES PUBLIC."combination"(ID) ON DELETE CASCADE ON UPDATE CASCADE NOCHECK;    
ALTER TABLE PUBLIC."order" ADD CONSTRAINT PUBLIC.ORDER_ACCOUNT_FKC FOREIGN KEY(ACCOUNT_FK) REFERENCES PUBLIC."account"(ID) NOCHECK;           
ALTER TABLE PUBLIC."security" ADD CONSTRAINT PUBLIC.SECURITY_UNDERLYING_FKC FOREIGN KEY(UNDERLYING_FK) REFERENCES PUBLIC."security"(ID) ON UPDATE CASCADE NOCHECK;            
ALTER TABLE PUBLIC."security_family" ADD CONSTRAINT PUBLIC.SECURITY_FAMILY_UNDERLAYING_FKC FOREIGN KEY(UNDERLYING_FK) REFERENCES PUBLIC."security"(ID) ON DELETE CASCADE ON UPDATE CASCADE NOCHECK;           
ALTER TABLE PUBLIC."subscription" ADD CONSTRAINT PUBLIC.SUBSCRIPTION_STRATEGY_FKC FOREIGN KEY(STRATEGY_FK) REFERENCES PUBLIC."strategy"(ID) ON UPDATE CASCADE NOCHECK;        
ALTER TABLE PUBLIC."subscription" ADD CONSTRAINT PUBLIC.SUBSCRIPTION_SECURITY_FKC FOREIGN KEY(SECURITY_FK) REFERENCES PUBLIC."security"(ID) ON UPDATE CASCADE NOCHECK;        
ALTER TABLE PUBLIC."holiday" ADD CONSTRAINT PUBLIC.HOLIDAY_MARKET_FKC FOREIGN KEY(EXCHANGE_FK) REFERENCES PUBLIC."exchange"(ID) ON DELETE CASCADE ON UPDATE CASCADE NOCHECK;  
ALTER TABLE PUBLIC."transaction" ADD CONSTRAINT PUBLIC.TRANSACTION_ACCOUNT_FKC FOREIGN KEY(ACCOUNT_FK) REFERENCES PUBLIC."account"(ID) ON UPDATE CASCADE NOCHECK;             
ALTER TABLE PUBLIC."security_family" ADD CONSTRAINT PUBLIC.SECURITY_FAMILY_MARKET_FKC FOREIGN KEY(EXCHANGE_FK) REFERENCES PUBLIC."exchange"(ID) NOCHECK;      
