;             
CREATE USER IF NOT EXISTS SA SALT 'a7eef7be8f7d03ed' HASH '2c3fb8f814298c3a0746706f36cdcde63b927ab8364645735dc3f467bee8f712' ADMIN;           
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_CFCFAA6F_1164_4ED1_85BB_E162A7C95BA5 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_380E93AC_094B_4BD5_B1EA_BA64038A4FD8 START WITH 2 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_F6102437_4740_4714_97B0_C7D3747E562B START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_77346152_7BD4_4181_9694_C2D86A62629E START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_CD645776_757E_4323_9F48_E8E98BD5A5F2 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_8D9A2413_23A9_4832_B5E1_1F7382AAFD1B START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_415C653A_246A_4F09_BB7A_1BBD298E6ADA START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_1B9988FB_CE39_4B8E_B924_F7AFBFA3A376 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_6672FD5D_798E_486D_84D3_6E8C6D82CCF6 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_1889A79B_8778_4634_8CF0_496123F290FE START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_6A8299C1_E176_4FB1_BAA5_7869C772E532 START WITH 2 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_255C8CFC_BDB3_4DA0_B6A8_90C5135AFE92 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_8259C729_ACE2_446C_981D_B620DD8C876D START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_17A183AA_663B_4184_8C4E_AB35AEC58CB9 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_4AA182DE_7BCB_4951_9A5C_BE1FBAEE657A START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_EB5D5646_6DA4_4D78_AF22_A3703842C59C START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_201D29F4_7115_4284_B1E6_4EF97DAADF04 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_1D492A91_39E1_450A_BACD_D7221EBA4760 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_8E7A7B0E_2E19_4C1E_8B32_A8D413F7ADF7 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_A8ED2AC8_4D0C_4491_A140_88D6094386DE START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_43DFA47F_EB5D_49EF_AB62_037EF0C0AE97 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_4FD503FB_6ECE_4F22_9BB4_1C676CCDE446 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_AACE7745_914D_48CF_BC48_60259735CE96 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_9B44E597_EFF5_479A_8D9F_EE0E66ECC12C START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_C3667629_79C2_46F4_9C3B_CA0B6772261E START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_CF35583D_1B67_4703_BBFA_F5CA017CA657 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_0AB361D2_E5A2_496C_BCCB_E9BD674F4318 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_B212DD4D_E1CD_4F2A_B562_7E2102C4B0A9 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_3041C3C7_E090_414C_B7CF_4DA9AB5A6AE3 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_CF616A5D_71C6_4AD9_BED5_B60941D94985 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_E98E3274_9FC6_482A_9D0E_CE6D49B973FE START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_C3D1CA75_BA38_4CA3_A86B_BCB46A7944CE START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_F18A4283_F551_4BDB_9772_359EEBB02698 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_4F6250B8_F34C_4610_8B1E_2ACA6291D30B START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_3FEC6318_AA8F_44F5_A44A_AB1C1B415102 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_E6AA51CD_F6F7_464A_B238_0F0DF1E721B8 START WITH 2 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_16C56745_7C69_4847_BA85_A4D31243B9EF START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_B81E372A_E40A_4A1C_8A64_30CA0F967682 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_ABA79D99_A06C_4F16_891E_0EEAC20551CA START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_B670A87A_7D7D_4D85_9495_4E66459CC16F START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_92BEFE57_70F4_4A51_963D_797D52CF4131 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_01CE5304_697E_4168_9959_7791B4A68337 START WITH 1 BELONGS_TO_TABLE;    
CREATE CACHED TABLE PUBLIC."account"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_255C8CFC_BDB3_4DA0_B6A8_90C5135AFE92) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_255C8CFC_BDB3_4DA0_B6A8_90C5135AFE92,
    NAME VARCHAR(20) NOT NULL,
    ACTIVE BIT NOT NULL,
    BROKER VARCHAR(100) NOT NULL,
    ORDER_SERVICE_TYPE VARCHAR(100) NOT NULL,
    SESSION_QUALIFIER VARCHAR(10) DEFAULT NULL,
    EXT_ACCOUNT VARCHAR(20) DEFAULT NULL,
    EXT_ACCOUNT_GROUP VARCHAR(20) DEFAULT NULL,
    EXT_ALLOCATION_PROFILE VARCHAR(20) DEFAULT NULL,
    EXT_CLEARING_ACCOUNT VARCHAR(20) DEFAULT NULL
);
ALTER TABLE PUBLIC."account" ADD CONSTRAINT PUBLIC.CONSTRAINT_B PRIMARY KEY(ID);              
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."account";               
CREATE INDEX PUBLIC.INDEX_B ON PUBLIC."account"(ACTIVE);      
CREATE INDEX PUBLIC.INDEX_B9 ON PUBLIC."account"(BROKER);     
CREATE INDEX PUBLIC.INDEX_B9D ON PUBLIC."account"(ORDER_SERVICE_TYPE);        
CREATE CACHED TABLE PUBLIC."allocation"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_CF616A5D_71C6_4AD9_BED5_B60941D94985) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_CF616A5D_71C6_4AD9_BED5_B60941D94985,
    VALUE DOUBLE NOT NULL,
    ORDER_PREFERENCE_FK BIGINT NOT NULL,
    ACCOUNT_FK BIGINT NOT NULL
);         
ALTER TABLE PUBLIC."allocation" ADD CONSTRAINT PUBLIC.CONSTRAINT_8 PRIMARY KEY(ID);           
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."allocation";            
CREATE INDEX PUBLIC.INDEX_8 ON PUBLIC."allocation"(ACCOUNT_FK);               
CREATE INDEX PUBLIC.INDEX_8E ON PUBLIC."allocation"(ORDER_PREFERENCE_FK);     
CREATE CACHED TABLE PUBLIC."bar"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_EB5D5646_6DA4_4D78_AF22_A3703842C59C) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_EB5D5646_6DA4_4D78_AF22_A3703842C59C,
    DATE_TIME DATETIME NOT NULL,
    OPEN DECIMAL(13, 6) NOT NULL,
    HIGH DECIMAL(13, 6) NOT NULL,
    LOW DECIMAL(13, 6) NOT NULL,
    CLOSE DECIMAL(13, 6) NOT NULL,
    VOL INT NOT NULL,
    BAR_SIZE VARCHAR(100) NOT NULL,
    FEED_TYPE VARCHAR(100) NOT NULL,
    SECURITY_FK INT NOT NULL
);        
ALTER TABLE PUBLIC."bar" ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID);  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."bar";   
CREATE INDEX PUBLIC.INDEX_1 ON PUBLIC."bar"(DATE_TIME);       
CREATE INDEX PUBLIC.INDEX_17 ON PUBLIC."bar"(SECURITY_FK);    
CREATE INDEX PUBLIC.INDEX_17C ON PUBLIC."bar"(BAR_SIZE);      
CREATE CACHED TABLE PUBLIC."bond"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_CF35583D_1B67_4703_BBFA_F5CA017CA657) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_CF35583D_1B67_4703_BBFA_F5CA017CA657,
    MATURITY DATE NOT NULL,
    COUPON DOUBLE NOT NULL
);            
ALTER TABLE PUBLIC."bond" ADD CONSTRAINT PUBLIC.CONSTRAINT_2 PRIMARY KEY(ID); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."bond";  
CREATE INDEX PUBLIC.INDEX_2 ON PUBLIC."bond"(MATURITY);       
CREATE INDEX PUBLIC.INDEX_2E ON PUBLIC."bond"(ID);            
CREATE CACHED TABLE PUBLIC."bond_family"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_CFCFAA6F_1164_4ED1_85BB_E162A7C95BA5) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_CFCFAA6F_1164_4ED1_85BB_E162A7C95BA5,
    MATURITY_DISTANCE VARCHAR(100) NOT NULL,
    LENGTH INT NOT NULL,
    QUOTATION_STYLE VARCHAR(100) NOT NULL
);           
ALTER TABLE PUBLIC."bond_family" ADD CONSTRAINT PUBLIC.CONSTRAINT_89 PRIMARY KEY(ID);         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."bond_family";           
CREATE INDEX PUBLIC.INDEX_89 ON PUBLIC."bond_family"(ID);     
CREATE CACHED TABLE PUBLIC."broker_parameters"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_77346152_7BD4_4181_9694_C2D86A62629E) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_77346152_7BD4_4181_9694_C2D86A62629E,
    BROKER VARCHAR(100) NOT NULL,
    SYMBOL_ROOT VARCHAR(20) DEFAULT NULL,
    CONTRACT_SIZE DOUBLE DEFAULT NULL,
    SCALE INT DEFAULT NULL,
    TICK_SIZE_PATTERN VARCHAR(100) DEFAULT NULL,
    EXECUTION_COMMISSION DECIMAL(5, 2) DEFAULT NULL,
    CLEARING_COMMISSION DECIMAL(5, 2) DEFAULT NULL,
    FEE DECIMAL(5, 2) DEFAULT NULL,
    EXCHANGE_CODE VARCHAR(10) DEFAULT NULL,
    PRICE_MULTIPLIER DOUBLE DEFAULT NULL,
    SECURITY_FAMILY_FK BIGINT NOT NULL
);   
ALTER TABLE PUBLIC."broker_parameters" ADD CONSTRAINT PUBLIC.CONSTRAINT_9 PRIMARY KEY(ID);    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."broker_parameters";     
CREATE INDEX PUBLIC.INDEX_9 ON PUBLIC."broker_parameters"(SECURITY_FAMILY_FK);
CREATE CACHED TABLE PUBLIC."cash_balance"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_E6AA51CD_F6F7_464A_B238_0F0DF1E721B8) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_E6AA51CD_F6F7_464A_B238_0F0DF1E721B8,
    CURRENCY VARCHAR(100) NOT NULL,
    AMOUNT DECIMAL(15, 2) NOT NULL,
    STRATEGY_FK BIGINT NOT NULL,
    VERSION INT NOT NULL
);       
ALTER TABLE PUBLIC."cash_balance" ADD CONSTRAINT PUBLIC.CONSTRAINT_D PRIMARY KEY(ID);         
-- 1 +/- SELECT COUNT(*) FROM PUBLIC."cash_balance";          
INSERT INTO PUBLIC."cash_balance"(ID, CURRENCY, AMOUNT, STRATEGY_FK, VERSION) VALUES
(1, 'USD', 1000000.00, 1, 1);           
CREATE INDEX PUBLIC.INDEX_D ON PUBLIC."cash_balance"(STRATEGY_FK);            
CREATE CACHED TABLE PUBLIC."combination"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_01CE5304_697E_4168_9959_7791B4A68337) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_01CE5304_697E_4168_9959_7791B4A68337,
    UUID CHAR(36) NOT NULL,
    TYPE VARCHAR(100) NOT NULL,
    PERSISTENT BIT NOT NULL
);   
ALTER TABLE PUBLIC."combination" ADD CONSTRAINT PUBLIC.CONSTRAINT_D9 PRIMARY KEY(ID);         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."combination";           
CREATE INDEX PUBLIC.INDEX_D9 ON PUBLIC."combination"(ID);     
CREATE CACHED TABLE PUBLIC."commodity"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_B212DD4D_E1CD_4F2A_B562_7E2102C4B0A9) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_B212DD4D_E1CD_4F2A_B562_7E2102C4B0A9,
    TYPE VARCHAR(100) NOT NULL
);
ALTER TABLE PUBLIC."commodity" ADD CONSTRAINT PUBLIC.CONSTRAINT_A PRIMARY KEY(ID);            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."commodity";             
CREATE INDEX PUBLIC.INDEX_A ON PUBLIC."commodity"(ID);        
CREATE CACHED TABLE PUBLIC."component"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_B670A87A_7D7D_4D85_9495_4E66459CC16F) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_B670A87A_7D7D_4D85_9495_4E66459CC16F,
    QUANTITY BIGINT NOT NULL,
    PERSISTENT BIT NOT NULL,
    SECURITY_FK BIGINT NOT NULL,
    COMBINATION_FK BIGINT NOT NULL,
    VERSION INT NOT NULL
);  
ALTER TABLE PUBLIC."component" ADD CONSTRAINT PUBLIC.CONSTRAINT_AC PRIMARY KEY(ID);           
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."component";             
CREATE INDEX PUBLIC.INDEX_AC ON PUBLIC."component"(COMBINATION_FK);           
CREATE INDEX PUBLIC.INDEX_AC8 ON PUBLIC."component"(SECURITY_FK);             
CREATE CACHED TABLE PUBLIC."easy_to_borrow"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_E98E3274_9FC6_482A_9D0E_CE6D49B973FE) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_E98E3274_9FC6_482A_9D0E_CE6D49B973FE,
    DATE DATE NOT NULL,
    BROKER VARCHAR(100) NOT NULL,
    QUANTITY BIGINT NOT NULL,
    STOCK_FK BIGINT NOT NULL
);  
ALTER TABLE PUBLIC."easy_to_borrow" ADD CONSTRAINT PUBLIC.CONSTRAINT_80 PRIMARY KEY(ID);      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."easy_to_borrow";        
CREATE INDEX PUBLIC.INDEX_80 ON PUBLIC."easy_to_borrow"(STOCK_FK);            
CREATE CACHED TABLE PUBLIC."exchange"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_92BEFE57_70F4_4A51_963D_797D52CF4131) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_92BEFE57_70F4_4A51_963D_797D52CF4131,
    NAME VARCHAR(50) NOT NULL,
    CODE VARCHAR(10) NOT NULL,
    TIME_ZONE VARCHAR(50) NOT NULL
);             
ALTER TABLE PUBLIC."exchange" ADD CONSTRAINT PUBLIC.CONSTRAINT_7 PRIMARY KEY(ID);             
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."exchange";              
CREATE CACHED TABLE PUBLIC."forex"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_8E7A7B0E_2E19_4C1E_8B32_A8D413F7ADF7) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_8E7A7B0E_2E19_4C1E_8B32_A8D413F7ADF7,
    BASE_CURRENCY VARCHAR(100) NOT NULL
);           
ALTER TABLE PUBLIC."forex" ADD CONSTRAINT PUBLIC.CONSTRAINT_5 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."forex"; 
CREATE INDEX PUBLIC.INDEX_5 ON PUBLIC."forex"(ID);            
CREATE CACHED TABLE PUBLIC."fund"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_3FEC6318_AA8F_44F5_A44A_AB1C1B415102) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_3FEC6318_AA8F_44F5_A44A_AB1C1B415102
);      
ALTER TABLE PUBLIC."fund" ADD CONSTRAINT PUBLIC.CONSTRAINT_3 PRIMARY KEY(ID); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."fund";  
CREATE INDEX PUBLIC.INDEX_3 ON PUBLIC."fund"(ID);             
CREATE CACHED TABLE PUBLIC."future"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_16C56745_7C69_4847_BA85_A4D31243B9EF) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_16C56745_7C69_4847_BA85_A4D31243B9EF,
    EXPIRATION DATE NOT NULL,
    FIRST_NOTICE DATE DEFAULT NULL,
    LAST_TRADING DATE DEFAULT NULL
);           
ALTER TABLE PUBLIC."future" ADD CONSTRAINT PUBLIC.CONSTRAINT_B4 PRIMARY KEY(ID);              
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."future";
CREATE INDEX PUBLIC.INDEX_B4 ON PUBLIC."future"(EXPIRATION);  
CREATE INDEX PUBLIC.INDEX_B4B ON PUBLIC."future"(FIRST_NOTICE);               
CREATE INDEX PUBLIC.INDEX_B4B5 ON PUBLIC."future"(LAST_TRADING);              
CREATE INDEX PUBLIC.INDEX_B4B58 ON PUBLIC."future"(ID);       
CREATE CACHED TABLE PUBLIC."future_family"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_ABA79D99_A06C_4F16_891E_0EEAC20551CA) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_ABA79D99_A06C_4F16_891E_0EEAC20551CA,
    INTREST DOUBLE NOT NULL,
    DIVIDEND DOUBLE NOT NULL,
    MARGIN_PARAMETER DOUBLE NOT NULL,
    EXPIRATION_TYPE VARCHAR(100) NOT NULL,
    EXPIRATION_DISTANCE VARCHAR(100) NOT NULL,
    LENGTH INT NOT NULL
);   
ALTER TABLE PUBLIC."future_family" ADD CONSTRAINT PUBLIC.CONSTRAINT_E PRIMARY KEY(ID);        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."future_family";         
CREATE INDEX PUBLIC.INDEX_E ON PUBLIC."future_family"(ID);    
CREATE CACHED TABLE PUBLIC."generic_future"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_3041C3C7_E090_414C_B7CF_4DA9AB5A6AE3) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_3041C3C7_E090_414C_B7CF_4DA9AB5A6AE3,
    DURATION VARCHAR(100) NOT NULL,
    ASSET_CLASS VARCHAR(100) NOT NULL
);               
ALTER TABLE PUBLIC."generic_future" ADD CONSTRAINT PUBLIC.CONSTRAINT_21 PRIMARY KEY(ID);      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."generic_future";        
CREATE INDEX PUBLIC.INDEX_21 ON PUBLIC."generic_future"(DURATION);            
CREATE INDEX PUBLIC.INDEX_217 ON PUBLIC."generic_future"(ID); 
CREATE CACHED TABLE PUBLIC."generic_future_family"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_F18A4283_F551_4BDB_9772_359EEBB02698) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_F18A4283_F551_4BDB_9772_359EEBB02698,
    EXPIRATION_TYPE VARCHAR(100) NOT NULL,
    EXPIRATION_DISTANCE VARCHAR(100) NOT NULL
);         
ALTER TABLE PUBLIC."generic_future_family" ADD CONSTRAINT PUBLIC.CONSTRAINT_6 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."generic_future_family"; 
CREATE INDEX PUBLIC.INDEX_6 ON PUBLIC."generic_future_family"(ID);            
CREATE CACHED TABLE PUBLIC."generic_tick"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_1D492A91_39E1_450A_BACD_D7221EBA4760) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_1D492A91_39E1_450A_BACD_D7221EBA4760,
    DATE_TIME DATETIME NOT NULL,
    FEED_TYPE VARCHAR(100) NOT NULL,
    SECURITY_FK BIGINT NOT NULL,
    TICK_TYPE VARCHAR(100) NOT NULL,
    MONEY_VALUE DECIMAL(13, 6) DEFAULT NULL,
    DOUBLE_VALUE DOUBLE DEFAULT NULL,
    INT_VALUE INT DEFAULT NULL
);        
ALTER TABLE PUBLIC."generic_tick" ADD CONSTRAINT PUBLIC.CONSTRAINT_F PRIMARY KEY(ID);         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."generic_tick";          
CREATE INDEX PUBLIC.INDEX_F ON PUBLIC."generic_tick"(SECURITY_FK);            
CREATE CACHED TABLE PUBLIC."holiday"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_AACE7745_914D_48CF_BC48_60259735CE96) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_AACE7745_914D_48CF_BC48_60259735CE96,
    DATE DATE NOT NULL,
    LATE_OPEN TIME DEFAULT NULL,
    EARLY_CLOSE TIME DEFAULT NULL,
    EXCHANGE_FK BIGINT NOT NULL
);  
ALTER TABLE PUBLIC."holiday" ADD CONSTRAINT PUBLIC.CONSTRAINT_4 PRIMARY KEY(ID);              
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."holiday";               
CREATE INDEX PUBLIC.INDEX_4 ON PUBLIC."holiday"(EXCHANGE_FK); 
CREATE CACHED TABLE PUBLIC."implied_volatility"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_0AB361D2_E5A2_496C_BCCB_E9BD674F4318) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_0AB361D2_E5A2_496C_BCCB_E9BD674F4318,
    DURATION VARCHAR(100) NOT NULL,
    MONEYNESS DOUBLE DEFAULT NULL,
    DELTA DOUBLE DEFAULT NULL,
    TYPE VARCHAR(100) NOT NULL
);              
ALTER TABLE PUBLIC."implied_volatility" ADD CONSTRAINT PUBLIC.CONSTRAINT_1E PRIMARY KEY(ID);  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."implied_volatility";    
CREATE INDEX PUBLIC.INDEX_1E ON PUBLIC."implied_volatility"(ID);              
CREATE CACHED TABLE PUBLIC."index"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_4FD503FB_6ECE_4F22_9BB4_1C676CCDE446) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_4FD503FB_6ECE_4F22_9BB4_1C676CCDE446,
    ASSET_CLASS VARCHAR(100) NOT NULL
);             
ALTER TABLE PUBLIC."index" ADD CONSTRAINT PUBLIC.CONSTRAINT_5F PRIMARY KEY(ID);               
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."index"; 
CREATE INDEX PUBLIC.INDEX_5F ON PUBLIC."index"(ID);           
CREATE CACHED TABLE PUBLIC."intrest_rate"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_CD645776_757E_4323_9F48_E8E98BD5A5F2) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_CD645776_757E_4323_9F48_E8E98BD5A5F2,
    DURATION VARCHAR(100) NOT NULL
);         
ALTER TABLE PUBLIC."intrest_rate" ADD CONSTRAINT PUBLIC.CONSTRAINT_64 PRIMARY KEY(ID);        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."intrest_rate";          
CREATE INDEX PUBLIC.INDEX_64 ON PUBLIC."intrest_rate"(ID);    
CREATE CACHED TABLE PUBLIC."measurement"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_415C653A_246A_4F09_BB7A_1BBD298E6ADA) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_415C653A_246A_4F09_BB7A_1BBD298E6ADA,
    NAME VARCHAR(255) NOT NULL,
    DATE_TIME DATETIME NOT NULL,
    INT_VALUE INT DEFAULT NULL,
    DOUBLE_VALUE DOUBLE DEFAULT NULL,
    MONEY_VALUE DECIMAL(15, 6) DEFAULT NULL,
    TEXT_VALUE VARCHAR(50) DEFAULT NULL,
    BOOLEAN_VALUE BIT DEFAULT NULL,
    STRATEGY_FK BIGINT NOT NULL
);     
ALTER TABLE PUBLIC."measurement" ADD CONSTRAINT PUBLIC.CONSTRAINT_93 PRIMARY KEY(ID);         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."measurement";           
CREATE INDEX PUBLIC.INDEX_93 ON PUBLIC."measurement"(STRATEGY_FK);            
CREATE CACHED TABLE PUBLIC."option"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_6672FD5D_798E_486D_84D3_6E8C6D82CCF6) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_6672FD5D_798E_486D_84D3_6E8C6D82CCF6,
    STRIKE DECIMAL(12, 5) NOT NULL,
    EXPIRATION DATE NOT NULL,
    TYPE VARCHAR(100) NOT NULL
);               
ALTER TABLE PUBLIC."option" ADD CONSTRAINT PUBLIC.CONSTRAINT_C PRIMARY KEY(ID);               
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."option";
CREATE INDEX PUBLIC.INDEX_C ON PUBLIC."option"(EXPIRATION);   
CREATE INDEX PUBLIC.INDEX_C3 ON PUBLIC."option"(STRIKE);      
CREATE INDEX PUBLIC.INDEX_C3C ON PUBLIC."option"(TYPE);       
CREATE INDEX PUBLIC.INDEX_C3CA ON PUBLIC."option"(ID);        
CREATE CACHED TABLE PUBLIC."option_family"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_201D29F4_7115_4284_B1E6_4EF97DAADF04) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_201D29F4_7115_4284_B1E6_4EF97DAADF04,
    INTREST DOUBLE NOT NULL,
    DIVIDEND DOUBLE NOT NULL,
    MARGIN_PARAMETER DOUBLE NOT NULL,
    EXPIRATION_TYPE VARCHAR(100) NOT NULL,
    EXPIRATION_DISTANCE VARCHAR(100) NOT NULL,
    STRIKE_DISTANCE DOUBLE NOT NULL,
    WEEKLY BIT NOT NULL
);             
ALTER TABLE PUBLIC."option_family" ADD CONSTRAINT PUBLIC.CONSTRAINT_B3 PRIMARY KEY(ID);       
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."option_family";         
CREATE INDEX PUBLIC.INDEX_B3 ON PUBLIC."option_family"(ID);   
CREATE CACHED TABLE PUBLIC."order"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_B81E372A_E40A_4A1C_8A64_30CA0F967682) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_B81E372A_E40A_4A1C_8A64_30CA0F967682,
    CLASS VARCHAR(255) NOT NULL,
    INT_ID VARCHAR(30) NOT NULL,
    EXT_ID VARCHAR(50) DEFAULT NULL,
    DATE_TIME DATETIME NOT NULL,
    SIDE VARCHAR(100) NOT NULL,
    QUANTITY BIGINT NOT NULL,
    TIF VARCHAR(100) NOT NULL,
    TIF_DATE_TIME DATETIME DEFAULT NULL,
    "LIMIT" DECIMAL(15, 6) DEFAULT NULL,
    STOP DECIMAL(15, 6) DEFAULT NULL,
    ACCOUNT_FK BIGINT NOT NULL,
    SECURITY_FK BIGINT NOT NULL,
    STRATEGY_FK BIGINT NOT NULL
);         
ALTER TABLE PUBLIC."order" ADD CONSTRAINT PUBLIC.CONSTRAINT_65 PRIMARY KEY(ID);               
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."order"; 
CREATE INDEX PUBLIC.INDEX_65 ON PUBLIC."order"(ACCOUNT_FK);   
CREATE INDEX PUBLIC.INDEX_651 ON PUBLIC."order"(SECURITY_FK); 
CREATE INDEX PUBLIC.INDEX_6518 ON PUBLIC."order"(STRATEGY_FK);
CREATE CACHED TABLE PUBLIC."order_preference"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_43DFA47F_EB5D_49EF_AB62_037EF0C0AE97) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_43DFA47F_EB5D_49EF_AB62_037EF0C0AE97,
    NAME VARCHAR(50) NOT NULL,
    ORDER_TYPE VARCHAR(100) NOT NULL,
    DEFAULT_ACCOUNT_FK BIGINT DEFAULT NULL,
    VERSION INT NOT NULL
);           
ALTER TABLE PUBLIC."order_preference" ADD CONSTRAINT PUBLIC.CONSTRAINT_7D PRIMARY KEY(ID);    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."order_preference";      
CREATE INDEX PUBLIC.INDEX_7 ON PUBLIC."order_preference"(DEFAULT_ACCOUNT_FK); 
CREATE CACHED TABLE PUBLIC."order_property"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_1B9988FB_CE39_4B8E_B924_F7AFBFA3A376) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_1B9988FB_CE39_4B8E_B924_F7AFBFA3A376,
    NAME VARCHAR(30) NOT NULL,
    VALUE VARCHAR(255) NOT NULL,
    TYPE VARCHAR(100) NOT NULL,
    ORDER_FK BIGINT NOT NULL
);          
ALTER TABLE PUBLIC."order_property" ADD CONSTRAINT PUBLIC.CONSTRAINT_78 PRIMARY KEY(ID);      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."order_property";        
CREATE INDEX PUBLIC.INDEX_78 ON PUBLIC."order_property"(ORDER_FK);            
CREATE CACHED TABLE PUBLIC."order_status"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_8259C729_ACE2_446C_981D_B620DD8C876D) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_8259C729_ACE2_446C_981D_B620DD8C876D,
    DATE_TIME DATETIME NOT NULL,
    EXT_DATE_TIME DATETIME NOT NULL,
    STATUS VARCHAR(100) NOT NULL,
    FILLED_QUANTITY BIGINT NOT NULL,
    REMAINING_QUANTITY BIGINT NOT NULL,
    AVG_PRICE DECIMAL(15, 6) DEFAULT NULL,
    LAST_PRICE DECIMAL(15, 6) DEFAULT NULL,
    INT_ID VARCHAR(30) DEFAULT NULL,
    EXT_ID VARCHAR(50) DEFAULT NULL,
    SEQUENCE_NUMBER BIGINT NOT NULL,
    REASON VARCHAR(255) DEFAULT NULL,
    ORDER_FK BIGINT NOT NULL
);   
ALTER TABLE PUBLIC."order_status" ADD CONSTRAINT PUBLIC.CONSTRAINT_3E PRIMARY KEY(ID);        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."order_status";          
CREATE INDEX PUBLIC.INDEX_3E ON PUBLIC."order_status"(ORDER_FK);              
CREATE CACHED TABLE PUBLIC."portfolio_value"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_4F6250B8_F34C_4610_8B1E_2ACA6291D30B) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_4F6250B8_F34C_4610_8B1E_2ACA6291D30B,
    DATE_TIME DATETIME NOT NULL,
    SECURITIES_CURRENT_VALUE DECIMAL(15, 6) NOT NULL,
    CASH_BALANCE DECIMAL(15, 6) NOT NULL,
    MAINTENANCE_MARGIN DECIMAL(15, 6) DEFAULT NULL,
    NET_LIQ_VALUE DECIMAL(15, 6) NOT NULL,
    LEVERAGE DOUBLE NOT NULL,
    ALLOCATION DOUBLE NOT NULL,
    CASH_FLOW DECIMAL(15, 6) DEFAULT NULL,
    STRATEGY_FK BIGINT NOT NULL
);        
ALTER TABLE PUBLIC."portfolio_value" ADD CONSTRAINT PUBLIC.CONSTRAINT_F1 PRIMARY KEY(ID);     
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."portfolio_value";       
CREATE INDEX PUBLIC.INDEX_F1 ON PUBLIC."portfolio_value"(STRATEGY_FK);        
CREATE CACHED TABLE PUBLIC."position"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_A8ED2AC8_4D0C_4491_A140_88D6094386DE) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_A8ED2AC8_4D0C_4491_A140_88D6094386DE,
    QUANTITY BIGINT NOT NULL,
    COST DOUBLE NOT NULL,
    REALIZED_P_L DOUBLE NOT NULL,
    EXIT_VALUE DECIMAL(15, 6) DEFAULT NULL,
    MAINTENANCE_MARGIN DECIMAL(15, 2) DEFAULT NULL,
    PERSISTENT BIT NOT NULL,
    SECURITY_FK BIGINT NOT NULL,
    STRATEGY_FK BIGINT NOT NULL,
    VERSION INT DEFAULT '0' NOT NULL
);          
ALTER TABLE PUBLIC."position" ADD CONSTRAINT PUBLIC.CONSTRAINT_2C PRIMARY KEY(ID);            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."position";              
CREATE INDEX PUBLIC.INDEX_2C ON PUBLIC."position"(SECURITY_FK);               
CREATE INDEX PUBLIC.INDEX_2C9 ON PUBLIC."position"(STRATEGY_FK);              
CREATE CACHED TABLE PUBLIC."property"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_9B44E597_EFF5_479A_8D9F_EE0E66ECC12C) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_9B44E597_EFF5_479A_8D9F_EE0E66ECC12C,
    NAME VARCHAR(255) NOT NULL,
    PERSISTENT BIT NOT NULL,
    INT_VALUE INT DEFAULT NULL,
    DOUBLE_VALUE DOUBLE DEFAULT NULL,
    MONEY_VALUE DECIMAL(15, 6) DEFAULT NULL,
    TEXT_VALUE VARCHAR(255) DEFAULT NULL,
    DATE_TIME_VALUE DATETIME DEFAULT NULL,
    BOOLEAN_VALUE BIT DEFAULT NULL,
    PROPERTY_HOLDER_FK BIGINT NOT NULL,
    VERSION INT NOT NULL
);             
ALTER TABLE PUBLIC."property" ADD CONSTRAINT PUBLIC.CONSTRAINT_C4 PRIMARY KEY(ID);            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."property";              
CREATE CACHED TABLE PUBLIC."security"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_17A183AA_663B_4184_8C4E_AB35AEC58CB9) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_17A183AA_663B_4184_8C4E_AB35AEC58CB9,
    SYMBOL VARCHAR(30) DEFAULT NULL,
    ISIN VARCHAR(20) DEFAULT NULL,
    BBGID VARCHAR(12) DEFAULT NULL,
    RIC VARCHAR(20) DEFAULT NULL,
    CONID VARCHAR(30) DEFAULT NULL,
    LMAXID VARCHAR(30) DEFAULT NULL,
    UNDERLYING_FK BIGINT DEFAULT NULL,
    SECURITY_FAMILY_FK BIGINT NOT NULL
);    
ALTER TABLE PUBLIC."security" ADD CONSTRAINT PUBLIC.CONSTRAINT_38 PRIMARY KEY(ID);            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."security";              
CREATE INDEX PUBLIC.INDEX_38 ON PUBLIC."security"(SECURITY_FAMILY_FK);        
CREATE INDEX PUBLIC.INDEX_389 ON PUBLIC."security"(UNDERLYING_FK);            
CREATE CACHED TABLE PUBLIC."security_family"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_1889A79B_8778_4634_8CF0_496123F290FE) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_1889A79B_8778_4634_8CF0_496123F290FE,
    NAME VARCHAR(20) NOT NULL,
    SYMBOL_ROOT VARCHAR(20) DEFAULT NULL,
    ISIN_ROOT VARCHAR(20) DEFAULT NULL,
    RIC_ROOT VARCHAR(20) DEFAULT NULL,
    CURRENCY VARCHAR(100) NOT NULL,
    CONTRACT_SIZE DOUBLE NOT NULL,
    SCALE INT NOT NULL,
    TICK_SIZE_PATTERN VARCHAR(100) NOT NULL,
    EXECUTION_COMMISSION DECIMAL(5, 2) DEFAULT NULL,
    CLEARING_COMMISSION DECIMAL(5, 2) DEFAULT NULL,
    FEE DECIMAL(5, 2) DEFAULT NULL,
    TRADEABLE BIT NOT NULL,
    SYNTHETIC BIT NOT NULL,
    PERIODICITY VARCHAR(100) DEFAULT NULL,
    MAX_GAP INT DEFAULT NULL,
    UNDERLYING_FK BIGINT DEFAULT NULL,
    EXCHANGE_FK BIGINT DEFAULT NULL
);            
ALTER TABLE PUBLIC."security_family" ADD CONSTRAINT PUBLIC.CONSTRAINT_58 PRIMARY KEY(ID);     
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."security_family";       
CREATE INDEX PUBLIC.INDEX_58 ON PUBLIC."security_family"(UNDERLYING_FK);      
CREATE INDEX PUBLIC.INDEX_585 ON PUBLIC."security_family"(EXCHANGE_FK);       
CREATE CACHED TABLE PUBLIC."security_reference"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_4AA182DE_7BCB_4951_9A5C_BE1FBAEE657A) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_4AA182DE_7BCB_4951_9A5C_BE1FBAEE657A,
    NAME VARCHAR(100) NOT NULL,
    OWNER_FK BIGINT NOT NULL,
    TARGET_FK BIGINT NOT NULL
);        
ALTER TABLE PUBLIC."security_reference" ADD CONSTRAINT PUBLIC.CONSTRAINT_22 PRIMARY KEY(ID);  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."security_reference";    
CREATE INDEX PUBLIC.INDEX_22 ON PUBLIC."security_reference"(OWNER_FK);        
CREATE INDEX PUBLIC.INDEX_227 ON PUBLIC."security_reference"(TARGET_FK);      
CREATE CACHED TABLE PUBLIC."stock"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_C3667629_79C2_46F4_9C3B_CA0B6772261E) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_C3667629_79C2_46F4_9C3B_CA0B6772261E,
    GICS CHAR(8) DEFAULT NULL
);     
ALTER TABLE PUBLIC."stock" ADD CONSTRAINT PUBLIC.CONSTRAINT_68 PRIMARY KEY(ID);               
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."stock"; 
CREATE INDEX PUBLIC.INDEX_68 ON PUBLIC."stock"(GICS);         
CREATE INDEX PUBLIC.INDEX_68A ON PUBLIC."stock"(ID);          
CREATE CACHED TABLE PUBLIC."strategy"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_380E93AC_094B_4BD5_B1EA_BA64038A4FD8) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_380E93AC_094B_4BD5_B1EA_BA64038A4FD8,
    NAME VARCHAR(30) NOT NULL,
    AUTO_ACTIVATE BIT NOT NULL,
    ALLOCATION DOUBLE NOT NULL,
    VERSION INT DEFAULT '0' NOT NULL
);         
ALTER TABLE PUBLIC."strategy" ADD CONSTRAINT PUBLIC.CONSTRAINT_6A PRIMARY KEY(ID);            
-- 1 +/- SELECT COUNT(*) FROM PUBLIC."strategy";              
INSERT INTO PUBLIC."strategy"(ID, NAME, AUTO_ACTIVATE, ALLOCATION, VERSION) VALUES
(1, 'SERVER', TRUE, 0.0, 0);              
CREATE CACHED TABLE PUBLIC."subscription"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_8D9A2413_23A9_4832_B5E1_1F7382AAFD1B) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_8D9A2413_23A9_4832_B5E1_1F7382AAFD1B,
    SECURITY_FK BIGINT NOT NULL,
    STRATEGY_FK BIGINT NOT NULL,
    FEED_TYPE VARCHAR(100) NOT NULL,
    PERSISTENT BIT NOT NULL,
    VERSION INT NOT NULL
);           
ALTER TABLE PUBLIC."subscription" ADD CONSTRAINT PUBLIC.CONSTRAINT_14 PRIMARY KEY(ID);        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."subscription";          
CREATE INDEX PUBLIC.INDEX_14 ON PUBLIC."subscription"(PERSISTENT);            
CREATE INDEX PUBLIC.INDEX_145 ON PUBLIC."subscription"(SECURITY_FK);          
CREATE INDEX PUBLIC.INDEX_1456 ON PUBLIC."subscription"(STRATEGY_FK);         
CREATE INDEX PUBLIC.INDEX_14565 ON PUBLIC."subscription"(FEED_TYPE);          
CREATE CACHED TABLE PUBLIC."tick"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_F6102437_4740_4714_97B0_C7D3747E562B) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_F6102437_4740_4714_97B0_C7D3747E562B,
    DATE_TIME DATETIME NOT NULL,
    LAST DECIMAL(13, 6) DEFAULT NULL,
    LAST_DATE_TIME DATETIME DEFAULT NULL,
    VOL INT NOT NULL,
    VOL_BID INT NOT NULL,
    VOL_ASK INT NOT NULL,
    BID DECIMAL(13, 6) DEFAULT NULL,
    ASK DECIMAL(13, 6) DEFAULT NULL,
    FEED_TYPE VARCHAR(100) NOT NULL,
    SECURITY_FK BIGINT NOT NULL
); 
ALTER TABLE PUBLIC."tick" ADD CONSTRAINT PUBLIC.CONSTRAINT_36 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."tick";  
CREATE INDEX PUBLIC.INDEX_36 ON PUBLIC."tick"(DATE_TIME);     
CREATE INDEX PUBLIC.INDEX_365 ON PUBLIC."tick"(SECURITY_FK);  
CREATE INDEX PUBLIC.INDEX_3651 ON PUBLIC."tick"(FEED_TYPE);   
CREATE CACHED TABLE PUBLIC."trading_hours"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_C3D1CA75_BA38_4CA3_A86B_BCB46A7944CE) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_C3D1CA75_BA38_4CA3_A86B_BCB46A7944CE,
    OPEN TIME NOT NULL,
    CLOSE TIME NOT NULL,
    SUNDAY BIT NOT NULL,
    MONDAY BIT NOT NULL,
    TUESDAY BIT NOT NULL,
    WEDNESDAY BIT NOT NULL,
    THURSDAY BIT NOT NULL,
    FRIDAY BIT NOT NULL,
    SATURDAY BIT NOT NULL,
    EXCHANGE_FK BIGINT NOT NULL
);          
ALTER TABLE PUBLIC."trading_hours" ADD CONSTRAINT PUBLIC.CONSTRAINT_BB PRIMARY KEY(ID);       
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."trading_hours";         
CREATE INDEX PUBLIC.INDEX_BB ON PUBLIC."trading_hours"(EXCHANGE_FK);          
CREATE CACHED TABLE PUBLIC."transaction"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_6A8299C1_E176_4FB1_BAA5_7869C772E532) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_6A8299C1_E176_4FB1_BAA5_7869C772E532,
    EXT_ID VARCHAR(30) DEFAULT NULL,
    INT_ORDER_ID VARCHAR(30) DEFAULT NULL,
    EXT_ORDER_ID VARCHAR(50) DEFAULT NULL,
    DATE_TIME DATETIME NOT NULL,
    SETTLEMENT_DATE DATE DEFAULT NULL,
    QUANTITY BIGINT NOT NULL,
    PRICE DECIMAL(15, 6) NOT NULL,
    EXECUTION_COMMISSION DECIMAL(15, 2) DEFAULT NULL,
    CLEARING_COMMISSION DECIMAL(15, 2) DEFAULT NULL,
    FEE DECIMAL(15, 2) DEFAULT NULL,
    CURRENCY VARCHAR(100) NOT NULL,
    TYPE VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(255) DEFAULT NULL,
    SECURITY_FK BIGINT DEFAULT NULL,
    STRATEGY_FK BIGINT NOT NULL,
    POSITION_FK BIGINT DEFAULT NULL,
    ACCOUNT_FK BIGINT DEFAULT NULL
);            
ALTER TABLE PUBLIC."transaction" ADD CONSTRAINT PUBLIC.CONSTRAINT_7F PRIMARY KEY(ID);         
-- 1 +/- SELECT COUNT(*) FROM PUBLIC."transaction";           
INSERT INTO PUBLIC."transaction"(ID, EXT_ID, INT_ORDER_ID, EXT_ORDER_ID, DATE_TIME, SETTLEMENT_DATE, QUANTITY, PRICE, EXECUTION_COMMISSION, CLEARING_COMMISSION, FEE, CURRENCY, TYPE, DESCRIPTION, SECURITY_FK, STRATEGY_FK, POSITION_FK, ACCOUNT_FK) VALUES
(1, NULL, NULL, NULL, TIMESTAMP '2012-08-16 00:00:00.0', NULL, 1, 1000000.000000, NULL, NULL, NULL, 'USD', 'CREDIT', NULL, NULL, 1, NULL, NULL);
CREATE INDEX PUBLIC.INDEX_7F ON PUBLIC."transaction"(DATE_TIME);              
CREATE INDEX PUBLIC.INDEX_7FA ON PUBLIC."transaction"(SETTLEMENT_DATE);       
CREATE INDEX PUBLIC.INDEX_7FA0 ON PUBLIC."transaction"(CURRENCY);             
CREATE INDEX PUBLIC.INDEX_7FA0D ON PUBLIC."transaction"(STRATEGY_FK);         
CREATE INDEX PUBLIC.INDEX_7FA0D2 ON PUBLIC."transaction"(POSITION_FK);        
CREATE INDEX PUBLIC.INDEX_7FA0D2D ON PUBLIC."transaction"(SECURITY_FK);       
CREATE INDEX PUBLIC.INDEX_7FA0D2DE_0 ON PUBLIC."transaction"(ACCOUNT_FK);     
ALTER TABLE PUBLIC."security" ADD CONSTRAINT PUBLIC.CONSTRAINT_38927 UNIQUE(BBGID);           
ALTER TABLE PUBLIC."allocation" ADD CONSTRAINT PUBLIC.CONSTRAINT_8E UNIQUE(ORDER_PREFERENCE_FK, ACCOUNT_FK);  
ALTER TABLE PUBLIC."broker_parameters" ADD CONSTRAINT PUBLIC.CONSTRAINT_94 UNIQUE(BROKER, SECURITY_FAMILY_FK);
ALTER TABLE PUBLIC."strategy" ADD CONSTRAINT PUBLIC.CONSTRAINT_6A8 UNIQUE(NAME);              
ALTER TABLE PUBLIC."exchange" ADD CONSTRAINT PUBLIC.CONSTRAINT_76 UNIQUE(NAME);               
ALTER TABLE PUBLIC."security" ADD CONSTRAINT PUBLIC.CONSTRAINT_3892 UNIQUE(ISIN);             
ALTER TABLE PUBLIC."bar" ADD CONSTRAINT PUBLIC.CONSTRAINT_17 UNIQUE(DATE_TIME, SECURITY_FK, BAR_SIZE);        
ALTER TABLE PUBLIC."security" ADD CONSTRAINT PUBLIC.CONSTRAINT_389 UNIQUE(SYMBOL, SECURITY_FAMILY_FK);        
ALTER TABLE PUBLIC."subscription" ADD CONSTRAINT PUBLIC.CONSTRAINT_145 UNIQUE(SECURITY_FK, STRATEGY_FK, FEED_TYPE);           
ALTER TABLE PUBLIC."account" ADD CONSTRAINT PUBLIC.CONSTRAINT_B9 UNIQUE(NAME);
ALTER TABLE PUBLIC."measurement" ADD CONSTRAINT PUBLIC.CONSTRAINT_93F UNIQUE(DATE_TIME, NAME, STRATEGY_FK);   
ALTER TABLE PUBLIC."component" ADD CONSTRAINT PUBLIC.CONSTRAINT_AC8 UNIQUE(SECURITY_FK, COMBINATION_FK);      
ALTER TABLE PUBLIC."easy_to_borrow" ADD CONSTRAINT PUBLIC.CONSTRAINT_80E UNIQUE(DATE, BROKER, STOCK_FK);      
ALTER TABLE PUBLIC."tick" ADD CONSTRAINT PUBLIC.CONSTRAINT_365 UNIQUE(DATE_TIME, SECURITY_FK, FEED_TYPE);     
ALTER TABLE PUBLIC."transaction" ADD CONSTRAINT PUBLIC.CONSTRAINT_7FA UNIQUE(EXT_ID);         
ALTER TABLE PUBLIC."cash_balance" ADD CONSTRAINT PUBLIC.CONSTRAINT_D5 UNIQUE(CURRENCY, STRATEGY_FK);          
ALTER TABLE PUBLIC."security" ADD CONSTRAINT PUBLIC.CONSTRAINT_3892774 UNIQUE(CONID);         
ALTER TABLE PUBLIC."security" ADD CONSTRAINT PUBLIC.CONSTRAINT_389277 UNIQUE(RIC);            
ALTER TABLE PUBLIC."property" ADD CONSTRAINT PUBLIC.CONSTRAINT_C4C UNIQUE(NAME, PROPERTY_HOLDER_FK);          
ALTER TABLE PUBLIC."position" ADD CONSTRAINT PUBLIC.CONSTRAINT_2C9 UNIQUE(SECURITY_FK, STRATEGY_FK);          
ALTER TABLE PUBLIC."portfolio_value" ADD CONSTRAINT PUBLIC.CONSTRAINT_F1C UNIQUE(DATE_TIME, STRATEGY_FK);     
ALTER TABLE PUBLIC."security_family" ADD CONSTRAINT PUBLIC.CONSTRAINT_585 UNIQUE(NAME);       
ALTER TABLE PUBLIC."order_preference" ADD CONSTRAINT PUBLIC.CONSTRAINT_7D3 UNIQUE(NAME);      
ALTER TABLE PUBLIC."allocation" ADD CONSTRAINT PUBLIC.ALLOCATION_ACCOUNT_FKC FOREIGN KEY(ACCOUNT_FK) REFERENCES PUBLIC."account"(ID) NOCHECK; 
ALTER TABLE PUBLIC."security_family" ADD CONSTRAINT PUBLIC.SECURITY_FAMILY_MARKET_FKC FOREIGN KEY(EXCHANGE_FK) REFERENCES PUBLIC."exchange"(ID) NOCHECK;      
ALTER TABLE PUBLIC."trading_hours" ADD CONSTRAINT PUBLIC.TRADING_HOURS_EXCHANGE_FKC FOREIGN KEY(EXCHANGE_FK) REFERENCES PUBLIC."exchange"(ID) ON DELETE CASCADE ON UPDATE CASCADE NOCHECK;    
ALTER TABLE PUBLIC."order_property" ADD CONSTRAINT PUBLIC.ORDER_PROPERTY_ORDER_FKC FOREIGN KEY(ORDER_FK) REFERENCES PUBLIC."order"(ID) NOCHECK;               
ALTER TABLE PUBLIC."security_family" ADD CONSTRAINT PUBLIC.SECURITY_FAMILY_UNDERLAYING_FKC FOREIGN KEY(UNDERLYING_FK) REFERENCES PUBLIC."security"(ID) ON DELETE CASCADE ON UPDATE CASCADE NOCHECK;           
ALTER TABLE PUBLIC."security" ADD CONSTRAINT PUBLIC.SECURITY_UNDERLYING_FKC FOREIGN KEY(UNDERLYING_FK) REFERENCES PUBLIC."security"(ID) ON UPDATE CASCADE NOCHECK;            
ALTER TABLE PUBLIC."order_preference" ADD CONSTRAINT PUBLIC.ORDER_PREFERENCE_DEFAULT_ACCOC FOREIGN KEY(DEFAULT_ACCOUNT_FK) REFERENCES PUBLIC."account"(ID) ON UPDATE CASCADE NOCHECK;         
ALTER TABLE PUBLIC."security_reference" ADD CONSTRAINT PUBLIC.SECURITY_REFERENCE_OWNER_FKC FOREIGN KEY(OWNER_FK) REFERENCES PUBLIC."security"(ID) NOCHECK;    
ALTER TABLE PUBLIC."transaction" ADD CONSTRAINT PUBLIC.TRANSACTION_ACCOUNT_FKC FOREIGN KEY(ACCOUNT_FK) REFERENCES PUBLIC."account"(ID) ON UPDATE CASCADE NOCHECK;             
ALTER TABLE PUBLIC."security_reference" ADD CONSTRAINT PUBLIC.SECURITY_REFERENCE_TARGET_FKC FOREIGN KEY(TARGET_FK) REFERENCES PUBLIC."security"(ID) NOCHECK;  
ALTER TABLE PUBLIC."subscription" ADD CONSTRAINT PUBLIC.SUBSCRIPTION_STRATEGY_FKC FOREIGN KEY(STRATEGY_FK) REFERENCES PUBLIC."strategy"(ID) ON UPDATE CASCADE NOCHECK;        
ALTER TABLE PUBLIC."order" ADD CONSTRAINT PUBLIC.ORDER_ACCOUNT_FKC FOREIGN KEY(ACCOUNT_FK) REFERENCES PUBLIC."account"(ID) NOCHECK;           
ALTER TABLE PUBLIC."subscription" ADD CONSTRAINT PUBLIC.SUBSCRIPTION_SECURITY_FKC FOREIGN KEY(SECURITY_FK) REFERENCES PUBLIC."security"(ID) ON UPDATE CASCADE NOCHECK;        
ALTER TABLE PUBLIC."component" ADD CONSTRAINT PUBLIC.COMPONENT_COMBINATION_FK FOREIGN KEY(COMBINATION_FK) REFERENCES PUBLIC."combination"(ID) ON DELETE CASCADE ON UPDATE CASCADE NOCHECK;    
ALTER TABLE PUBLIC."stock" ADD CONSTRAINT PUBLIC.STOCKIFKC FOREIGN KEY(ID) REFERENCES PUBLIC."security"(ID) ON DELETE CASCADE ON UPDATE CASCADE NOCHECK;      
ALTER TABLE PUBLIC."holiday" ADD CONSTRAINT PUBLIC.HOLIDAY_MARKET_FKC FOREIGN KEY(EXCHANGE_FK) REFERENCES PUBLIC."exchange"(ID) ON DELETE CASCADE ON UPDATE CASCADE NOCHECK;  
ALTER TABLE PUBLIC."transaction" ADD CONSTRAINT PUBLIC.TRANSACTION_POSITION_FKC FOREIGN KEY(POSITION_FK) REFERENCES PUBLIC."position"(ID) ON UPDATE CASCADE NOCHECK;          
ALTER TABLE PUBLIC."order_status" ADD CONSTRAINT PUBLIC.ORDER_STATUS_ORDER_FKC FOREIGN KEY(ORDER_FK) REFERENCES PUBLIC."order"(ID) ON DELETE CASCADE ON UPDATE CASCADE NOCHECK;               
ALTER TABLE PUBLIC."transaction" ADD CONSTRAINT PUBLIC.TRANSACTION_STRATEGY_FKC FOREIGN KEY(STRATEGY_FK) REFERENCES PUBLIC."strategy"(ID) ON UPDATE CASCADE NOCHECK;          
ALTER TABLE PUBLIC."transaction" ADD CONSTRAINT PUBLIC.TRANSACTION_SECURITY_FKC FOREIGN KEY(SECURITY_FK) REFERENCES PUBLIC."security"(ID) ON UPDATE CASCADE NOCHECK;          
