SET FOREIGN_KEY_CHECKS=0;

--
-- Table structure for table `account`
--

CREATE TABLE `account` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(20) NOT NULL,
  `ACTIVE` bit(1) NOT NULL,
  `BROKER` enum('IB','JPM','DC','RBS','RT') DEFAULT NULL,
  `ORDER_SERVICE_TYPE` enum('IB_NATIVE','IB_FIX','JPM_FIX','DC_FIX','RT_FIX') NOT NULL,
  `SESSION_QUALIFIER` varchar(10) DEFAULT NULL,
  `EXT_ACCOUNT` varchar(20) DEFAULT NULL,
  `EXT_ACCOUNT_GROUP` varchar(20) DEFAULT NULL,
  `EXT_ALLOCATION_PROFILE` varchar(20) DEFAULT NULL,
  `EXT_CLEARING_ACCOUNT` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `NAME_UNIQUE` (`NAME`),
  KEY `ACTIVE` (`ACTIVE`),
  KEY `BROKER` (`BROKER`),
  KEY `ORDER_SERVICE_TYPE` (`ORDER_SERVICE_TYPE`)
) ENGINE=InnoDB CHARACTER SET=latin1 ROW_FORMAT=Compact;

--
-- Table structure for table `allocation`
--

CREATE TABLE `allocation` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `VALUE` double NOT NULL,
  `ORDER_PREFERENCE_FK` int(11) NOT NULL,
  `ACCOUNT_FK` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ORDER_PREFERENCE_ACCOUNT_UNIQUE` (`ORDER_PREFERENCE_FK`,`ACCOUNT_FK`),
  KEY `ALLOCATION_ACCOUNT_FKC` (`ACCOUNT_FK`),
  KEY `ALLOCATION_ORDER_PREFERENCE_FKC` (`ORDER_PREFERENCE_FK`),
  CONSTRAINT `ALLOCATION_ACCOUNT_FKC` FOREIGN KEY (`ACCOUNT_FK`) REFERENCES `account` (`ID`),
  CONSTRAINT `ALLOCATION_ORDER_PREFERENCE_FKC` FOREIGN KEY (`ORDER_PREFERENCE_FK`) REFERENCES `order_preference` (`ID`)
) ENGINE=InnoDB CHARACTER SET=latin1 ROW_FORMAT=Compact;

--
-- Table structure for table `bar`
--

CREATE TABLE `bar` (
  `ID` int(11) NOT NULL,
  `DATE_TIME` datetime NOT NULL,
  `OPEN` decimal(13,6) NOT NULL,
  `HIGH` decimal(13,6) NOT NULL,
  `LOW` decimal(13,6) NOT NULL,
  `CLOSE` decimal(13,6) NOT NULL,
  `VOL` int(11) NOT NULL,
  `BAR_SIZE` enum('MSEC_1','SEC_1','MIN_1','MIN_2','MIN_5','MIN_15','MIN_30','HOUR_1','HOUR_2','DAY_1','DAY_2','WEEK_1','WEEK_2','MONTH_1','MONTH_2','MONTH_3','MONTH_4','MONTH_5','MONTH_6','MONTH_7','MONTH_8','MONTH_9','MONTH_10','MONTH_11','MONTH_18','YEAR_1','YEAR_2') NOT NULL,
  `FEED_TYPE` enum('IB','BB','DC') DEFAULT NULL,
  `SECURITY_FK` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `DATE_TIME_SECURITY_BAR_SIZE_UNIQUE` (`DATE_TIME`,`SECURITY_FK`,`BAR_SIZE`),
  KEY `DATE_TIME` (`DATE_TIME`),
  KEY `SECURITY_FK` (`SECURITY_FK`),
  KEY `BAR_SIZE` (`BAR_SIZE`)
) ENGINE=MyISAM CHARACTER SET=latin1 ROW_FORMAT=Fixed;

--
-- Table structure for table `bond`
--

CREATE TABLE `bond` (
  `ID` int(11) NOT NULL,
  `MATURITY` datetime NOT NULL,
  `COUPON` double NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `MATURITY` (`MATURITY`),
  KEY `BONDIFKC` (`ID`),
  CONSTRAINT `BONDIFKC` FOREIGN KEY (`ID`) REFERENCES `security` (`ID`)
) ENGINE=InnoDB CHARACTER SET=latin1 ROW_FORMAT=Compact;

--
-- Table structure for table `bond_family`
--

CREATE TABLE `bond_family` (
  `ID` int(11) NOT NULL,
  `MATURITY_DISTANCE` enum('MSEC_1','SEC_1','MIN_1','MIN_2','MIN_5','MIN_15','MIN_30','HOUR_1','HOUR_2','DAY_1','DAY_2','WEEK_1','WEEK_2','MONTH_1','MONTH_2','MONTH_3','MONTH_4','MONTH_5','MONTH_6','MONTH_7','MONTH_8','MONTH_9','MONTH_10','MONTH_11','MONTH_18','YEAR_1','YEAR_2') NOT NULL,
  `LENGTH` int(11) NOT NULL,
  `QUOTATION_STYLE` enum('PRICE','YIELD') NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `BOND_FAMILYIFKC` (`ID`),
  CONSTRAINT `BOND_FAMILYIFKC` FOREIGN KEY (`ID`) REFERENCES `security_family` (`ID`)
) ENGINE=InnoDB CHARACTER SET=latin1 ROW_FORMAT=Compact;

--
-- Table structure for table `broker_parameters`
--

CREATE TABLE `broker_parameters` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `BROKER` enum('IB','JPM','DC','RBS') NOT NULL,
  `BASE_SYMBOL` varchar(20) DEFAULT NULL,
  `MARKET` varchar(20) DEFAULT NULL,
  `EXECUTION_COMMISSION` decimal(5,2) DEFAULT NULL,
  `CLEARING_COMMISSION` decimal(5,2) DEFAULT NULL,
  `FEE` decimal(5,2) DEFAULT NULL,
  `SECURITY_FAMILY_FK` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `BROKER_SECURITY_FAMILY_UNIQUE` (`BROKER`,`SECURITY_FAMILY_FK`),
  KEY `BROKER_PARAMETERS_SECURITY_FKC` (`SECURITY_FAMILY_FK`),
  CONSTRAINT `BROKER_PARAMETERS_SECURITY_FKC` FOREIGN KEY (`SECURITY_FAMILY_FK`) REFERENCES `security_family` (`ID`)
) ENGINE=InnoDB CHARACTER SET=latin1 ROW_FORMAT=Compact;

--
-- Table structure for table `cash_balance`
--

CREATE TABLE `cash_balance` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CURRENCY` enum('USD','EUR','CHF','GBP','CAD','JPY','AUD','NZD','HKD','SEK','NOK','BRL','RUB','INR') NOT NULL,
  `AMOUNT` decimal(15,2) NOT NULL,
  `STRATEGY_FK` int(11) NOT NULL,
  `VERSION` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CURRENCY_STRATEGY_UNIQUE` (`CURRENCY`,`STRATEGY_FK`),
  KEY `CASH_BALANCE_STRATEGY_FKC` (`STRATEGY_FK`),
  CONSTRAINT `CASH_BALANCE_STRATEGY_FKC` FOREIGN KEY (`STRATEGY_FK`) REFERENCES `strategy` (`ID`) ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET=latin1 ROW_FORMAT=Compact;

--
-- Table structure for table `combination`
--

CREATE TABLE `combination` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TYPE` enum('VERTICAL_SPREAD','COVERED_CALL','RATIO_SPREAD','STRADDLE','STRANGLE','BUTTERFLY','CALENDAR_SPREAD','IRON_CONDOR') NOT NULL,
  `PERSISTENT` bit(1) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `COMBINATIONIFKC` (`ID`),
  CONSTRAINT `COMBINATIONIFKC` FOREIGN KEY (`ID`) REFERENCES `security` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET=latin1 ROW_FORMAT=Compact;

--
-- Table structure for table `commodity`
--

CREATE TABLE `commodity` (
  `ID` int(11) NOT NULL,
  `TYPE` enum('ENERGY','INDUSTRIAL_METALS','PRECIOUS_METALS','AGRICULTURE','LIVESTOCK') NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `COMMODITYIFKC` (`ID`),
  CONSTRAINT `COMMODITYIFKC` FOREIGN KEY (`ID`) REFERENCES `security` (`ID`)
) ENGINE=InnoDB CHARACTER SET=latin1 ROW_FORMAT=Compact;

--
-- Table structure for table `component`
--

CREATE TABLE `component` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `QUANTITY` bigint(20) NOT NULL,
  `PERSISTENT` bit(1) NOT NULL,
  `SECURITY_FK` int(11) NOT NULL,
  `COMBINATION_FK` int(11) NOT NULL,
  `VERSION` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `SECURITY_COMBINATION_UNIQUE` (`SECURITY_FK`,`COMBINATION_FK`),
  KEY `COMPONENT_COMBINATION_FK` (`COMBINATION_FK`),
  KEY `COMPONENT_SECURITY_FKC` (`SECURITY_FK`),
  CONSTRAINT `COMPONENT_COMBINATION_FK` FOREIGN KEY (`COMBINATION_FK`) REFERENCES `combination` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `COMPONENT_SECURITY_FKC` FOREIGN KEY (`SECURITY_FK`) REFERENCES `security` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET=latin1 ROW_FORMAT=Compact;

--
-- Table structure for table `default_order_preference`
--

CREATE TABLE `default_order_preference` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ORDER_PREFERENCE_FK` int(11) NOT NULL,
  `STRATEGY_FK` int(11) NOT NULL,
  `SECURITY_FAMILY_FK` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `STRATEGY_SECURITY_FAMILY_UNIQUE` (`STRATEGY_FK`,`SECURITY_FAMILY_FK`),
  KEY `DEFAULT_ORDER_PREFERENCE_ORDER_PREFERENCE_FKC` (`ORDER_PREFERENCE_FK`),
  KEY `DEFAULT_ORDER_PREFERENCE_SECURITY_FAMILY_FKC` (`SECURITY_FAMILY_FK`),
  KEY `DEFAULT_ORDER_PREFERENCE_STRATEGY_FKC` (`STRATEGY_FK`),
  CONSTRAINT `DEFAULT_ORDER_PREFERENCE_ORDER_PREFERENCE_FKC` FOREIGN KEY (`ORDER_PREFERENCE_FK`) REFERENCES `order_preference` (`ID`) ON UPDATE CASCADE,
  CONSTRAINT `DEFAULT_ORDER_PREFERENCE_SECURITY_FAMILY_FKC` FOREIGN KEY (`SECURITY_FAMILY_FK`) REFERENCES `security_family` (`ID`) ON UPDATE CASCADE,
  CONSTRAINT `DEFAULT_ORDER_PREFERENCE_STRATEGY_FKC` FOREIGN KEY (`STRATEGY_FK`) REFERENCES `strategy` (`ID`) ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET=latin1 ROW_FORMAT=Compact;

--
-- Table structure for table `easy_to_borrow`
--

CREATE TABLE `easy_to_borrow` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DATE` datetime NOT NULL,
  `BROKER` varchar(255) NOT NULL,
  `QUANTITY` bigint(20) NOT NULL,
  `STOCK_FK` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `DATE_BROKER_STOCK_UNIQUE` (`DATE`,`BROKER`,`STOCK_FK`),
  KEY `EASY_TO_BORROW_STOCK_FKC` (`STOCK_FK`),
  CONSTRAINT `EASY_TO_BORROW_STOCK_FKC` FOREIGN KEY (`STOCK_FK`) REFERENCES `stock` (`ID`)
) ENGINE=InnoDB CHARACTER SET=latin1 ROW_FORMAT=Compact;

--
-- Table structure for table `forex`
--

CREATE TABLE `forex` (
  `ID` int(11) NOT NULL,
  `BASE_CURRENCY` enum('USD','EUR','CHF','GBP','CAD','JPY','AUD','NZD','HKD','SEK','NOK','BRL','RUB','INR') NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FOREXIFKC` (`ID`),
  CONSTRAINT `FOREXIFKC` FOREIGN KEY (`ID`) REFERENCES `security` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET=latin1 ROW_FORMAT=Compact;

--
-- Table structure for table `fund`
--

CREATE TABLE `fund` (
  `ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FUNDIFKC` (`ID`),
  CONSTRAINT `FUNDIFKC` FOREIGN KEY (`ID`) REFERENCES `security` (`ID`)
) ENGINE=InnoDB CHARACTER SET=latin1 ROW_FORMAT=Compact;

--
-- Table structure for table `future`
--

CREATE TABLE `future` (
  `ID` int(11) NOT NULL,
  `EXPIRATION` datetime NOT NULL,
  `FIRST_NOTICE` datetime DEFAULT NULL,
  `LAST_TRADING` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `EXPIRATION` (`EXPIRATION`),
  KEY `FIRST_NOTICE` (`FIRST_NOTICE`),
  KEY `LAST_TRADING` (`LAST_TRADING`),
  KEY `FUTUREIFKC` (`ID`),
  CONSTRAINT `FUTUREIFKC` FOREIGN KEY (`ID`) REFERENCES `security` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET=latin1 ROW_FORMAT=Compact;

--
-- Table structure for table `future_family`
--

CREATE TABLE `future_family` (
  `ID` int(11) NOT NULL,
  `INTREST` double NOT NULL,
  `DIVIDEND` double NOT NULL,
  `MARGIN_PARAMETER` double NOT NULL,
  `EXPIRATION_TYPE` enum('NEXT_3_RD_FRIDAY','NEXT_3_RD_FRIDAY_3_MONTHS','NEXT_3_RD_MONDAY_3_MONTHS','THIRTY_DAYS_BEFORE_NEXT_3_RD_FRIDAY') NOT NULL,
  `EXPIRATION_DISTANCE` enum('MSEC_1','SEC_1','MIN_1','MIN_2','MIN_5','MIN_15','MIN_30','HOUR_1','HOUR_2','DAY_1','DAY_2','WEEK_1','WEEK_2','MONTH_1','MONTH_2','MONTH_3','MONTH_4','MONTH_5','MONTH_6','MONTH_7','MONTH_8','MONTH_9','MONTH_10','MONTH_11','MONTH_18','YEAR_1','YEAR_2') NOT NULL,
  `LENGTH` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FUTURE_FAMILYIFKC` (`ID`),
  CONSTRAINT `FUTURE_FAMILYIFKC` FOREIGN KEY (`ID`) REFERENCES `security_family` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET=latin1 ROW_FORMAT=Compact;

--
-- Table structure for table `generic_future`
--

CREATE TABLE `generic_future` (
  `ID` int(11) NOT NULL,
  `DURATION` enum('MSEC_1','SEC_1','MIN_1','MIN_2','MIN_5','MIN_15','MIN_30','HOUR_1','HOUR_2','DAY_1','DAY_2','WEEK_1','WEEK_2','MONTH_1','MONTH_2','MONTH_3','MONTH_4','MONTH_5','MONTH_6','MONTH_7','MONTH_8','MONTH_9','MONTH_10','MONTH_11','MONTH_18','YEAR_1','YEAR_2') NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `DURATION` (`DURATION`),
  KEY `GENERIC_FUTUREIFKC` (`ID`),
  CONSTRAINT `GENERIC_FUTUREIFKC` FOREIGN KEY (`ID`) REFERENCES `security` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET=latin1 ROW_FORMAT=Compact;

--
-- Table structure for table `generic_future_family`
--

CREATE TABLE `generic_future_family` (
  `ID` int(11) NOT NULL,
  `EXPIRATION_TYPE` enum('NEXT_3_RD_FRIDAY','NEXT_3_RD_FRIDAY_3_MONTHS','THIRTY_DAYS_BEFORE_NEXT_3_RD_FRIDAY') NOT NULL,
  `EXPIRATION_DISTANCE` enum('MSEC_1','SEC_1','MIN_1','MIN_2','MIN_5','MIN_15','MIN_30','HOUR_1','HOUR_2','DAY_1','DAY_2','WEEK_1','WEEK_2','MONTH_1','MONTH_2','MONTH_3','MONTH_4','MONTH_5','MONTH_6','MONTH_7','MONTH_8','MONTH_9','MONTH_10','MONTH_11','MONTH_18','YEAR_1','YEAR_2') DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `GENERIC_FUTURE_FAMILYIFKC` (`ID`),
  CONSTRAINT `GENERIC_FUTURE_FAMILYIFKC` FOREIGN KEY (`ID`) REFERENCES `security_family` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET=latin1 ROW_FORMAT=Compact;

--
-- Table structure for table `implied_volatility`
--

CREATE TABLE `implied_volatility` (
  `ID` int(11) NOT NULL,
  `DURATION` enum('MSEC_1','SEC_1','MIN_1','MIN_2','MIN_5','MIN_15','MIN_30','HOUR_1','HOUR_2','DAY_1','DAY_2','WEEK_1','WEEK_2','MONTH_1','MONTH_2','MONTH_3','MONTH_4','MONTH_5','MONTH_6','MONTH_7','MONTH_8','MONTH_9','MONTH_10','MONTH_11','MONTH_18','YEAR_1','YEAR_2') NOT NULL,
  `MONEYNESS` double DEFAULT NULL,
  `DELTA` double DEFAULT NULL,
  `TYPE` enum('CALL','PUT') NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `IMPLIED_VOLATILITYIFKC` (`ID`),
  CONSTRAINT `IMPLIED_VOLATILITYIFKC` FOREIGN KEY (`ID`) REFERENCES `security` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET=latin1 ROW_FORMAT=Compact;

--
-- Table structure for table `index`
--

CREATE TABLE `index` (
  `ID` int(11) NOT NULL,
  `TYPE` enum('EQUITY','VOLATILITY','COMMODITY') NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `INDEXIFKC` (`ID`),
  CONSTRAINT `INDEXIFKC` FOREIGN KEY (`ID`) REFERENCES `security` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET=latin1 ROW_FORMAT=Compact;

--
-- Table structure for table `intrest_rate`
--

CREATE TABLE `intrest_rate` (
  `ID` int(11) NOT NULL,
  `DURATION` enum('MSEC_1','SEC_1','MIN_1','MIN_2','MIN_5','MIN_15','MIN_30','HOUR_1','HOUR_2','DAY_1','DAY_2','WEEK_1','WEEK_2','MONTH_1','MONTH_2','MONTH_3','MONTH_4','MONTH_5','MONTH_6','MONTH_7','MONTH_8','MONTH_9','MONTH_10','MONTH_11','MONTH_18','YEAR_1','YEAR_2') NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `INTREST_RATEIFKC` (`ID`),
  CONSTRAINT `INTREST_RATEIFKC` FOREIGN KEY (`ID`) REFERENCES `security` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET=latin1 ROW_FORMAT=Compact;

--
-- Table structure for table `measurement`
--

CREATE TABLE `measurement` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `DATE` datetime NOT NULL,
  `INT_VALUE` int(11) DEFAULT NULL,
  `DOUBLE_VALUE` double DEFAULT NULL,
  `MONEY_VALUE` decimal(15,6) DEFAULT NULL,
  `TEXT_VALUE` varchar(50) DEFAULT NULL,
  `BOOLEAN_VALUE` bit(1) DEFAULT NULL,
  `STRATEGY_FK` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `DATE_NAME_STRATEGY_UNIQUE` (`DATE`,`NAME`,`STRATEGY_FK`),
  KEY `MEASUREMENT_STRATEGY_FKC` (`STRATEGY_FK`),
  CONSTRAINT `MEASUREMENT_STRATEGY_FKC` FOREIGN KEY (`STRATEGY_FK`) REFERENCES `strategy` (`ID`) ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET=latin1 ROW_FORMAT=Compact;

--
-- Table structure for table `option`
--

CREATE TABLE `option` (
  `ID` int(11) NOT NULL,
  `STRIKE` decimal(12,5) NOT NULL,
  `EXPIRATION` datetime NOT NULL,
  `TYPE` enum('CALL','PUT') NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `EXPIRATION` (`EXPIRATION`),
  KEY `STRIKE` (`STRIKE`),
  KEY `TYPE` (`TYPE`),
  KEY `OPTIONIFKC` (`ID`),
  CONSTRAINT `OPTIONIFKC` FOREIGN KEY (`ID`) REFERENCES `security` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET=latin1 ROW_FORMAT=Compact;

--
-- Table structure for table `option_family`
--

CREATE TABLE `option_family` (
  `ID` int(11) NOT NULL,
  `INTREST` double NOT NULL,
  `DIVIDEND` double NOT NULL,
  `MARGIN_PARAMETER` double DEFAULT NULL,
  `EXPIRATION_TYPE` enum('NEXT_3_RD_FRIDAY','NEXT_3_RD_FRIDAY_3_MONTHS','THIRTY_DAYS_BEFORE_NEXT_3_RD_FRIDAY') DEFAULT NULL,
  `EXPIRATION_DISTANCE` enum('MSEC_1','SEC_1','MIN_1','MIN_2','MIN_5','MIN_15','MIN_30','HOUR_1','HOUR_2','DAY_1','DAY_2','WEEK_1','WEEK_2','MONTH_1','MONTH_2','MONTH_3','MONTH_4','MONTH_5','MONTH_6','MONTH_7','MONTH_8','MONTH_9','MONTH_10','MONTH_11','MONTH_18','YEAR_1','YEAR_2') DEFAULT NULL,
  `STRIKE_DISTANCE` double DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `OPTION_FAMILYIFKC` (`ID`),
  CONSTRAINT `OPTION_FAMILYIFKC` FOREIGN KEY (`ID`) REFERENCES `security_family` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET=latin1 ROW_FORMAT=Compact;

--
-- Table structure for table `order_preference`
--

CREATE TABLE `order_preference` (
  `ID` int(11) NOT NULL,
  `NAME` varchar(50) NOT NULL,
  `ORDER_TYPE` enum('MARKET','LIMIT','STOP','STOP_LIMIT','SLICING','TICKWISE_INCREMENTAL','VARIABLE_INCREMENTAL','DISTRIBUTIONAL') NOT NULL,
  `DEFAULT_ACCOUNT_FK` int(11) DEFAULT NULL,
  `VERSION` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `NAME_UNIQUE` (`NAME`),
  KEY `ORDER_PREFERENCE_DEFAULT_ACCOC` (`DEFAULT_ACCOUNT_FK`),
  CONSTRAINT `ORDER_PREFERENCE_DEFAULT_ACCOC` FOREIGN KEY (`DEFAULT_ACCOUNT_FK`) REFERENCES `account` (`ID`) ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET=latin1 ROW_FORMAT=Compact;

--
-- Table structure for table `portfolio_value`
--

CREATE TABLE `portfolio_value` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DATE_TIME` datetime NOT NULL,
  `SECURITIES_CURRENT_VALUE` decimal(15,6) NOT NULL,
  `CASH_BALANCE` decimal(15,6) NOT NULL,
  `MAINTENANCE_MARGIN` decimal(15,6) DEFAULT NULL,
  `NET_LIQ_VALUE` decimal(15,6) NOT NULL,
  `LEVERAGE` double NOT NULL,
  `ALLOCATION` double NOT NULL,
  `CASH_FLOW` decimal(15,6) DEFAULT NULL,
  `STRATEGY_FK` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `DATE_TIME_STRATEGY_UNIQUE` (`DATE_TIME`,`STRATEGY_FK`),
  KEY `PORTFOLIO_VALUE_STRATEGY_FKC` (`STRATEGY_FK`),
  CONSTRAINT `PORTFOLIO_VALUE_STRATEGY_FKC` FOREIGN KEY (`STRATEGY_FK`) REFERENCES `strategy` (`ID`) ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET=latin1 ROW_FORMAT=Compact;

--
-- Table structure for table `position`
--

CREATE TABLE `position` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `QUANTITY` bigint(20) NOT NULL,
  `COST` double NOT NULL,
  `REALIZED_P_L` double DEFAULT NULL,
  `EXIT_VALUE` decimal(15,6) DEFAULT NULL,
  `MAINTENANCE_MARGIN` decimal(15,2) DEFAULT NULL,
  `PERSISTENT` bit(1) NOT NULL,
  `SECURITY_FK` int(11) NOT NULL,
  `STRATEGY_FK` int(11) NOT NULL,
  `VERSION` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `SECURITY_STRATEGY_UNIQUE` (`SECURITY_FK`,`STRATEGY_FK`),
  KEY `POSITION_SECURITY_FKC` (`SECURITY_FK`),
  KEY `POSITION_STRATEGY_FKC` (`STRATEGY_FK`),
  CONSTRAINT `POSITION_SECURITY_FKC` FOREIGN KEY (`SECURITY_FK`) REFERENCES `security` (`ID`) ON UPDATE CASCADE,
  CONSTRAINT `POSITION_STRATEGY_FKC` FOREIGN KEY (`STRATEGY_FK`) REFERENCES `strategy` (`ID`) ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET=latin1 ROW_FORMAT=Compact;

--
-- Table structure for table `property`
--

CREATE TABLE `property` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `PERSISTENT` bit(1) NOT NULL,
  `INT_VALUE` int(11) DEFAULT NULL,
  `DOUBLE_VALUE` double DEFAULT NULL,
  `MONEY_VALUE` decimal(15,6) DEFAULT NULL,
  `TEXT_VALUE` varchar(255) DEFAULT NULL,
  `DATE_VALUE` datetime DEFAULT NULL,
  `BOOLEAN_VALUE` bit(1) DEFAULT NULL,
  `PROPERTY_HOLDER_FK` int(11) NOT NULL,
  `VERSION` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `NAME_PROPERTY_HOLDER_UNIQUE` (`NAME`,`PROPERTY_HOLDER_FK`)
) ENGINE=InnoDB CHARACTER SET=latin1 ROW_FORMAT=Compact;

--
-- Table structure for table `security`
--

CREATE TABLE `security` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SYMBOL` varchar(30) DEFAULT NULL,
  `ISIN` varchar(20) DEFAULT NULL,
  `BBGID` varchar(12) DEFAULT NULL,
  `RIC` varchar(20) DEFAULT NULL,
  `CONID` varchar(30) DEFAULT NULL,
  `UNDERLYING_FK` int(11) DEFAULT NULL,
  `SECURITY_FAMILY_FK` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `SYMBOL_SECURITY_FAMILY_UNIQUE` (`SYMBOL`,`SECURITY_FAMILY_FK`),
  UNIQUE KEY `ISIN_UNIQUE` (`ISIN`),
  UNIQUE KEY `BBGID_UNIQUE` (`BBGID`),
  UNIQUE KEY `RIC_UNIQUE` (`RIC`),
  UNIQUE KEY `CONID_UNIQUE` (`CONID`),
  KEY `SECURITY_SECURITY_FAMILY_FKC` (`SECURITY_FAMILY_FK`),
  KEY `SECURITY_UNDERLYING_FKC` (`UNDERLYING_FK`),
  CONSTRAINT `SECURITY_SECURITY_FAMILY_FKC` FOREIGN KEY (`SECURITY_FAMILY_FK`) REFERENCES `security_family` (`ID`) ON UPDATE CASCADE,
  CONSTRAINT `SECURITY_UNDERLYING_FKC` FOREIGN KEY (`UNDERLYING_FK`) REFERENCES `security` (`ID`) ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET=latin1 ROW_FORMAT=Compact;

--
-- Table structure for table `security_family`
--

CREATE TABLE `security_family` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(20) NOT NULL,
  `BASE_SYMBOL` varchar(20) DEFAULT NULL,
  `ISIN_ROOT` varchar(20) DEFAULT NULL,
  `RIC_ROOT` varchar(20) DEFAULT NULL,
  `MARKET` varchar(20) NOT NULL,
  `CURRENCY` enum('USD','EUR','CHF','GBP','CAD','JPY','AUD','NZD','HKD','SEK','NOK','BRL','RUB','INR') NOT NULL,
  `TRADING_CLASS` varchar(20) DEFAULT NULL,
  `CONTRACT_SIZE` int(11) NOT NULL,
  `SCALE` int(11) NOT NULL,
  `TICK_SIZE_PATTERN` varchar(100) NOT NULL,
  `EXECUTION_COMMISSION` decimal(5,2) DEFAULT NULL,
  `CLEARING_COMMISSION` decimal(5,2) DEFAULT NULL,
  `FEE` decimal(5,2) DEFAULT NULL,
  `MARKET_OPEN_DAY` enum('SUNDAY','MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY') DEFAULT NULL,
  `MARKET_OPEN` time NOT NULL,
  `MARKET_CLOSE` time NOT NULL,
  `TRADEABLE` bit(1) NOT NULL,
  `SYNTHETIC` bit(1) NOT NULL,
  `SPREAD_SLOPE` double DEFAULT NULL,
  `SPREAD_CONSTANT` double DEFAULT NULL,
  `MAX_SPREAD_SLOPE` double DEFAULT NULL,
  `MAX_SPREAD_CONSTANT` double DEFAULT NULL,
  `PERIODICITY` enum('MIN','HOUR','DAY','MONTH') DEFAULT NULL,
  `MAX_GAP` int(11) DEFAULT NULL,
  `UNDERLYING_FK` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `NAME_UNIQUE` (`NAME`),
  KEY `SECURITY_FAMILY_UNDERLAYING_FKC` (`UNDERLYING_FK`),
  CONSTRAINT `SECURITY_FAMILY_UNDERLAYING_FKC` FOREIGN KEY (`UNDERLYING_FK`) REFERENCES `security` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET=latin1 ROW_FORMAT=Compact;

--
-- Table structure for table `stock`
--

CREATE TABLE `stock` (
  `ID` int(11) NOT NULL,
  `GICS` char(8) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `GICS` (`GICS`),
  KEY `STOCKIFKC` (`ID`),
  CONSTRAINT `STOCKIFKC` FOREIGN KEY (`ID`) REFERENCES `security` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET=latin1 ROW_FORMAT=Compact;

--
-- Table structure for table `strategy`
--

CREATE TABLE `strategy` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(30) NOT NULL,
  `AUTO_ACTIVATE` bit(1) NOT NULL,
  `ALLOCATION` double NOT NULL,
  `INIT_MODULES` varchar(255) DEFAULT NULL,
  `RUN_MODULES` varchar(255) DEFAULT NULL,
  `VERSION` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `NAME_UNIQUE` (`NAME`)
) ENGINE=InnoDB CHARACTER SET=latin1 ROW_FORMAT=Compact;

--
-- Table structure for table `subscription`
--

CREATE TABLE `subscription` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SECURITY_FK` int(11) NOT NULL,
  `STRATEGY_FK` int(11) NOT NULL,
  `FEED_TYPE` enum('IB','BB','DC') NOT NULL,
  `PERSISTENT` bit(1) NOT NULL,
  `VERSION` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `STRATEGY_SECURITY_FEED_TYPE_UNIQUE` (`SECURITY_FK`,`STRATEGY_FK`,`FEED_TYPE`),
  KEY `PERSISTENT` (`PERSISTENT`),
  KEY `SUBSCRIPTION_SECURITY_FKC` (`SECURITY_FK`),
  KEY `SUBSCRIPTION_STRATEGY_FKC` (`STRATEGY_FK`),
  KEY `FEED_TYPE` (`FEED_TYPE`),
  CONSTRAINT `SUBSCRIPTION_SECURITY_FKC` FOREIGN KEY (`SECURITY_FK`) REFERENCES `security` (`ID`) ON UPDATE CASCADE,
  CONSTRAINT `SUBSCRIPTION_STRATEGY_FKC` FOREIGN KEY (`STRATEGY_FK`) REFERENCES `strategy` (`ID`) ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET=latin1 ROW_FORMAT=Compact;

--
-- Table structure for table `tick`
--

CREATE TABLE `tick` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DATE_TIME` datetime NOT NULL,
  `LAST` decimal(13,6) DEFAULT NULL,
  `LAST_DATE_TIME` datetime DEFAULT NULL,
  `VOL` int(11) NOT NULL,
  `VOL_BID` int(11) NOT NULL,
  `VOL_ASK` int(11) NOT NULL,
  `BID` decimal(13,6) DEFAULT NULL,
  `ASK` decimal(13,6) DEFAULT NULL,
  `FEED_TYPE` enum('IB','BB','DC') DEFAULT NULL,
  `SECURITY_FK` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `DATE_TIME_SECURITY_FEED_TYPE_UNIQUE` (`DATE_TIME`,`SECURITY_FK`,`FEED_TYPE`),
  KEY `DATE_TIME` (`DATE_TIME`),
  KEY `SECURITY_FK` (`SECURITY_FK`),
  KEY `FEED_TYPE` (`FEED_TYPE`)
) ENGINE=MyISAM CHARACTER SET=latin1 ROW_FORMAT=Fixed;

--
-- Table structure for table `transaction`
--

CREATE TABLE `transaction` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `EXT_ID` varchar(30) DEFAULT NULL,
  `DATE_TIME` datetime NOT NULL,
  `SETTLEMENT_DATE` datetime DEFAULT NULL,
  `QUANTITY` bigint(20) NOT NULL,
  `PRICE` decimal(15,6) NOT NULL,
  `EXECUTION_COMMISSION` decimal(15,2) DEFAULT NULL,
  `CLEARING_COMMISSION` decimal(15,2) DEFAULT NULL,
  `FEE` decimal(15,2) DEFAULT NULL,
  `CURRENCY` enum('USD','EUR','CHF','GBP','CAD','JPY','AUD','NZD','HKD','SEK','NOK','BRL','RUB','INR') NOT NULL,
  `TYPE` enum('BUY','SELL','EXPIRATION','CREDIT','DEBIT','INTREST_PAID','INTREST_RECEIVED','FEES','REFUND','REBALANCE','TRANSFER','DIVIDEND') NOT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `SECURITY_FK` int(11) DEFAULT NULL,
  `STRATEGY_FK` int(11) NOT NULL,
  `POSITION_FK` int(11) DEFAULT NULL,
  `ACCOUNT_FK` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `EXT_ID_UNIQUE` (`EXT_ID`),
  KEY `DATE_TIME` (`DATE_TIME`),
  KEY `SETTLEMENT_DATE` (`SETTLEMENT_DATE`),
  KEY `CURRENCY` (`CURRENCY`),
  KEY `TRANSACTION_STRATEGY_FKC` (`STRATEGY_FK`),
  KEY `TRANSACTION_POSITION_FKC` (`POSITION_FK`),
  KEY `TRANSACTION_SECURITY_FKC` (`SECURITY_FK`),
  KEY `TRANSACTION_ACCOUNT_FKC` (`ACCOUNT_FK`),
  CONSTRAINT `TRANSACTION_ACCOUNT_FKC` FOREIGN KEY (`ACCOUNT_FK`) REFERENCES `account` (`ID`) ON UPDATE CASCADE,
  CONSTRAINT `TRANSACTION_POSITION_FKC` FOREIGN KEY (`POSITION_FK`) REFERENCES `position` (`ID`) ON UPDATE CASCADE,
  CONSTRAINT `TRANSACTION_SECURITY_FKC` FOREIGN KEY (`SECURITY_FK`) REFERENCES `security` (`ID`) ON UPDATE CASCADE,
  CONSTRAINT `TRANSACTION_STRATEGY_FKC` FOREIGN KEY (`STRATEGY_FK`) REFERENCES `strategy` (`ID`) ON UPDATE CASCADE
) ENGINE=InnoDB CHARACTER SET=latin1 ROW_FORMAT=Compact;

--
-- table data for table `strategy`
--

INSERT INTO `strategy` (`ID`, `NAME`, `AUTO_ACTIVATE`, `ALLOCATION`, `INIT_MODULES`, `RUN_MODULES`, `VERSION`) VALUES (1,'BASE','',0,'market-data,combination,current-values,market-data-simulation,trades,portfolio,performance,algo-slicing,market-data-ib,market-data-dc',NULL,0);
