ALTER TABLE `security` ADD `DESCRIPTION` varchar(100) DEFAULT NULL AFTER `SYMBOL`;

ALTER TABLE `order` ADD `EXCHANGE_FK` bigint(20) DEFAULT NULL AFTER `STRATEGY_FK`;
ALTER TABLE `order` ADD CONSTRAINT `ORDER_EXCHANGE_FKC` FOREIGN KEY ( `EXCHANGE_FK` ) REFERENCES `exchange` ( `ID` ); 

ALTER TABLE `broker_parameters` DROP `EXCHANGE_CODE`;

ALTER TABLE `exchange` MODIFY `CODE` varchar(10) DEFAULT NULL;
ALTER TABLE `exchange` ADD `MIC` varchar(4) DEFAULT NULL AFTER `CODE`;
ALTER TABLE `exchange` ADD `BLOOMBERG_CODE` varchar(3) DEFAULT NULL AFTER `MIC`;
ALTER TABLE `exchange` ADD `IB_CODE` varchar(10) DEFAULT NULL AFTER `BLOOMBERG_CODE`;

