ALTER TABLE `bar` ADD `VWAP` decimal(13,6) DEFAULT NULL AFTER `VOL`;

ALTER TABLE `order_preference` MODIFY `ORDER_TYPE` enum('MARKET','LIMIT','STOP','STOP_LIMIT','SLICING','TICKWISE_INCREMENTAL','VARIABLE_INCREMENTAL','VWAP') NOT NULL;