ALTER TABLE `future` ADD `MONTH_YEAR` char(6) NOT NULL AFTER `EXPIRATION`;

UPDATE `future` SET `MONTH_YEAR` = DATE_FORMAT(`EXPIRATION`, '%Y%m');
UPDATE `future` SET `EXPIRATION` = `LAST_TRADING`;

ALTER TABLE `future` DROP `LAST_TRADING`;