/**
${pojo.getClassJavaDoc(pojo.getDeclarationName() + " generated by hbm2java", 0)}
 */
${pojo.getClassModifiers()} interface ${pojo.getDeclarationName()}I ${pojo.getExtendsDeclaration()?replace("Impl", "I")}