/**
${pojo.getClassJavaDoc(pojo.getDeclarationName() + "Builder generated by hbm2java", 0)} 
 */
${pojo.getClassModifiers()} ${pojo.getDeclarationType()} ${pojo.getDeclarationName()}VOBuilder {

    public static ${pojo.getDeclarationName()}VOBuilder create() {
        return new ${pojo.getDeclarationName()}VOBuilder();
    }
