;             
CREATE USER IF NOT EXISTS SA SALT 'f718438aa7460712' HASH '7b6cd45b4b095988bfd567db92976e19a12979a13eaa6a69741008ba6bb1cb66' ADMIN;           
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_F061B560_82F1_4E09_BE1E_B0EB7135B76B START WITH 52 BELONGS_TO_TABLE;   
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_17AB3B5B_964E_48AA_A379_E7DF271037C3 START WITH 46 BELONGS_TO_TABLE;   
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_107AA803_850C_4AF4_A695_A7A78AF3BDD7 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_6271A79A_E74B_45E7_843B_7B2D354371CA START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_C84AB782_9AB1_4C76_81DE_07DBBCA78C15 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_F9B8C3DB_24DA_4819_9B27_550589948394 START WITH 12 BELONGS_TO_TABLE;   
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_404D4B13_746F_463F_8A8B_05C4E279D569 START WITH 101 BELONGS_TO_TABLE;  
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_DDF81F7F_C71B_435B_8433_9B8164694D5B START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_152A35B8_D087_41A9_94BB_219383CFF9C3 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_3EDDDA7D_B8B7_46E7_A19F_61ABE8A02D9F START WITH 2 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_CCADF464_9BD8_4E54_BE07_64A44B4109D3 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_5016E21B_77B7_42D4_B7C7_19B6D4359FB1 START WITH 4 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_D167E5F4_E07F_4462_9314_234DC43667CC START WITH 2 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_8D55E322_281E_4887_82E3_45E66E08B89C START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_5FF284AA_F4A8_4D61_940B_68A08BA72E51 START WITH 4 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_6AA22681_ECEB_43A0_A88C_6B58BB0FF2E6 START WITH 2 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_05CD34F6_7B09_4838_939F_03CC54623B39 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_A33B73BC_A04C_40FB_B7B6_2E6072C01572 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_DCC551BF_B84B_4162_B836_F00CA10EBC73 START WITH 3 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_82D4BA2E_5F1E_419E_A413_1A466B4848F1 START WITH 3 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_FCB0592A_3CB7_46B8_A957_C424E041581D START WITH 12 BELONGS_TO_TABLE;   
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_4F369FD8_BB0F_4165_948D_13EEA06E21C2 START WITH 109 BELONGS_TO_TABLE;  
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_E3063847_C728_42C7_9B4E_BCFFA10420FF START WITH 167 BELONGS_TO_TABLE;  
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_9F86195B_9119_4F55_AADD_B00E93971A9A START WITH 1 BELONGS_TO_TABLE;    
CREATE CACHED TABLE PUBLIC."account"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_4F369FD8_BB0F_4165_948D_13EEA06E21C2) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_4F369FD8_BB0F_4165_948D_13EEA06E21C2,
    NAME VARCHAR(20) NOT NULL,
    ACTIVE BIT NOT NULL,
    BROKER VARCHAR(100) DEFAULT NULL,
    ORDER_SERVICE_TYPE VARCHAR(100) NOT NULL,
    SESSION_QUALIFIER VARCHAR(10) DEFAULT NULL,
    EXT_ACCOUNT VARCHAR(20) DEFAULT NULL,
    EXT_ACCOUNT_GROUP VARCHAR(20) DEFAULT NULL,
    EXT_ALLOCATION_PROFILE VARCHAR(20) DEFAULT NULL,
    EXT_CLEARING_ACCOUNT VARCHAR(20) DEFAULT NULL
);               
ALTER TABLE PUBLIC."account" ADD CONSTRAINT PUBLIC.CONSTRAINT_B PRIMARY KEY(ID);              
CREATE INDEX PUBLIC.INDEX_B ON PUBLIC."account"(ACTIVE);
CREATE INDEX PUBLIC.INDEX_B9 ON PUBLIC."account"(BROKER);     
CREATE INDEX PUBLIC.INDEX_B9D ON PUBLIC."account"(ORDER_SERVICE_TYPE);        
CREATE CACHED TABLE PUBLIC."allocation"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_C84AB782_9AB1_4C76_81DE_07DBBCA78C15) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_C84AB782_9AB1_4C76_81DE_07DBBCA78C15,
    VALUE DOUBLE NOT NULL,
    ORDER_PREFERENCE_FK INT NOT NULL,
    ACCOUNT_FK INT NOT NULL
);  
ALTER TABLE PUBLIC."allocation" ADD CONSTRAINT PUBLIC.CONSTRAINT_8 PRIMARY KEY(ID);           
CREATE INDEX PUBLIC.INDEX_8 ON PUBLIC."allocation"(ACCOUNT_FK);
CREATE INDEX PUBLIC.INDEX_8E ON PUBLIC."allocation"(ORDER_PREFERENCE_FK);     
CREATE CACHED TABLE PUBLIC."bar"(
    ID INT NOT NULL,
    DATE_TIME DATETIME NOT NULL,
    OPEN DECIMAL(13, 6) NOT NULL,
    HIGH DECIMAL(13, 6) NOT NULL,
    LOW DECIMAL(13, 6) NOT NULL,
    CLOSE DECIMAL(13, 6) NOT NULL,
    VOL INT NOT NULL,
    BAR_SIZE VARCHAR(100) NOT NULL,
    FEED_TYPE VARCHAR(100) DEFAULT NULL,
    SECURITY_FK INT NOT NULL
); 
ALTER TABLE PUBLIC."bar" ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID);  
CREATE INDEX PUBLIC.INDEX_1 ON PUBLIC."bar"(DATE_TIME);
CREATE INDEX PUBLIC.INDEX_17 ON PUBLIC."bar"(SECURITY_FK);    
CREATE INDEX PUBLIC.INDEX_17C ON PUBLIC."bar"(BAR_SIZE);      
CREATE CACHED TABLE PUBLIC."bond"(
    ID INT NOT NULL,
    MATURITY DATE NOT NULL,
    COUPON DOUBLE NOT NULL
);         
ALTER TABLE PUBLIC."bond" ADD CONSTRAINT PUBLIC.CONSTRAINT_2 PRIMARY KEY(ID); 
CREATE INDEX PUBLIC.INDEX_2 ON PUBLIC."bond"(MATURITY);
CREATE INDEX PUBLIC.INDEX_2E ON PUBLIC."bond"(ID);            
CREATE CACHED TABLE PUBLIC."bond_family"(
    ID INT NOT NULL,
    MATURITY_DISTANCE VARCHAR(100) NOT NULL,
    LENGTH INT NOT NULL,
    QUOTATION_STYLE VARCHAR(100) NOT NULL
);        
ALTER TABLE PUBLIC."bond_family" ADD CONSTRAINT PUBLIC.CONSTRAINT_89 PRIMARY KEY(ID);         
CREATE INDEX PUBLIC.INDEX_89 ON PUBLIC."bond_family"(ID);
CREATE CACHED TABLE PUBLIC."broker_parameters"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_DCC551BF_B84B_4162_B836_F00CA10EBC73) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_DCC551BF_B84B_4162_B836_F00CA10EBC73,
    BROKER VARCHAR(100) NOT NULL,
    SYMBOL_ROOT VARCHAR(20) DEFAULT NULL,
    EXCHANGE_CODE VARCHAR(20) DEFAULT NULL,
    EXECUTION_COMMISSION DECIMAL(5, 2) DEFAULT NULL,
    CLEARING_COMMISSION DECIMAL(5, 2) DEFAULT NULL,
    FEE DECIMAL(5, 2) DEFAULT NULL,
    SECURITY_FAMILY_FK INT NOT NULL
);           
ALTER TABLE PUBLIC."broker_parameters" ADD CONSTRAINT PUBLIC.CONSTRAINT_9 PRIMARY KEY(ID);    
CREATE INDEX PUBLIC.INDEX_9 ON PUBLIC."broker_parameters"(SECURITY_FAMILY_FK);
CREATE CACHED TABLE PUBLIC."cash_balance"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_3EDDDA7D_B8B7_46E7_A19F_61ABE8A02D9F) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_3EDDDA7D_B8B7_46E7_A19F_61ABE8A02D9F,
    CURRENCY VARCHAR(100) NOT NULL,
    AMOUNT DECIMAL(15, 2) NOT NULL,
    STRATEGY_FK INT NOT NULL,
    VERSION INT NOT NULL
);             
ALTER TABLE PUBLIC."cash_balance" ADD CONSTRAINT PUBLIC.CONSTRAINT_D PRIMARY KEY(ID);         
CREATE INDEX PUBLIC.INDEX_D ON PUBLIC."cash_balance"(STRATEGY_FK);
CREATE CACHED TABLE PUBLIC."combination"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_05CD34F6_7B09_4838_939F_03CC54623B39) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_05CD34F6_7B09_4838_939F_03CC54623B39,
    UUID CHAR(36) NOT NULL,
    TYPE VARCHAR(100) NOT NULL,
    PERSISTENT BIT NOT NULL
);      
ALTER TABLE PUBLIC."combination" ADD CONSTRAINT PUBLIC.CONSTRAINT_D9 PRIMARY KEY(ID);         
CREATE INDEX PUBLIC.INDEX_D9 ON PUBLIC."combination"(ID);
CREATE CACHED TABLE PUBLIC."commodity"(
    ID INT NOT NULL,
    TYPE VARCHAR(100) NOT NULL
);             
ALTER TABLE PUBLIC."commodity" ADD CONSTRAINT PUBLIC.CONSTRAINT_A PRIMARY KEY(ID);            
CREATE INDEX PUBLIC.INDEX_A ON PUBLIC."commodity"(ID);
CREATE CACHED TABLE PUBLIC."component"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_A33B73BC_A04C_40FB_B7B6_2E6072C01572) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_A33B73BC_A04C_40FB_B7B6_2E6072C01572,
    QUANTITY BIGINT NOT NULL,
    PERSISTENT BIT NOT NULL,
    SECURITY_FK INT NOT NULL,
    COMBINATION_FK INT NOT NULL,
    VERSION INT NOT NULL
);           
ALTER TABLE PUBLIC."component" ADD CONSTRAINT PUBLIC.CONSTRAINT_AC PRIMARY KEY(ID);           
CREATE INDEX PUBLIC.INDEX_AC ON PUBLIC."component"(COMBINATION_FK);
CREATE INDEX PUBLIC.INDEX_AC8 ON PUBLIC."component"(SECURITY_FK);             
CREATE CACHED TABLE PUBLIC."default_order_preference"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_82D4BA2E_5F1E_419E_A413_1A466B4848F1) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_82D4BA2E_5F1E_419E_A413_1A466B4848F1,
    ORDER_PREFERENCE_FK INT NOT NULL,
    STRATEGY_FK INT NOT NULL,
    SECURITY_FAMILY_FK INT NOT NULL
);         
ALTER TABLE PUBLIC."default_order_preference" ADD CONSTRAINT PUBLIC.CONSTRAINT_3 PRIMARY KEY(ID);             
CREATE INDEX PUBLIC.INDEX_3 ON PUBLIC."default_order_preference"(ORDER_PREFERENCE_FK);
CREATE INDEX PUBLIC.INDEX_34 ON PUBLIC."default_order_preference"(SECURITY_FAMILY_FK);        
CREATE INDEX PUBLIC.INDEX_34A ON PUBLIC."default_order_preference"(STRATEGY_FK);              
CREATE CACHED TABLE PUBLIC."easy_to_borrow"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_152A35B8_D087_41A9_94BB_219383CFF9C3) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_152A35B8_D087_41A9_94BB_219383CFF9C3,
    DATE DATE NOT NULL,
    BROKER VARCHAR(100) NOT NULL,
    QUANTITY BIGINT NOT NULL,
    STOCK_FK INT NOT NULL
);        
ALTER TABLE PUBLIC."easy_to_borrow" ADD CONSTRAINT PUBLIC.CONSTRAINT_80 PRIMARY KEY(ID);      
CREATE INDEX PUBLIC.INDEX_80 ON PUBLIC."easy_to_borrow"(STOCK_FK);
CREATE CACHED TABLE PUBLIC."exchange"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_F9B8C3DB_24DA_4819_9B27_550589948394) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_F9B8C3DB_24DA_4819_9B27_550589948394,
    NAME VARCHAR(50) NOT NULL,
    CODE VARCHAR(10) NOT NULL,
    TIME_ZONE VARCHAR(50) DEFAULT NULL
);            
ALTER TABLE PUBLIC."exchange" ADD CONSTRAINT PUBLIC.CONSTRAINT_7 PRIMARY KEY(ID);             
CREATE CACHED TABLE PUBLIC."forex"(
    ID INT NOT NULL,
    BASE_CURRENCY VARCHAR(100) NOT NULL
);        
ALTER TABLE PUBLIC."forex" ADD CONSTRAINT PUBLIC.CONSTRAINT_5 PRIMARY KEY(ID);
CREATE INDEX PUBLIC.INDEX_5 ON PUBLIC."forex"(ID);
CREATE CACHED TABLE PUBLIC."fund"(
    ID INT NOT NULL
);   
ALTER TABLE PUBLIC."fund" ADD CONSTRAINT PUBLIC.CONSTRAINT_30 PRIMARY KEY(ID);
CREATE INDEX PUBLIC.INDEX_30 ON PUBLIC."fund"(ID);
CREATE CACHED TABLE PUBLIC."future"(
    ID INT NOT NULL,
    EXPIRATION DATE NOT NULL,
    FIRST_NOTICE DATE DEFAULT NULL,
    LAST_TRADING DATE DEFAULT NULL
);        
ALTER TABLE PUBLIC."future" ADD CONSTRAINT PUBLIC.CONSTRAINT_B4 PRIMARY KEY(ID);              
CREATE INDEX PUBLIC.INDEX_B4 ON PUBLIC."future"(EXPIRATION);
CREATE INDEX PUBLIC.INDEX_B4B ON PUBLIC."future"(FIRST_NOTICE);               
CREATE INDEX PUBLIC.INDEX_B4B5 ON PUBLIC."future"(LAST_TRADING);              
CREATE INDEX PUBLIC.INDEX_B4B58 ON PUBLIC."future"(ID);       
CREATE CACHED TABLE PUBLIC."future_family"(
    ID INT NOT NULL,
    INTREST DOUBLE NOT NULL,
    DIVIDEND DOUBLE NOT NULL,
    MARGIN_PARAMETER DOUBLE NOT NULL,
    EXPIRATION_TYPE VARCHAR(100) NOT NULL,
    EXPIRATION_DISTANCE VARCHAR(100) NOT NULL,
    LENGTH INT NOT NULL
);
ALTER TABLE PUBLIC."future_family" ADD CONSTRAINT PUBLIC.CONSTRAINT_E PRIMARY KEY(ID);        
CREATE INDEX PUBLIC.INDEX_E ON PUBLIC."future_family"(ID);
CREATE CACHED TABLE PUBLIC."generic_future"(
    ID INT NOT NULL,
    DURATION VARCHAR(100) NOT NULL,
    ASSET_CLASS VARCHAR(100) NOT NULL
);            
ALTER TABLE PUBLIC."generic_future" ADD CONSTRAINT PUBLIC.CONSTRAINT_21 PRIMARY KEY(ID);      
CREATE INDEX PUBLIC.INDEX_21 ON PUBLIC."generic_future"(DURATION);
CREATE INDEX PUBLIC.INDEX_217 ON PUBLIC."generic_future"(ID); 
CREATE CACHED TABLE PUBLIC."generic_future_family"(
    ID INT NOT NULL,
    EXPIRATION_TYPE VARCHAR(100) NOT NULL,
    EXPIRATION_DISTANCE VARCHAR(100) DEFAULT NULL
);  
ALTER TABLE PUBLIC."generic_future_family" ADD CONSTRAINT PUBLIC.CONSTRAINT_6 PRIMARY KEY(ID);
CREATE INDEX PUBLIC.INDEX_6 ON PUBLIC."generic_future_family"(ID);
CREATE CACHED TABLE PUBLIC."generic_tick"(
    ID INT NOT NULL,
    DATE_TIME DATETIME NOT NULL,
    FEED_TYPE VARCHAR(100) NOT NULL,
    SECURITY_FK INT NOT NULL,
    TICK_TYPE VARCHAR(100) NOT NULL,
    MONEY_VALUE DECIMAL(13, 6) DEFAULT NULL,
    DOUBLE_VALUE DOUBLE DEFAULT NULL,
    INT_VALUE INT DEFAULT NULL
);        
ALTER TABLE PUBLIC."generic_tick" ADD CONSTRAINT PUBLIC.CONSTRAINT_F PRIMARY KEY(ID);         
CREATE INDEX PUBLIC.INDEX_F ON PUBLIC."generic_tick"(SECURITY_FK);
CREATE CACHED TABLE PUBLIC."holiday"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_5FF284AA_F4A8_4D61_940B_68A08BA72E51) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_5FF284AA_F4A8_4D61_940B_68A08BA72E51,
    DATE DATE NOT NULL,
    LATE_OPEN TIME DEFAULT NULL,
    EARLY_CLOSE TIME DEFAULT NULL,
    EXCHANGE_FK INT NOT NULL
);        
ALTER TABLE PUBLIC."holiday" ADD CONSTRAINT PUBLIC.CONSTRAINT_4 PRIMARY KEY(ID);              
CREATE INDEX PUBLIC.INDEX_4 ON PUBLIC."holiday"(EXCHANGE_FK);
CREATE CACHED TABLE PUBLIC."implied_volatility"(
    ID INT NOT NULL,
    DURATION VARCHAR(100) NOT NULL,
    MONEYNESS DOUBLE DEFAULT NULL,
    DELTA DOUBLE DEFAULT NULL,
    TYPE VARCHAR(100) NOT NULL
);           
ALTER TABLE PUBLIC."implied_volatility" ADD CONSTRAINT PUBLIC.CONSTRAINT_1E PRIMARY KEY(ID);  
CREATE INDEX PUBLIC.INDEX_1E ON PUBLIC."implied_volatility"(ID);
CREATE CACHED TABLE PUBLIC."index"(
    ID INT NOT NULL,
    ASSET_CLASS VARCHAR(100) NOT NULL
);          
ALTER TABLE PUBLIC."index" ADD CONSTRAINT PUBLIC.CONSTRAINT_5F PRIMARY KEY(ID);               
CREATE INDEX PUBLIC.INDEX_5F ON PUBLIC."index"(ID);
CREATE CACHED TABLE PUBLIC."intrest_rate"(
    ID INT NOT NULL,
    DURATION VARCHAR(100) NOT NULL
);      
ALTER TABLE PUBLIC."intrest_rate" ADD CONSTRAINT PUBLIC.CONSTRAINT_64 PRIMARY KEY(ID);        
CREATE INDEX PUBLIC.INDEX_64 ON PUBLIC."intrest_rate"(ID);
CREATE CACHED TABLE PUBLIC."measurement"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_6271A79A_E74B_45E7_843B_7B2D354371CA) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_6271A79A_E74B_45E7_843B_7B2D354371CA,
    NAME VARCHAR(255) NOT NULL,
    DATE_TIME DATETIME NOT NULL,
    INT_VALUE INT DEFAULT NULL,
    DOUBLE_VALUE DOUBLE DEFAULT NULL,
    MONEY_VALUE DECIMAL(15, 6) DEFAULT NULL,
    TEXT_VALUE VARCHAR(50) DEFAULT NULL,
    BOOLEAN_VALUE BIT DEFAULT NULL,
    STRATEGY_FK INT NOT NULL
);           
ALTER TABLE PUBLIC."measurement" ADD CONSTRAINT PUBLIC.CONSTRAINT_93 PRIMARY KEY(ID);         
CREATE INDEX PUBLIC.INDEX_93 ON PUBLIC."measurement"(STRATEGY_FK);
CREATE CACHED TABLE PUBLIC."option"(
    ID INT NOT NULL,
    STRIKE DECIMAL(12, 5) NOT NULL,
    EXPIRATION DATE NOT NULL,
    TYPE VARCHAR(100) NOT NULL
);            
ALTER TABLE PUBLIC."option" ADD CONSTRAINT PUBLIC.CONSTRAINT_C PRIMARY KEY(ID);               
CREATE INDEX PUBLIC.INDEX_C ON PUBLIC."option"(EXPIRATION);
CREATE INDEX PUBLIC.INDEX_C3 ON PUBLIC."option"(STRIKE);      
CREATE INDEX PUBLIC.INDEX_C3C ON PUBLIC."option"(TYPE);       
CREATE INDEX PUBLIC.INDEX_C3CA ON PUBLIC."option"(ID);        
CREATE CACHED TABLE PUBLIC."option_family"(
    ID INT NOT NULL,
    INTREST DOUBLE NOT NULL,
    DIVIDEND DOUBLE NOT NULL,
    MARGIN_PARAMETER DOUBLE NOT NULL,
    EXPIRATION_TYPE VARCHAR(100) NOT NULL,
    EXPIRATION_DISTANCE VARCHAR(100) NOT NULL,
    STRIKE_DISTANCE DOUBLE NOT NULL,
    WEEKLY BIT NOT NULL
);          
ALTER TABLE PUBLIC."option_family" ADD CONSTRAINT PUBLIC.CONSTRAINT_B3 PRIMARY KEY(ID);       
CREATE INDEX PUBLIC.INDEX_B3 ON PUBLIC."option_family"(ID);
CREATE CACHED TABLE PUBLIC."order"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_9F86195B_9119_4F55_AADD_B00E93971A9A) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_9F86195B_9119_4F55_AADD_B00E93971A9A,
    CLASS VARCHAR(255) NOT NULL,
    INT_ID VARCHAR(30) NOT NULL,
    EXT_ID VARCHAR(30) DEFAULT NULL,
    DATE_TIME DATETIME NOT NULL,
    SIDE VARCHAR(100) NOT NULL,
    QUANTITY BIGINT NOT NULL,
    TIF VARCHAR(100) NOT NULL,
    TIF_DATE_TIME DATETIME DEFAULT NULL,
    "LIMIT" DECIMAL(15, 6) DEFAULT NULL,
    STOP DECIMAL(15, 6) DEFAULT NULL,
    ACCOUNT_FK INT NOT NULL,
    SECURITY_FK INT NOT NULL,
    STRATEGY_FK INT NOT NULL
);     
ALTER TABLE PUBLIC."order" ADD CONSTRAINT PUBLIC.CONSTRAINT_65 PRIMARY KEY(ID);               
CREATE INDEX PUBLIC.INDEX_65 ON PUBLIC."order"(SECURITY_FK);
CREATE INDEX PUBLIC.INDEX_651 ON PUBLIC."order"(ACCOUNT_FK);  
CREATE INDEX PUBLIC.INDEX_6518 ON PUBLIC."order"(STRATEGY_FK);
CREATE CACHED TABLE PUBLIC."order_preference"(
    ID INT NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    ORDER_TYPE VARCHAR(100) NOT NULL,
    DEFAULT_ACCOUNT_FK INT DEFAULT NULL,
    VERSION INT NOT NULL
);           
ALTER TABLE PUBLIC."order_preference" ADD CONSTRAINT PUBLIC.CONSTRAINT_7D PRIMARY KEY(ID);    
CREATE INDEX PUBLIC.INDEX_7 ON PUBLIC."order_preference"(DEFAULT_ACCOUNT_FK);
CREATE CACHED TABLE PUBLIC."order_property"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_107AA803_850C_4AF4_A695_A7A78AF3BDD7) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_107AA803_850C_4AF4_A695_A7A78AF3BDD7,
    NAME VARCHAR(30) NOT NULL,
    VALUE VARCHAR(30) NOT NULL,
    TYPE VARCHAR(100) NOT NULL,
    ORDER_FK INT DEFAULT NULL
);             
ALTER TABLE PUBLIC."order_property" ADD CONSTRAINT PUBLIC.CONSTRAINT_78 PRIMARY KEY(ID);      
CREATE INDEX PUBLIC.INDEX_78 ON PUBLIC."order_property"(ORDER_FK);
CREATE CACHED TABLE PUBLIC."order_status"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_DDF81F7F_C71B_435B_8433_9B8164694D5B) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_DDF81F7F_C71B_435B_8433_9B8164694D5B,
    DATE_TIME DATETIME NOT NULL,
    EXT_DATE_TIME DATETIME NOT NULL,
    STATUS VARCHAR(100) NOT NULL,
    FILLED_QUANTITY BIGINT NOT NULL,
    REMAINING_QUANTITY BIGINT NOT NULL,
    AVG_PRICE DECIMAL(15, 6) DEFAULT NULL,
    LAST_PRICE DECIMAL(15, 6) DEFAULT NULL,
    INT_ID VARCHAR(30) DEFAULT NULL,
    EXT_ID VARCHAR(30) DEFAULT NULL,
    SEQUENCE_NUMBER BIGINT DEFAULT NULL,
    REASON VARCHAR(255) DEFAULT NULL,
    ORDER_FK INT NOT NULL
);     
ALTER TABLE PUBLIC."order_status" ADD CONSTRAINT PUBLIC.CONSTRAINT_3E PRIMARY KEY(ID);        
CREATE INDEX PUBLIC.INDEX_3E ON PUBLIC."order_status"(ORDER_FK);
CREATE CACHED TABLE PUBLIC."portfolio_value"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_8D55E322_281E_4887_82E3_45E66E08B89C) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_8D55E322_281E_4887_82E3_45E66E08B89C,
    DATE_TIME DATETIME NOT NULL,
    SECURITIES_CURRENT_VALUE DECIMAL(15, 6) NOT NULL,
    CASH_BALANCE DECIMAL(15, 6) NOT NULL,
    MAINTENANCE_MARGIN DECIMAL(15, 6) DEFAULT NULL,
    NET_LIQ_VALUE DECIMAL(15, 6) NOT NULL,
    LEVERAGE DOUBLE NOT NULL,
    ALLOCATION DOUBLE NOT NULL,
    CASH_FLOW DECIMAL(15, 6) DEFAULT NULL,
    STRATEGY_FK INT NOT NULL
);              
ALTER TABLE PUBLIC."portfolio_value" ADD CONSTRAINT PUBLIC.CONSTRAINT_F1 PRIMARY KEY(ID);     
CREATE INDEX PUBLIC.INDEX_F1 ON PUBLIC."portfolio_value"(STRATEGY_FK);
CREATE CACHED TABLE PUBLIC."position"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_CCADF464_9BD8_4E54_BE07_64A44B4109D3) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_CCADF464_9BD8_4E54_BE07_64A44B4109D3,
    QUANTITY BIGINT NOT NULL,
    COST DOUBLE NOT NULL,
    REALIZED_P_L DOUBLE DEFAULT NULL,
    EXIT_VALUE DECIMAL(15, 6) DEFAULT NULL,
    MAINTENANCE_MARGIN DECIMAL(15, 2) DEFAULT NULL,
    PERSISTENT BIT NOT NULL,
    SECURITY_FK INT NOT NULL,
    STRATEGY_FK INT NOT NULL,
    VERSION INT DEFAULT '0' NOT NULL
);               
ALTER TABLE PUBLIC."position" ADD CONSTRAINT PUBLIC.CONSTRAINT_2C PRIMARY KEY(ID);            
CREATE INDEX PUBLIC.INDEX_2C ON PUBLIC."position"(SECURITY_FK);
CREATE INDEX PUBLIC.INDEX_2C9 ON PUBLIC."position"(STRATEGY_FK);              
CREATE CACHED TABLE PUBLIC."property"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_F061B560_82F1_4E09_BE1E_B0EB7135B76B) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_F061B560_82F1_4E09_BE1E_B0EB7135B76B,
    NAME VARCHAR(255) NOT NULL,
    PERSISTENT BIT NOT NULL,
    INT_VALUE INT DEFAULT NULL,
    DOUBLE_VALUE DOUBLE DEFAULT NULL,
    MONEY_VALUE DECIMAL(15, 6) DEFAULT NULL,
    TEXT_VALUE VARCHAR(255) DEFAULT NULL,
    DATE_TIME_VALUE DATETIME DEFAULT NULL,
    BOOLEAN_VALUE BIT DEFAULT NULL,
    PROPERTY_HOLDER_FK INT NOT NULL,
    VERSION INT NOT NULL
);   
ALTER TABLE PUBLIC."property" ADD CONSTRAINT PUBLIC.CONSTRAINT_C4 PRIMARY KEY(ID);            
CREATE CACHED TABLE PUBLIC."security"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_E3063847_C728_42C7_9B4E_BCFFA10420FF) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_E3063847_C728_42C7_9B4E_BCFFA10420FF,
    SYMBOL VARCHAR(30) DEFAULT NULL,
    ISIN VARCHAR(20) DEFAULT NULL,
    BBGID VARCHAR(12) DEFAULT NULL,
    RIC VARCHAR(20) DEFAULT NULL,
    CONID VARCHAR(30) DEFAULT NULL,
    LMAXID VARCHAR(30) DEFAULT NULL,
    UNDERLYING_FK INT DEFAULT NULL,
    SECURITY_FAMILY_FK INT NOT NULL
);             
ALTER TABLE PUBLIC."security" ADD CONSTRAINT PUBLIC.CONSTRAINT_38 PRIMARY KEY(ID);            
CREATE INDEX PUBLIC.INDEX_38 ON PUBLIC."security"(SECURITY_FAMILY_FK);
CREATE INDEX PUBLIC.INDEX_389 ON PUBLIC."security"(UNDERLYING_FK);            
CREATE CACHED TABLE PUBLIC."security_family"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_17AB3B5B_964E_48AA_A379_E7DF271037C3) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_17AB3B5B_964E_48AA_A379_E7DF271037C3,
    NAME VARCHAR(20) NOT NULL,
    SYMBOL_ROOT VARCHAR(20) DEFAULT NULL,
    ISIN_ROOT VARCHAR(20) DEFAULT NULL,
    RIC_ROOT VARCHAR(20) DEFAULT NULL,
    CURRENCY VARCHAR(100) NOT NULL,
    TRADING_CLASS VARCHAR(20) DEFAULT NULL,
    CONTRACT_SIZE DOUBLE NOT NULL,
    SCALE INT NOT NULL,
    TICK_SIZE_PATTERN VARCHAR(100) NOT NULL,
    EXECUTION_COMMISSION DECIMAL(5, 2) DEFAULT NULL,
    CLEARING_COMMISSION DECIMAL(5, 2) DEFAULT NULL,
    FEE DECIMAL(5, 2) DEFAULT NULL,
    TRADEABLE BIT NOT NULL,
    SYNTHETIC BIT NOT NULL,
    PERIODICITY VARCHAR(100) DEFAULT NULL,
    MAX_GAP INT DEFAULT NULL,
    UNDERLYING_FK INT DEFAULT NULL,
    EXCHANGE_FK INT DEFAULT NULL
);        
ALTER TABLE PUBLIC."security_family" ADD CONSTRAINT PUBLIC.CONSTRAINT_58 PRIMARY KEY(ID);     
CREATE INDEX PUBLIC.INDEX_58 ON PUBLIC."security_family"(UNDERLYING_FK);
CREATE INDEX PUBLIC.INDEX_585 ON PUBLIC."security_family"(EXCHANGE_FK);       
CREATE CACHED TABLE PUBLIC."stock"(
    ID INT NOT NULL,
    GICS CHAR(8) DEFAULT NULL
);  
ALTER TABLE PUBLIC."stock" ADD CONSTRAINT PUBLIC.CONSTRAINT_68 PRIMARY KEY(ID);               
CREATE INDEX PUBLIC.INDEX_68 ON PUBLIC."stock"(GICS);
CREATE INDEX PUBLIC.INDEX_68A ON PUBLIC."stock"(ID);          
CREATE CACHED TABLE PUBLIC."strategy"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_6AA22681_ECEB_43A0_A88C_6B58BB0FF2E6) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_6AA22681_ECEB_43A0_A88C_6B58BB0FF2E6,
    NAME VARCHAR(30) NOT NULL,
    AUTO_ACTIVATE BIT NOT NULL,
    ALLOCATION DOUBLE NOT NULL,
    INIT_MODULES VARCHAR(255) DEFAULT NULL,
    RUN_MODULES VARCHAR(255) DEFAULT NULL,
    VERSION INT DEFAULT '0' NOT NULL
);   
ALTER TABLE PUBLIC."strategy" ADD CONSTRAINT PUBLIC.CONSTRAINT_6A PRIMARY KEY(ID);            
CREATE CACHED TABLE PUBLIC."subscription"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_404D4B13_746F_463F_8A8B_05C4E279D569) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_404D4B13_746F_463F_8A8B_05C4E279D569,
    SECURITY_FK INT NOT NULL,
    STRATEGY_FK INT NOT NULL,
    FEED_TYPE VARCHAR(100) NOT NULL,
    PERSISTENT BIT NOT NULL,
    VERSION INT NOT NULL
);    
ALTER TABLE PUBLIC."subscription" ADD CONSTRAINT PUBLIC.CONSTRAINT_14 PRIMARY KEY(ID);        
CREATE INDEX PUBLIC.INDEX_14 ON PUBLIC."subscription"(PERSISTENT);
CREATE INDEX PUBLIC.INDEX_145 ON PUBLIC."subscription"(SECURITY_FK);          
CREATE INDEX PUBLIC.INDEX_1456 ON PUBLIC."subscription"(STRATEGY_FK);         
CREATE INDEX PUBLIC.INDEX_14565 ON PUBLIC."subscription"(FEED_TYPE);          
CREATE CACHED TABLE PUBLIC."tick"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_5016E21B_77B7_42D4_B7C7_19B6D4359FB1) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_5016E21B_77B7_42D4_B7C7_19B6D4359FB1,
    DATE_TIME DATETIME NOT NULL,
    LAST DECIMAL(13, 6) DEFAULT NULL,
    LAST_DATE_TIME DATETIME DEFAULT NULL,
    VOL INT NOT NULL,
    VOL_BID INT NOT NULL,
    VOL_ASK INT NOT NULL,
    BID DECIMAL(13, 6) DEFAULT NULL,
    ASK DECIMAL(13, 6) DEFAULT NULL,
    FEED_TYPE VARCHAR(100) DEFAULT NULL,
    SECURITY_FK INT NOT NULL
);   
ALTER TABLE PUBLIC."tick" ADD CONSTRAINT PUBLIC.CONSTRAINT_36 PRIMARY KEY(ID);
CREATE INDEX PUBLIC.INDEX_36 ON PUBLIC."tick"(DATE_TIME);
CREATE INDEX PUBLIC.INDEX_365 ON PUBLIC."tick"(SECURITY_FK);  
CREATE INDEX PUBLIC.INDEX_3651 ON PUBLIC."tick"(FEED_TYPE);   
CREATE INDEX PUBLIC.INDEX_36519 ON PUBLIC."tick"(SECURITY_FK);
CREATE CACHED TABLE PUBLIC."trading_hours"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_FCB0592A_3CB7_46B8_A957_C424E041581D) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_FCB0592A_3CB7_46B8_A957_C424E041581D,
    OPEN TIME NOT NULL,
    CLOSE TIME NOT NULL,
    SUNDAY BIT NOT NULL,
    MONDAY BIT NOT NULL,
    TUESDAY BIT NOT NULL,
    WEDNESDAY BIT NOT NULL,
    THURSDAY BIT NOT NULL,
    FRIDAY BIT NOT NULL,
    SATURDAY BIT NOT NULL,
    EXCHANGE_FK INT NOT NULL
);
ALTER TABLE PUBLIC."trading_hours" ADD CONSTRAINT PUBLIC.CONSTRAINT_BB PRIMARY KEY(ID);       
CREATE INDEX PUBLIC.INDEX_BB ON PUBLIC."trading_hours"(EXCHANGE_FK);
CREATE CACHED TABLE PUBLIC."transaction"(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_D167E5F4_E07F_4462_9314_234DC43667CC) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_D167E5F4_E07F_4462_9314_234DC43667CC,
    EXT_ID VARCHAR(30) DEFAULT NULL,
    INT_ORDER_ID VARCHAR(30) DEFAULT NULL,
    EXT_ORDER_ID VARCHAR(30) DEFAULT NULL,
    DATE_TIME DATETIME NOT NULL,
    SETTLEMENT_DATE DATE DEFAULT NULL,
    QUANTITY BIGINT NOT NULL,
    PRICE DECIMAL(15, 6) NOT NULL,
    EXECUTION_COMMISSION DECIMAL(15, 2) DEFAULT NULL,
    CLEARING_COMMISSION DECIMAL(15, 2) DEFAULT NULL,
    FEE DECIMAL(15, 2) DEFAULT NULL,
    CURRENCY VARCHAR(100) NOT NULL,
    TYPE VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(255) DEFAULT NULL,
    SECURITY_FK INT DEFAULT NULL,
    STRATEGY_FK INT NOT NULL,
    POSITION_FK INT DEFAULT NULL,
    ACCOUNT_FK INT DEFAULT NULL
);           
ALTER TABLE PUBLIC."transaction" ADD CONSTRAINT PUBLIC.CONSTRAINT_7F PRIMARY KEY(ID);         
CREATE INDEX PUBLIC.INDEX_7F ON PUBLIC."transaction"(DATE_TIME);
CREATE INDEX PUBLIC.INDEX_7FA ON PUBLIC."transaction"(SETTLEMENT_DATE);       
CREATE INDEX PUBLIC.INDEX_7FA0 ON PUBLIC."transaction"(CURRENCY);             
CREATE INDEX PUBLIC.INDEX_7FA0D ON PUBLIC."transaction"(STRATEGY_FK);         
CREATE INDEX PUBLIC.INDEX_7FA0D2 ON PUBLIC."transaction"(POSITION_FK);        
CREATE INDEX PUBLIC.INDEX_7FA0D2D ON PUBLIC."transaction"(SECURITY_FK);       
CREATE INDEX PUBLIC.INDEX_7FA0D2DE_0 ON PUBLIC."transaction"(ACCOUNT_FK);     
ALTER TABLE PUBLIC."security" ADD CONSTRAINT PUBLIC.CONSTRAINT_38927 UNIQUE(BBGID);           
ALTER TABLE PUBLIC."allocation" ADD CONSTRAINT PUBLIC.CONSTRAINT_8E UNIQUE(ORDER_PREFERENCE_FK, ACCOUNT_FK);  
ALTER TABLE PUBLIC."broker_parameters" ADD CONSTRAINT PUBLIC.CONSTRAINT_94 UNIQUE(BROKER, SECURITY_FAMILY_FK);
ALTER TABLE PUBLIC."strategy" ADD CONSTRAINT PUBLIC.CONSTRAINT_6A8 UNIQUE(NAME);              
ALTER TABLE PUBLIC."exchange" ADD CONSTRAINT PUBLIC.CONSTRAINT_76 UNIQUE(NAME);               
ALTER TABLE PUBLIC."security" ADD CONSTRAINT PUBLIC.CONSTRAINT_3892 UNIQUE(ISIN);             
ALTER TABLE PUBLIC."bar" ADD CONSTRAINT PUBLIC.CONSTRAINT_17 UNIQUE(DATE_TIME, SECURITY_FK, BAR_SIZE);        
ALTER TABLE PUBLIC."security" ADD CONSTRAINT PUBLIC.CONSTRAINT_389 UNIQUE(SYMBOL, SECURITY_FAMILY_FK);        
ALTER TABLE PUBLIC."subscription" ADD CONSTRAINT PUBLIC.CONSTRAINT_145 UNIQUE(SECURITY_FK, STRATEGY_FK, FEED_TYPE);           
ALTER TABLE PUBLIC."account" ADD CONSTRAINT PUBLIC.CONSTRAINT_B9 UNIQUE(NAME);
ALTER TABLE PUBLIC."measurement" ADD CONSTRAINT PUBLIC.CONSTRAINT_93F UNIQUE(DATE_TIME, NAME, STRATEGY_FK);   
ALTER TABLE PUBLIC."component" ADD CONSTRAINT PUBLIC.CONSTRAINT_AC8 UNIQUE(SECURITY_FK, COMBINATION_FK);      
ALTER TABLE PUBLIC."easy_to_borrow" ADD CONSTRAINT PUBLIC.CONSTRAINT_80E UNIQUE(DATE, BROKER, STOCK_FK);      
ALTER TABLE PUBLIC."default_order_preference" ADD CONSTRAINT PUBLIC.CONSTRAINT_34 UNIQUE(STRATEGY_FK, SECURITY_FAMILY_FK);    
ALTER TABLE PUBLIC."tick" ADD CONSTRAINT PUBLIC.CONSTRAINT_365 UNIQUE(DATE_TIME, SECURITY_FK, FEED_TYPE);     
ALTER TABLE PUBLIC."transaction" ADD CONSTRAINT PUBLIC.CONSTRAINT_7FA UNIQUE(EXT_ID);         
ALTER TABLE PUBLIC."cash_balance" ADD CONSTRAINT PUBLIC.CONSTRAINT_D5 UNIQUE(CURRENCY, STRATEGY_FK);          
ALTER TABLE PUBLIC."security" ADD CONSTRAINT PUBLIC.CONSTRAINT_3892774 UNIQUE(CONID);         
ALTER TABLE PUBLIC."security" ADD CONSTRAINT PUBLIC.CONSTRAINT_389277 UNIQUE(RIC);            
ALTER TABLE PUBLIC."property" ADD CONSTRAINT PUBLIC.CONSTRAINT_C4C UNIQUE(NAME, PROPERTY_HOLDER_FK);          
ALTER TABLE PUBLIC."position" ADD CONSTRAINT PUBLIC.CONSTRAINT_2C9 UNIQUE(SECURITY_FK, STRATEGY_FK);          
ALTER TABLE PUBLIC."portfolio_value" ADD CONSTRAINT PUBLIC.CONSTRAINT_F1C UNIQUE(DATE_TIME, STRATEGY_FK);     
ALTER TABLE PUBLIC."security_family" ADD CONSTRAINT PUBLIC.CONSTRAINT_585 UNIQUE(NAME);       
ALTER TABLE PUBLIC."order_preference" ADD CONSTRAINT PUBLIC.CONSTRAINT_7D3 UNIQUE(NAME);      
ALTER TABLE PUBLIC."allocation" ADD CONSTRAINT PUBLIC.ALLOCATION_ACCOUNT_FKC FOREIGN KEY(ACCOUNT_FK) REFERENCES PUBLIC."account"(ID) NOCHECK; 
ALTER TABLE PUBLIC."security_family" ADD CONSTRAINT PUBLIC.SECURITY_FAMILY_MARKET_FKC FOREIGN KEY(EXCHANGE_FK) REFERENCES PUBLIC."exchange"(ID) NOCHECK;      
ALTER TABLE PUBLIC."trading_hours" ADD CONSTRAINT PUBLIC.TRADING_HOURS_EXCHANGE_FKC FOREIGN KEY(EXCHANGE_FK) REFERENCES PUBLIC."exchange"(ID) NOCHECK;        
ALTER TABLE PUBLIC."order_property" ADD CONSTRAINT PUBLIC.ORDER_PROPERTY_ORDER_FKC FOREIGN KEY(ORDER_FK) REFERENCES PUBLIC."order"(ID) NOCHECK;               
ALTER TABLE PUBLIC."security_family" ADD CONSTRAINT PUBLIC.SECURITY_FAMILY_UNDERLAYING_FKC FOREIGN KEY(UNDERLYING_FK) REFERENCES PUBLIC."security"(ID) ON DELETE CASCADE ON UPDATE CASCADE NOCHECK;           
ALTER TABLE PUBLIC."security" ADD CONSTRAINT PUBLIC.SECURITY_UNDERLYING_FKC FOREIGN KEY(UNDERLYING_FK) REFERENCES PUBLIC."security"(ID) ON UPDATE CASCADE NOCHECK;            
ALTER TABLE PUBLIC."order_preference" ADD CONSTRAINT PUBLIC.ORDER_PREFERENCE_DEFAULT_ACCOC FOREIGN KEY(DEFAULT_ACCOUNT_FK) REFERENCES PUBLIC."account"(ID) ON UPDATE CASCADE NOCHECK;         
ALTER TABLE PUBLIC."transaction" ADD CONSTRAINT PUBLIC.TRANSACTION_ACCOUNT_FKC FOREIGN KEY(ACCOUNT_FK) REFERENCES PUBLIC."account"(ID) ON UPDATE CASCADE NOCHECK;             
ALTER TABLE PUBLIC."subscription" ADD CONSTRAINT PUBLIC.SUBSCRIPTION_STRATEGY_FKC FOREIGN KEY(STRATEGY_FK) REFERENCES PUBLIC."strategy"(ID) ON UPDATE CASCADE NOCHECK;        
ALTER TABLE PUBLIC."order" ADD CONSTRAINT PUBLIC.ORDER_ACCOUNT_FKC FOREIGN KEY(ACCOUNT_FK) REFERENCES PUBLIC."account"(ID) NOCHECK;           
ALTER TABLE PUBLIC."subscription" ADD CONSTRAINT PUBLIC.SUBSCRIPTION_SECURITY_FKC FOREIGN KEY(SECURITY_FK) REFERENCES PUBLIC."security"(ID) ON UPDATE CASCADE NOCHECK;        
ALTER TABLE PUBLIC."component" ADD CONSTRAINT PUBLIC.COMPONENT_COMBINATION_FK FOREIGN KEY(COMBINATION_FK) REFERENCES PUBLIC."combination"(ID) ON DELETE CASCADE ON UPDATE CASCADE NOCHECK;    
ALTER TABLE PUBLIC."stock" ADD CONSTRAINT PUBLIC.STOCKIFKC FOREIGN KEY(ID) REFERENCES PUBLIC."security"(ID) ON DELETE CASCADE ON UPDATE CASCADE NOCHECK;      
ALTER TABLE PUBLIC."holiday" ADD CONSTRAINT PUBLIC.HOLIDAY_MARKET_FKC FOREIGN KEY(EXCHANGE_FK) REFERENCES PUBLIC."exchange"(ID) ON UPDATE CASCADE NOCHECK;    
ALTER TABLE PUBLIC."transaction" ADD CONSTRAINT PUBLIC.TRANSACTION_POSITION_FKC FOREIGN KEY(POSITION_FK) REFERENCES PUBLIC."position"(ID) ON UPDATE CASCADE NOCHECK;          
ALTER TABLE PUBLIC."order_status" ADD CONSTRAINT PUBLIC.ORDER_STATUS_ORDER_FKC FOREIGN KEY(ORDER_FK) REFERENCES PUBLIC."order"(ID) ON DELETE CASCADE ON UPDATE CASCADE NOCHECK;               
ALTER TABLE PUBLIC."transaction" ADD CONSTRAINT PUBLIC.TRANSACTION_STRATEGY_FKC FOREIGN KEY(STRATEGY_FK) REFERENCES PUBLIC."strategy"(ID) ON UPDATE CASCADE NOCHECK;          
ALTER TABLE PUBLIC."transaction" ADD CONSTRAINT PUBLIC.TRANSACTION_SECURITY_FKC FOREIGN KEY(SECURITY_FK) REFERENCES PUBLIC."security"(ID) ON UPDATE CASCADE NOCHECK;          
