CREATE TABLE `security_reference` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) NOT NULL,
  `OWNER_FK` bigint(20) NOT NULL,
  `TARGET_FK` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `SECURITY_REFERENCE_OWNER_FKC` (`OWNER_FK`),
  KEY `SECURITY_REFERENCE_TARGET_FKC` (`TARGET_FK`),
  CONSTRAINT `SECURITY_REFERENCE_TARGET_FKC` FOREIGN KEY (`TARGET_FK`) REFERENCES `security` (`ID`),
  CONSTRAINT `SECURITY_REFERENCE_OWNER_FKC` FOREIGN KEY (`OWNER_FK`) REFERENCES `security` (`ID`)
) ENGINE=InnoDB CHARACTER SET=latin1 ROW_FORMAT=Compact;
