ALTER TABLE `position` DROP `MAINTENANCE_MARGIN`;

ALTER TABLE `future_family` DROP `MARGIN_PARAMETER`;

ALTER TABLE `option_family` DROP `MARGIN_PARAMETER`;

ALTER TABLE `position` DROP `EXIT_VALUE`;

ALTER TABLE `portfolio_value` DROP `MAINTENANCE_MARGIN`;

DROP TABLE `implied_volatility`;

ALTER TABLE `holiday` DROP FOREIGN KEY `HOLIDAY_MARKET_FKC`;
ALTER TABLE `holiday` DROP KEY `HOLIDAY_MARKET_FKC`;
ALTER TABLE `holiday` ADD KEY `HOLIDAY_EXCHANGE_FKC` (`EXCHANGE_FK`);
ALTER TABLE `holiday` ADD CONSTRAINT `HOLIDAY_EXCHANGE_FKC` FOREIGN KEY (`EXCHANGE_FK`) REFERENCES `exchange` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `security_family` DROP FOREIGN KEY `SECURITY_FAMILY_MARKET_FKC`;
ALTER TABLE `security_family` DROP KEY `SECURITY_FAMILY_MARKET_FKC`;
ALTER TABLE `security_family` ADD KEY `SECURITY_FAMILY_EXCHANGE_FKC` (`EXCHANGE_FK`);
ALTER TABLE `security_family` ADD CONSTRAINT `SECURITY_FAMILY_EXCHANGE_FKC` FOREIGN KEY (`EXCHANGE_FK`) REFERENCES `exchange` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
