INSERT INTO `transaction` (`id`, `DATE_TIME`, `QUANTITY`, `PRICE`, `COMMISSION`, `TYPE`, `SECURITY_FK`, `ACCOUNT_FK`, `POSITION_FK`) VALUES
  (-1,'1999-01-01 00:00:00',-1,1000000,0,'CREDIT',NULL,1,NULL);

INSERT INTO `security` (`id`, `ISIN`, `SYMBOL`, `MARKET`, `CURRENCY`, `UNDERLAYING_FK`, `VOLATILITY_FK`, `POSITION_FK`, `ON_WATCHLIST`) VALUES
  (4,'CH0008616382','SMI','M9','CHF',NULL,5,NULL,True),
  (5,'CH0019900841','VSMI','M9','CHF',NULL,NULL,NULL,True);

INSERT INTO `account` (`id`, `CURRENCY`) VALUES
  (1,'CHF');

COMMIT;

